### ISSUE TITLE
change fired twice

### ISSUE THREAD

**Issue by mattdeclaire** [eternicode/bootstrap-datepicker#1002]
It seems the `change` event is firing twice under certain circumstances. `_setDate()` [calls](https://github.com/eternicode/bootstrap-datepicker/blob/8bc254a136110369684dc05a48171682ff1f3a81/js/bootstrap-datepicker.js#L1038) `setValue()`, which fires `change` [here](https://github.com/eternicode/bootstrap-datepicker/blob/8bc254a136110369684dc05a48171682ff1f3a81/js/bootstrap-datepicker.js#L508); and then later fires `change` itself [here](https://github.com/eternicode/bootstrap-datepicker/blob/8bc254a136110369684dc05a48171682ff1f3a81/js/bootstrap-datepicker.js#L1048).

**Comment by acrobat** [comment]
Fixed #1337
