### ISSUE TITLE
In ie11 and firefox latest version date picker is not displaying

### ISSUE THREAD

**Issue by mraju2** [eternicode/bootstrap-datepicker#1012]
Hi, 

please help me , in  ie11 and in firefox latest version date picker is not displaying , in chrome datepicker is working perfectly. I am getting error "object does not support property or method 'date picker'.

Thanks and Regards,
Raju

**Comment by acrobat** [comment]
Closing this issue as I can't reproduce it. If this should still be an issue with the latest release/master please reopen and comment with a jsfiddle example
