### ISSUE TITLE
Arrow next month break Chrome/Firefox after clicked 3 times to forward

### ISSUE THREAD

**Issue by ivanzito** [eternicode/bootstrap-datepicker#1017]
I tested in 

* Chrome 36.0.1985.125 m, 
* Firefox 30.0 
* IE 11

This behavior is very strange because the bootstrap-datepicker work's fine only in IE.

I could see the same behavior [here](eonasdan.github.io/bootstrap-datetimepicker/#example1 "Title") 

I'm using the last version of bootstrap...

**Comment by hebbet** [comment]
closing old tickets, with no newer reply.
