### ISSUE TITLE
ViewMode=2 year issue

### ISSUE THREAD

**Issue by jamiebrohan** [eternicode/bootstrap-datepicker#1018]
Set calendar ViewMode(startMode=2)

Date format is set to dd/mm/yyyy, textbox input is limited to 10 characters.
Calendar works fine apart from if I enter a value that ends with an invalid year value.
Example: Enter "17 June 20" (limited to 10 chars for dd/mm/yyyy format)
When I enter the above and open calendar the Year range shown is "20-29".
Seems like if ViewMode=2 and last character in input box are digits which aren't a valid year the Calendar shows invalid year ranges. (valid range based on the digits though).

![image](https://cloud.githubusercontent.com/assets/4640314/3732927/b3e05300-1702-11e4-9f6a-60c94df1370d.png)

I understand that characters shouldn't be allowed in input box if date format is "dd/mm/yyyy" but wanted to avoid using input mask.

Nasty hack was to add the following to the Update function:
before:
			if (this.dates.length)
				this.viewDate = new Date(this.dates.get(-1));
			else if (this.viewDate < this.o.startDate)
				this.viewDate = new Date(this.o.startDate);
			else if (this.viewDate > this.o.endDate)
				this.viewDate = new Date(this.o.endDate);

after:
			if (this.dates.length)
				this.viewDate = new Date(this.dates.get(-1));
			else if (this.viewDate < this.o.startDate)
				this.viewDate = new Date(this.o.startDate);
			else if (this.viewDate > this.o.endDate)
				this.viewDate = new Date(this.o.endDate);			
			if (this.viewDate.getUTCFullYear().toString().length < 4) {
			    var d = new Date();
			    d.setDate(d.getDate() - 1);
			    d.setHours(1);
			    d.setMinutes(0);
			    d.setSeconds(0);
			    this.viewDate = d;
			}

**Comment by acrobat** [comment]
This bug is fixed with the `assumeNearbyYear` option from #1631. Here is an example on how to use this option (will be release with 1.6.0)

```
$('#datepicker').datepicker({
        format: 'dd.mm.yy',
        assumeNearbyYear: true
    });
```
