### ISSUE TITLE
JSLint - dissallowDanglingUnderscores (should it be added?)

### ISSUE THREAD

**Issue by JenasysDesign** [eternicode/bootstrap-datepicker#1030]
I wondered if "disallowDanglingUnderscores": true, should be added to the JSCS.json file.
The affect of the change would be a series of warnings requiring some JS changes. 

See http://jslinterrors.com/unexpected-dangling-_-in-a

I'm working with Visual Studio's Web essential's addin see: https://github.com/madskristensen/WebEssentials2013 and the default setting for that project includes 

"disallowDanglingUnderscores": true,

What are your thoughts?

**Comment by acrobat** [comment]
@JenasysDesign thanks for the question, we are currently updating our grunt tasks and also the jscs rules in #1185. I will keep your remark in mind when setting up the new rules. For further progress in updating the rules keep an eye out on PR #1185
