### ISSUE TITLE
Orientation attribute not working

### ISSUE THREAD

**Issue by PrimozRome** [eternicode/bootstrap-datepicker#1035]
I am trying to set up orientation attribute but it is ignored and placement is always default. Tried data-date-orientation="bottom auto" and data-orientation="bottom auto" and none of these is working.

**Comment by nestordeharo** [comment]
Not working for me neither, when i put orientation top auto it put in the inverse form

**Comment by kshipp** [comment]
Not working for me either.

**Comment by timothyandrew** [comment]
This still seems to be broken in the demo.

**Comment by Geckomind** [comment]
Same as @kshipp, the orientation it's backwards.

**Comment by dreamweiver** [comment]
Its been a while, there has been no update on this issue. anyway thanks  @kshipp ,it was a tricky thing to be identified.

**Comment by kshipp** [comment]
You're welcome.  Sometimes the easy things are the hardest to find.

**Comment by joarobles** [comment]
Even though I read the docs and it states:

>“orientation” refers to the location of the picker popup’s “anchor”; you can also think of it as the location of the trigger element (input, component, etc) relative to the picker.

I think that orientation of the displayed calendar instead of the anchor would be more natural

**Comment by hebbet** [comment]
seems to be fixed with f08ad04, closing.
