### ISSUE TITLE
How do I disabled dates from now to future?

### ISSUE THREAD

**Issue by paquitodev** [eternicode/bootstrap-datepicker#1043]
How do I disabled dates from now to future? I mean for example if I'm using the component on a birthday field then I can not born on 2020 or something like that, how I disable future dates?

**Comment by acrobat** [comment]
You should work with the [enddate](http://bootstrap-datepicker.readthedocs.org/en/latest/options.html#enddate) option. Use currentdate as the end date to disabled dates in the future
