### ISSUE TITLE
startDate and endDate not working right 

### ISSUE THREAD

**Issue by web-zen** [eternicode/bootstrap-datepicker#1044]
I'm having trouble using startDate and EndDate,  Valid years like 1950 are not shown as clickable but it is clickable along with start/end years on other year panels,  see 2nd image below please.

var minAge = "08/21/2013";
var maxAge = "08/21/1949"; 

$('#datepicker .input-group.date').datepicker({
				startView: 2,
				autoclose: true,
				endDate: minAge,
				startDate: maxAge
}).on("changeDate", function(e){

}); 

http://imgur.com/Gdx419Y,Iz3M7XK
http://imgur.com/Gdx419Y,Iz3M7XK#1

**Comment by acrobat** [comment]
The visual effect is normal behavior as 1950 falls out of the range of 1940 - 1949. Closing this as it is not an bug
