### ISSUE TITLE
changeDate firing three times

### ISSUE THREAD

**Issue by infacq** [eternicode/bootstrap-datepicker#1083]
refer to below stackOverflow

http://stackoverflow.com/questions/22614041/bootstrap-datepicker-on-change-firing-3-times
http://stackoverflow.com/questions/25699007/highstock-inputdateparser-fires-three-times?noredirect=1#comment40285939_25699007

is it really a bug?

**Comment by ehrig** [comment]
I encounter the same issue (v1.3.1), and as I run it via AJAX my Google Map updates three times, which is really confusing to the visitor. Any advice how to fix this?

**Comment by mazelx** [comment]
Not sure about that, I got the same problem... It actually fires twice. Same issue there : https://github.com/eternicode/bootstrap-datepicker/issues/1233

**Comment by dzhk** [comment]
It's correct only for simple datepickre. For datepicker it fires three times!
