### ISSUE TITLE
getDate documentation

### ISSUE THREAD

**Issue by trinzia** [eternicode/bootstrap-datepicker#1087]
Hi,
My forms have possibility for different date formats, but on form submit I want to save all dates in one format.  

I am trying to place result from getDate into a hidden input, so the format display is different than values that will be submitted with form.    However, I'm unable to figure it out from the docs.

When I add the following code, it breaks the browser.  
Error message: Uncaught RangeError: Maximum call stack size exceeded.

    $('.input-datepicker').datepicker()
    .on('changeDate', function(e){
        $(this).parents('.datepicker').find('.value-datepicker').val(  $(this).datepicker('getDate')  );
    }); 

Can you advise a better way to have forms submit the getDate result instead of the input value?

Thanks!

**Comment by stevenspiel** [comment]
I'm also running into that. How did you fix it?

**Comment by acrobat** [comment]
In 1.5.0 the format option was extended with 2 new sub-options toValue and toDisplay. See docs [here](http://bootstrap-datepicker.readthedocs.org/en/v1.5.0/options.html#format)

Could these new options added in 1.5.0 fix this issue?

**Comment by trinzia** [comment]
This looks like exactly the thing I need, in order to get setup correctly.
Thanks so much. :)

**Comment by acrobat** [comment]
Ok, great! Closing the issue!
