### ISSUE TITLE
DatePicker Position Fixed on the Top Of Page

### ISSUE THREAD

**Issue by santokh3386** [eternicode/bootstrap-datepicker#1088]
Hi,
I integrated the datepicker control with bootstrap 3.2. It is working properly like displaying and showing date. But the issue is It is fixed on the top of page no matter where the datepicker control is placed. Scrolling is also not affecting the control, it is still on the top of page.

I tried all the way, Setting its position, orientation (Right, Bottom)  nothing worked.

Please once give your opinion.

Thanks & Regards
S.Singh

**Comment by halilim** [comment]
I was experiencing this problem too. Setting orientation had fixed it. I zeroed in on the problem by removing other scripts one by one, and I've found the offending one: `jquery-ui-1.8.16.custom.min.js`.

Now I don't know the possibility of your problem being the same as mine, just FYI.

**Comment by hebbet** [comment]
seems to be fixed with f08ad04, closing.
