### ISSUE TITLE
noConflict method not working as intended

### ISSUE THREAD

**Issue by kartik-v** [eternicode/bootstrap-datepicker#1100]
The datepicker method is called again in [L1253](https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L1253) and probably another place or so. So using the picker with a noConflict method like the following is not working:

```js
$.fn.bdatepicker = $.fn.datepicker.noConflict();
$("input").bdatepicker(options); // throws an undefined datepicker error at L1253
```

**Comment by acrobat** [comment]
Closing this as it's a duplicate of #736
