### ISSUE TITLE
Key Board functionality not working

### ISSUE THREAD

**Issue by jeevajsb** [eternicode/bootstrap-datepicker#1110]
Key board functionality not working after setting start date or end date.

http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=10%2F21%2F2014&endDate=&startView=0&minViewMode=0&todayBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox

Can you fix this ? Or Can you give work around solution for this ?

**Comment by acrobat** [comment]
Fixed in #1165
