### ISSUE TITLE
Datepicker element css styling not being set when opening

### ISSUE THREAD

**Issue by scrous** [eternicode/bootstrap-datepicker#1135]
I am having an issue. The datepicker is working perfectly, but only the left element style length is being set when the datepicker is opened. The top length is not being set. I don't know what is the cause of this issue. So the datepicker either opens on the end of the page.

The content that contains the datepicker, is inside nav tabs that is inside a bootstrap collapse panel.

The datepicker is binded to the element using knockout.

**Comment by scrous** [comment]
There was some other js that interfered with the positioning on my site. So this is no longer a issue.

**Comment by acrobat** [comment]
Ok thanks for the feedback @scrous!
