### ISSUE TITLE
StartView from year not working with specific option

### ISSUE THREAD

**Issue by romero83** [eternicode/bootstrap-datepicker#1137]
Test Steps:
1. Look the Demo page: http://eternicode.github.io/bootstrap-datepicker/
2. Choose the following options: - startView: 2, minViewMode: 1, autoclose: true
3. Open datepicker (it is opening on year selection which is good)
4. Select a date
5. Click away and open again datepicker

Actual Result: 
Datepicker opening on month selection

Expected Result: 
Datepicker should open on year selection

**Comment by acrobat** [comment]
Fixed in #1304
