### ISSUE TITLE
Datepicker orientation broken when using "component" setting

### ISSUE THREAD

**Issue by NiclasLindqvist** [eternicode/bootstrap-datepicker#1146]
Using the "Component" setup, with the orientation: "auto right" (or other similar settings) makes the datepicker show up on the wrong place. Expected popup to align right to the element, actual result was hanging of the left part of the element.

![image](https://cloud.githubusercontent.com/assets/2562231/4916013/f0b404a0-64d4-11e4-8460-98884fc9911d.png)

**Comment by cruze300** [comment]
Adding to the input html code actually helps. Add this.

data-date-orientation="top auto" inside the input mark up. Hope it helps

**Comment by hebbet** [comment]
seems to be fixed with f08ad04, closing.
