### ISSUE TITLE
Highlight constant date   

### ISSUE THREAD

**Issue by chapster11** [eternicode/bootstrap-datepicker#1162]
Using as a component I'd like to be able to highlight a date on the calendar just like Today highlight. Using setDate allows me to select a new date which will populate the inputs value. I don't want to disturb that functionality I just want to highlight a date on the calendar that constantly stays highlighted. So basically you would have all the same functionality where Today is highlighted (Current functionality), a custom date is highlighted ( New functionality ) and the setDate value is selected ( Current functionality ).    

Any ideas how I could extend the code to do this or if it's already built in and I'm not seeing it in the docs. 
I love this component amazing work.

**Comment by Henri-K** [comment]
+1

**Comment by Henri-K** [comment]
@chapster11  this should do the trick for now: http://stackoverflow.com/questions/22514772/highlight-certain-dates-on-bootstrap-datepicker

**Comment by acrobat** [comment]
Like @Henri-K suggested the `beforeShowDay` option is the way to achieve this. I've created a small example to display the option! http://jsfiddle.net/zcvq0yhh/24/
