### ISSUE TITLE
Create a dist folder

### ISSUE THREAD

**Issue by thiagotalma** [eternicode/bootstrap-datepicker#1166]
It would help a lot if you create a folder /dist with all files generated and will be used on the web (today they are in two separate folders /js and /css).

Like https://github.com/twbs/bootstrap/tree/master/dist

That way we can configure the assets managers to load all the files from the folder /dist.

**Comment by acrobat** [comment]
Closing this issue as PR #1185 introduced a dist directory with all js/css files
