### ISSUE TITLE
setStartDate resetting format

### ISSUE THREAD

**Issue by lazybearonline** [eternicode/bootstrap-datepicker#1180]
When I use the setStartDate method to disable the previous dates, the format resets to default and not the format I chose when instantiating using {format : "d M yyyy"}

**Comment by acrobat** [comment]
Can you verify this is still an issue, I can't reproduce this in 1.3.1. See [example](http://jsfiddle.net/g02L8z8y/6/)

**Comment by lazybearonline** [comment]
Hi Acrobat,
All seems to be working in the [jsfiddle](http://jsfiddle.net/g02L8z8y/9/).
Thanks for getting back to me.

**Comment by acrobat** [comment]
Great thanks @lazybearonline!
