### ISSUE TITLE
Datepicker is not hide in IE11 

### ISSUE THREAD

**Issue by jeevajsb** [eternicode/bootstrap-datepicker#1186]
Datepicker is not hide in IE11 while using mouse to select the date.

But it can be hidden while using keyboard...

How to solve this issue ?

**Comment by acrobat** [comment]
Closing this issue as I can't reproduce it. If the issue still occurs in the latest release or current master please reopen this issue or open a new issue with a link to this and with a [jsfiddle example](http://jsfiddle.net/g02L8z8y/)
