### ISSUE TITLE
Keyboard functionality is not worked as expected

### ISSUE THREAD

**Issue by jeevajsb** [eternicode/bootstrap-datepicker#1187]
Keyboard functionality is not worked as expected. Issues are,
If we set min and max date
1. then we can navigate to disabled date using keyboard (using mouse work as expected).
2. Before select any date, if we use keyboard, then we navigate only on right side (if we already set min date).
3. After select any date, we can navigate using only left and right arrow not by up and down.

**Comment by acrobat** [comment]
Looks like this is fixed with #1590
