### ISSUE TITLE
Publish package on npm

### ISSUE THREAD

**Issue by acrobat** [eternicode/bootstrap-datepicker#1191]
With the release op 1.4.0 we are going to publish this package on npm

**Comment by Dakuan** [comment]
+1

**Comment by theofidry** [comment]
+1

**Comment by A----** [comment]
:+1:

**Comment by binarykitchen** [comment]
When is this going to happen?

**Comment by hebbet** [comment]
@binarykitchen when 1.4 is ready

**Comment by acrobat** [comment]
1.4 should be ready around the end of the month @binarykitchen

**Comment by acrobat** [comment]
@eternicode do you want to publish the release on npm? Or can I do it?

Instructions: https://gist.github.com/coolaj86/1318304

**Comment by acrobat** [comment]
The package is published on npm! https://www.npmjs.com/package/bootstrap-datepicker

**Comment by acrobat** [comment]
@eternicode just create a account like described in the first steps here (https://gist.github.com/coolaj86/1318304) and I will add you as a maintainer!
