### ISSUE TITLE
Start date and end date not working with language specified

### ISSUE THREAD

**Issue by gavinkflam** [eternicode/bootstrap-datepicker#1215]
With start date and/or end date specified, dates available for selection should be limited.
[Sandbox example](http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=12%2F15%2F2014&endDate=12%2F20%2F2014&startView=0&minViewMode=0&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox)

However, with a language specified, it doesn't work anymore.
[Sandbox example](http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=12%2F15%2F2014&endDate=12%2F20%2F2014&startView=0&minViewMode=0&todayBtn=false&clearBtn=false&language=zh-TW&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox)

**Comment by acrobat** [comment]
This is not a bug, but the startdate format should be equal to the date format of the chosen language!
