### ISSUE TITLE
setDate does not work unless time is 00:00:00

### ISSUE THREAD

**Issue by colavitam** [eternicode/bootstrap-datepicker#1221]
When using setDate on an inline datepicker, the selected date is not updated unless the date's time is 00:00:00.

Does not work:
$("#datepick").datepicker('setDate',new Date("2015-02-13 09:30:00"))

Works:
$("#datepick").datepicker('setDate',new Date("2015-02-13 00:00:00"))

Here is a jsfiddle demonstrating the issue:
http://jsfiddle.net/Loe6kfwt/1/

**Comment by odissea** [comment]
I can confirm this behavior using the current stable version (1.3.1).
Unfortunately I don't have the time to localize this problem at the moment.
Any chance @acrobat can look over it?

**Comment by acrobat** [comment]
Yes I will try to come with a fix soon

**Comment by sambenne** [comment]
For me the date is being updated however, it is not selecting the date in the UI.

**Comment by mrchimp** [comment]
I can confirm what sambenne says. The date is "selected" it just doesn't look like it.
