### ISSUE TITLE
Adding CSS classes to years (viewMode 2) doesn't work

### ISSUE THREAD

**Issue by sth519** [eternicode/bootstrap-datepicker#1226]
Adding CSS classes to certain years, for example using the beforeShowDay or onRender callbacks, doesn't work with year selections (minViewMode 2). The functions get called but return values have no effect.

**Comment by acrobat** [comment]
@sth519 please add a jsfiddle example showing the case, makes it easier to debug ;) You can use [this jsfiddle](http://jsfiddle.net/g02L8z8y/) as a base to create your case!

**Comment by sth519** [comment]
Simplified example: http://jsfiddle.net/ro9ufa3k/1/

If you comment out the view mode settings, everything works as documented. However, I have not found a way to assign classes in the year selection mode.

**Comment by sth519** [comment]
Any ideas on how to fix this? I'm not familiar with the codebase of this project, so any pointers in the right direction are highly appreciated.

Thanks!

**Comment by sth519** [comment]
Any ideas?

**Comment by acrobat** [comment]
The option you use in the example is the before show day callback and it only applies to the day viewmode. There is another option 'beforeShowMonth' but there is not one yet for the year view

So if I understand you correct, what you try to achieve needs an new option 'beforeShowYear'?

**Comment by sth519** [comment]
Yes. The reason is that I need to highlight certain years in the dropdown list.

**Comment by acrobat** [comment]
Ok, I will label this issue as an feature and have it go into the 1.5.0 release!

**Comment by sth519** [comment]
Thanks!

**Comment by acrobat** [comment]
Fixed in #1436
