### ISSUE TITLE
Allow default date for picker with empty input

### ISSUE THREAD

**Issue by mkleehammer** [eternicode/bootstrap-datepicker#1229]
There are cases where I'd like to leave the date input empty but have the datepicker start at a date other than day.  Is this possible today?

For example, in one case I have a search form and an obvious start date for this is "30 days ago".  However I don't want to set a value and require the user to clear it out when they don't want it.  Instead, I'd like to start the control empty but have the picker default to 30 days in the past.

**Comment by acrobat** [comment]
Yes that's possible with the new "defaultViewDate" option introduced in #893 and will be released in 1.4.0!
