### ISSUE TITLE
1.3.1 - Won't popup if field is ReadOnly

### ISSUE THREAD

**Issue by KrunchMuffin** [eternicode/bootstrap-datepicker#1231]
It worked previously. When I removed ReadOnly, it worked, but the calendar was not correctly positioned.

**Comment by balojs** [comment]
+1

**Comment by acrobat** [comment]
In 1.3.1 the behavior with readonly fields didn't change, but in 1.4.0 this PR #1136 was merged and removed the possibility to attach datepicker to a readonly field. But maybe we have to revisit that PR to introduce an option to allow/disallow to ability to attach to a readonly field or revert the PR all together!

[Here you can see](http://jsfiddle.net/g02L8z8y/15/) that it still works on 1.3.1

**Comment by KrunchMuffin** [comment]
Not sure what version I have then because it is not listed in the header comments. Probably good idea to add that. I have reverted to 1.3.0 for now. Hopefully I am not missing anything critical.

**Comment by KrunchMuffin** [comment]
I think reverting the PR would be a good start.

**Comment by hebbet** [comment]
@KrunchMuffin thanks for suggestion to include the version in the file comments, filed a bug #1238

**Comment by patxisan** [comment]
+1 to introduce an option to allow/disallow to ability to attach to a readonly field

**Comment by orl** [comment]
datesDisabled is missing in 1.3.1

**Comment by natsu90** [comment]
+1 to revert the PR. The datepicker should be disabled on `disabled` attribute, instead of `readonly`. Readonly is useful to disallow user to edit datepicker input directly; `02/26/201` is treated as a valid date.

**Comment by acrobat** [comment]
The release of 1.4.0 is close, but i think we can't let this pass without a fix. So my idea is to add an option to don't show to datepicker if the field is readonly (like #1136 added) and keep the default behavior as it was before that PR was merged!

I will add that options this weekend and try to get the 1.4.0 release ready!

**Comment by hebbet** [comment]
+1

**Comment by acrobat** [comment]
I've created a PR for this option #1280. Please review it so we can merge it in a few days so it gets into the 1.4.0 release
