### ISSUE TITLE
The Github link in the online doc page does not work 

### ISSUE THREAD

**Issue by benjamin19890721** [eternicode/bootstrap-datepicker#1247]
There is a link at the online doc ( http://bootstrap-datepicker.readthedocs.org/en/release/ ) with "Edit on Github" as the text. This link does not link back to this Github page.

**Comment by vsn4ik** [comment]
Bootstrap-datepicker team, remove `release` branch (or change to `master`) from online docs (ReadTheDocs.com).

**Comment by acrobat** [comment]
@eternicode can you take a look at this or can you give me access to the online docs? the release branch is deleted on github but it needs manual deletion on readthedocs?

**Comment by eternicode** [comment]
Fixed, "stable" and "release" docs have been disabled.

**Comment by acrobat** [comment]
Thanks @eternicode but the only problem is that if you go to http://bootstrap-datepicker.readthedocs.org/ it redirect to http://bootstrap-datepicker.readthedocs.org/en/release/ and that way the release/stable docs are still visible

**Comment by eternicode** [comment]
My bad, root now redirects to /en//latest/
