### ISSUE TITLE
Year To Month

### ISSUE THREAD

**Issue by btecu** [eternicode/bootstrap-datepicker#1249]
I want to collect months and years and I would like to pop up the years view and once you select a year, to see the months view automatically.
Is it possible to open months view after I select something from years view?
It would be really useful because is not very obvious Years is clickable.

Something like this:
http://eonasdan.github.io/bootstrap-datetimepicker/#min-view-mode

**Comment by hebbet** [comment]
so you don't want to use the day for that project, only year and month?

**Comment by btecu** [comment]
I use day too, but for most cases I only need month and year.

**Comment by hebbet** [comment]
Did you try startView: 1
http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=1&minViewMode=0&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox

**Comment by btecu** [comment]
Yes I did. The month starts showing up and I click on it and the date is set. Nothing else happens.

What I want is to click on the Month and then automatically switch to Year view.
Something like this (click on Min View Mode icon): http://eonasdan.github.io/bootstrap-datetimepicker/#min-view-mode

**Comment by btecu** [comment]
No longer care.
