### ISSUE TITLE
Setting startDate and endDate via data-attribute seems to be broken?

### ISSUE THREAD

**Issue by pgr1973** [eternicode/bootstrap-datepicker#1250]
If I try to set the startDate and the endDate via data-attribute of the input-field:

`<input id="inputBirthDate" type="text" name="inputBirthDate" class="datepicker" data-provide="datepicker" data-date-startdate="-120y" data-date-enddate="-18y">`

The values for startDate and endDate are ignored. Also `data-date-endDate`, `data-date-startDate` and `data-endDate` and `data-startDate` are ignored.

Invoking the Datepicker via JS:
`$('input#inputBirthDate').datepicker({
    startDate: "-120y",
    endDate: "-18y"
});`

works perfectly. :-)

Is there a way to set startDate and endDate via data-attributes? Or any other way, besides invoking it via JS-Bindings?

**Comment by hebbet** [comment]
which version do you use?

**Comment by pgr1973** [comment]
Version 1.3.1

**Comment by peternijssen** [comment]
I believe data-date-start-date="" works.

**Comment by pgr1973** [comment]
Yep, that works. :-) Thank you very much ...

**Comment by acrobat** [comment]
Yes indeed capital letters do also need to seperated by a "-" (dash). Added a label to this ticket to add that behavior to the docs!

**Comment by acrobat** [comment]
The docs for this issue already exists [here](http://bootstrap-datepicker.readthedocs.org/en/latest/options.html#options). So closing this issue! Thanks for the report!

**Comment by controlqtime** [comment]
Sorry, but for me is working 
`data-start-date=""` and `data-end-date=""`
with v1.6.4

**Comment by Mijoh** [comment]
Sorry, but for me is working 
data-start-date="" and data-end-date=""
with v1.6.4

**Comment by Mijoh** [comment]
Sorry, but for me is working 
`data-start-date=""` and `data-end-date=""`
with v1.6.4

**Comment by morfeus5000** [comment]
funciona si haces un $('#fecha1').attr('data-start-date','-120y');
 $('#fecha2').attr('data-end-date','-18y');
