### ISSUE TITLE
Disabled prev/next buttons to remain visible

### ISSUE THREAD

**Issue by enstyled** [eternicode/bootstrap-datepicker#1260]
Currently, when you reach the start/end-date, the prev/next button gets "visibility: hidden".

Perhaps it would be better to get a class, e.g. "disabled" so it can be styled accordingly - be it hidden or with some opacity?

**Comment by GitBorisJohnson** [comment]
+1

**Comment by spenat28** [comment]
I would also like this. Now it's not possible to have different bg for header for example. You can leave visibility there,we can override it with visibility: visible !important;   ... but it also caouses, that You are able to click throw disabled months in calendar ...

**Comment by mediavrog** [comment]
+1
 totally useful for custom styling of background for example

**Comment by amit1911** [comment]
+1

**Comment by acrobat** [comment]
I've added the disabled class in d58e500. Will be released in 1.7.0!
