### ISSUE TITLE
Entering 1/1/15 receives NaN/NaN/NaN after clicking on date

### ISSUE THREAD

**Issue by cgsmith** [eternicode/bootstrap-datepicker#1264]
Hello! This report is on behalf of [Lord Vincent](https://twitter.com/PaulVRudolph)!

You can get a NaN error appearing in the to field.

To Replicate:
1. Click date picker
2. Type in a number like 1/2/14
3. While the date picker is still visible, pick a date on the date picker
4. The value that will display in the to field will be "NaN/NaN/NaN"

I'll take a crack at this later this week but **needed** to report it! Cheers!

![How to reproduce... the error.](https://cloud.githubusercontent.com/assets/570018/6099836/1ad66ff4-afc9-11e4-8c50-25386e8ed4df.png)
![NanNanNana showing](https://cloud.githubusercontent.com/assets/570018/6099837/1ad8551c-afc9-11e4-845e-eba3db3ea490.png)

**Comment by vsn4ik** [comment]
@cgsmith use:
http://bootstrap-datepicker.readthedocs.io/en/stable/options.html#assumenearbyyear
http://bootstrap-datepicker.readthedocs.io/en/stable/options.html#format

@acrobat, @hebbet, @eternicode please close this PR.

**Comment by cgsmith** [comment]
Thanks for the update @vsn4ik!
