### ISSUE TITLE
RegExp in js/bootstrap-datepicker.js

### ISSUE THREAD

**Issue by vsn4ik** [eternicode/bootstrap-datepicker#1270]
I can see the use of `/^<s1>|...|<sn>$/`.
This not equivalent `/^(<s1>|...|<sn>)$/`, and equivalent `/(^<s1>|...|<sn>$)/`.

Please check it.

**Comment by acrobat** [comment]
Can you provide a line number where we use that regexp? And what exactly wrong with it?

**Comment by hebbet** [comment]
closing old tickets :-)
