### ISSUE TITLE
Lack of new version (1.4.0) in Bower.

### ISSUE THREAD

**Issue by ssset** [eternicode/bootstrap-datepicker#1275]
Latest version available in Bower is 1.3.1 (see screenshot) but it should be 1.4.0.
![boostrap datepicker bower](https://cloud.githubusercontent.com/assets/9088754/6345464/b4441922-bc06-11e4-9e61-a9c3ac5c9b4f.png)

**Comment by acrobat** [comment]
1.4.0 is not yet released but it should be around the end of the month
