### ISSUE TITLE
  IE8 error because of hoursDisabled.indexOf(i)

### ISSUE THREAD

**Issue by phax** [eternicode/bootstrap-datepicker#1283]
IE8 does not support Array.indexOf()

I originally posted the error on a fork: https://github.com/smalot/bootstrap-datetimepicker/issues/330

The proposed solution from @amnesia7 using `jQuery.inArray` worked fine for me!

**Comment by hebbet** [comment]
the datepicker here doesn't have an hoursDisabled options

**Comment by phax** [comment]
Sorry my fault - I seemed to have mixed downloaded branches - mea culpa
