### ISSUE TITLE
Grunt screenshot doesn't show datepicker correct

### ISSUE THREAD

**Issue by acrobat** [eternicode/bootstrap-datepicker#1286]
We running the phantomjs screenshots grunt task, the screenshots don't get generated correctly

The datepicker popup show above the field instead of under the field, that way the popup isn't shown on the screenshots

But I don't know how to debug it or why it is broken (because running a manual example the popup shows correct). So anyone know how to debug/fix this?

Just run following commands to reproduce (compare with the images currently in the docs/_static/screenshots dir

```shell
$ npm install
$ grunt screenshots
```

This is the last issue before the 1.4.0 release is ready!

/cc @eternicode @hebbet @abeverley

**Comment by hebbet** [comment]
hm, make screenshots manually this release?

**Comment by acrobat** [comment]
Manual screenshots s no great solution, but I'm going to put out the 1.4.0 release tomorrow but just don't generate new screenshots (and fix this issue for 1.4.1) because there hasn't changed much on the screenshots (lot's of extra options, methods etc). That way the release can finally happen and we have some extra time to fix this issue!
