### ISSUE TITLE
Datepicker-Months and DatePicker-Years styling really messed up.

### ISSUE THREAD

**Issue by Godrules500** [eternicode/bootstrap-datepicker#1288]
When I load the datepicker, the days viewmode works great and looks beautiful. However, if I use the months or Year viewmode, the content of the container extends way out of the container.

I would insert a picture, but I can't so below is an illustration represents what I'm talking about.  The container is there and the correct size. It's the DatePicker's content that is ignoring its parent container.

I am using this with latest BootStrap.

|-----------------------------|
|<----------2015--------->|
| Jan  Feb Mar Apr M|ay June July August Sept - Dec
[_________________|

**Comment by hebbet** [comment]
can you provide a screenshot or even better an working example?

**Comment by Godrules500** [comment]
![image](https://cloud.githubusercontent.com/assets/318063/6510348/81e55084-c333-11e4-880f-54ca640cad24.png)

**Comment by Godrules500** [comment]
here is the html. I do notice that it is putting them all in the same row instead of splitting it



![image](https://cloud.githubusercontent.com/assets/318063/6510371/aa5f9718-c333-11e4-9df5-7a36fbf26529.png)

**Comment by hebbet** [comment]
ok, debugging a screenshot is not possible, so i request you to give us a link to that page or a jsfiddle of tha problem

**Comment by Godrules500** [comment]
Lol, I'm an idiot. I had looked in bootstraps and bootstrap-datepicker's css and extensively debugged the bootstrap-datepicker.js file.  BUT in my wonderful local css, I had something that had 

td {white-space:nowrap} 

which was causing all of the problems.  Thank you hebbet for helping me try to figure it out.
