### ISSUE TITLE
Add a main field to package.json to allow CommonJS usage

### ISSUE THREAD

**Issue by plumlee** [eternicode/bootstrap-datepicker#1298]
We use browserify for bundling, and a simple change to the `package.json` file like this:
```
"main": “dist/js/bootstrap-datepicker.js",
```
would allow code as follows when we want to load the date picker.
```
var datepicker = require(‘bootstrap-datepicker’)
```

Currently, we have to do this so that the correct module is found.
```
  "browser": {
    "bootstrap-datepicker": "./node_modules/boostrap-datepicker/dist/js/bootstrap-datepicker.js",
}
```

I’ll do the PR if you’re open to this.

**Comment by hebbet** [comment]
sure make a PR  :-)

**Comment by acrobat** [comment]
A PR is not necessary as #1285 adds this property!

**Comment by plumlee** [comment]
Thanks for that catch - I should have searched more thoroughly.

**Comment by acrobat** [comment]
no problem @plumlee, thanks for the interest in the project!
