### ISSUE TITLE
Cannot set property 'pt' of undefined

### ISSUE THREAD

**Issue by pdcmoreira** [eternicode/bootstrap-datepicker#1299]
I'm getting this error when trying to use the 'pt' locale:

![datepicker pt](https://cloud.githubusercontent.com/assets/4430606/6617599/321df7fc-c8b2-11e4-847d-2a494cc196c0.png)

**Comment by acrobat** [comment]
@pdcmoreira I can't reproduce this problem with the latest release, see http://jsfiddle.net/zkufmh7a/1/

**Comment by hebbet** [comment]
closing old tickets, with no newer reply.
