### ISSUE TITLE
Bower Pulling Old Version

### ISSUE THREAD

**Issue by prionkor** [eternicode/bootstrap-datepicker#1308]
I just installed the plugin via bower. It is pulling version `1.4.0`. Any idea why?

**Comment by acrobat** [comment]
1.4.0 is the latest released version, which version did you expect to be pulled by bower?

**Comment by prionkor** [comment]
Some of files says 1.5.0 or it isn't stable yet?

https://github.com/eternicode/bootstrap-datepicker/blob/master/dist/js/bootstrap-datepicker.min.js
https://github.com/eternicode/bootstrap-datepicker/blob/master/bower.json

**Comment by acrobat** [comment]
no 1.5.0 is the current development version, 1.4.0 is the latest released version

This is what the `bower info bootstrap-datepicker`command gives as output

```
Available versions:
  - 1.4.0
  - 1.3.1
  - 1.3.0
  - 1.3.0-rc.6
  - 1.3.0-rc.5
  - 1.3.0-rc.4
  - 1.3.0-rc.3
  - 1.3.0-rc.2
  - 1.3.0-rc.1
  - 1.2.0
  - 1.2.0-rc.1
  - 1.1.3
  - 1.1.2
  - 1.1.1
  - 1.1.0
  - 1.0.2
  - 1.0.2-rc.2
  - 1.0.2-rc.1.1
  - 1.0.2-rc.1
  - 1.0.1
  - 1.0.0
```

So you should require 1.4.0 in your bower config

**Comment by prionkor** [comment]
thank you. I thought something was wrong..
