### ISSUE TITLE
Edit css 'z-index' parameter to raise the calendar above the bootstrap modal window

### ISSUE THREAD

**Issue by masterdany88** [eternicode/bootstrap-datepicker#1309]
Hey. I am trying to use datepicker with this modal library:
https://github.com/nakupanda/bootstrap3-dialog
https://nakupanda.github.io/bootstrap3-dialog/

but unfortunatelly calendar shows under the dialog window.
Please help me

**Comment by acrobat** [comment]
which version of the datepicker do you use? And can you provide an example using [this jsfiddle](http://jsfiddle.net/vh1oknf7/) to show if this is still an issue on the 1.4.0 release

**Comment by masterdany88** [comment]
Hey. After You post, I've checked version. I've used 1.3.0. Now after update to 1.4.0 version the problem is gone. Thanks For Your help.
