### ISSUE TITLE
Using orientation:auto but date picker still appears above, cut off, when there plenty of space below.

### ISSUE THREAD

**Issue by trusktr** [eternicode/bootstrap-datepicker#1317]
In the screenshot, the orientation is set to "auto" so we'd expect the calendar to appear below insead of cut off above:

![screen shot 2015-03-17 at 1 00 23 pm](https://cloud.githubusercontent.com/assets/297678/6696320/b334fb00-cca5-11e4-92da-8ea4fe975fc6.png)

**Comment by acrobat** [comment]
Thanks for the bug report! It's indeed an issue and we will try to fix it soon. This is [an example](http://jsfiddle.net/vh1oknf7/1/) to show to issue

**Comment by osama9** [comment]
![capture](https://cloud.githubusercontent.com/assets/3780410/6776033/92f3f5ae-d14a-11e4-8d72-faf3ac0371fc.PNG)

I did a workaround by changing the following line:

```javascript
    if (Math.max(top_overflow, bottom_overflow) === bottom_overflow)
		yorient = 'top';
```

To:

```javascript
    if (Math.max(top_overflow, bottom_overflow) === bottom_overflow || scrollTop === 0)
		yorient = 'top';
```

This is the result: 
![capture](https://cloud.githubusercontent.com/assets/3780410/6776130/c53c2dd2-d14b-11e4-9ea6-d2b3d372140a.PNG)

**Comment by acrobat** [comment]
Thanks @osama9! The fix you propose is possibly also a fix for #1286, I will take a look at it later today!

**Comment by torrobinson** [comment]
Hmm there's definitely something else causing this then, as that fix hasn't solved my issue (though circumstances are probably different).

Mine still goes out of view when the orientation is set to "auto":
![](https://s3.amazonaws.com/f.cl.ly/items/1h1d0B023S2c0z1r0g2H/Image%202015-04-11%20at%206.56.18%20PM.png) 

So something in the auto logic is missing when the picker is at the very top of a fixed-position element (a panel stuck to the side in my app). Any ideas?

**Comment by lode** [comment]
:+1:

The proposed javascript workaround works fine for datepickers which open to the top (and fall off the screen) but not for ones opening to the bottom.

**Comment by alvin0618** [comment]
you can use container to solve this
<code>

		$('#date-range').datepicker({
			format: 'yyyy-mm-dd', 
			clearBtn: true,
			autoclose: true,
			disableTouchKeyboard: true,
			inputs: $('input[name="date-range-start-date"],input[name="date-range-end-date"]').toArray(),
			container: '#date-range-picker-container'
		});

</code>

**Comment by asessa** [comment]
Alternative solution: 

if (Math.max(top_overflow, bottom_overflow) === bottom_overflow && top_overflow > 0 || bottom_overflow < 0)

**Comment by asessa** [comment]
I've updated it again with a more simple 

if (top_overflow > 0)

Always display calendar on top if there is space.

I've updated the fiddle example, can you test this ? 

Example: 

http://jsfiddle.net/vh1oknf7/73/

**Comment by lode** [comment]
Looks promising!
In my own project (behind closed doors sorry) I only see only problem: it falls behind a fixed positioned element, instead of dropping in the other direction.

Further, also in the fiddle, the little arrow is wrongly positioned. Pointing the other direction as the input field is.

**Comment by asessa** [comment]
Looks like the css (position-bottom / top) are inverted, updated.

http://jsfiddle.net/asessa/pnd6e36k/2/

**Comment by lode** [comment]
I found a simple repro for the problem I'm having with fixed elements: using the default fixed navbar from bootstrap: http://jsfiddle.net/4hmcd1ug/

But maybe this is another bug, making it work with fixed navbars.

**Comment by asessa** [comment]
Do you mean this: 

http://jsfiddle.net/asessa/4hmcd1ug/1/

**Comment by asessa** [comment]
Test with scrolling: 

http://jsfiddle.net/asessa/4hmcd1ug/2/

**Comment by lode** [comment]
Sorry, forgot to save: http://jsfiddle.net/4hmcd1ug/4/

Just before it should dropdown, it falls behind the navbar.

![datepicker-with-fixed-navbar](https://cloud.githubusercontent.com/assets/511245/8638010/d75f0d6a-28ab-11e5-8ce3-a818671913bd.png)

**Comment by asessa** [comment]
It's a z-index problem because can't retreive nav (using parents) z-index. I've set a minimum z-index of 1080, maximum z-index on bootstrap is currently 1070 used by tooltip, so this should work with any bootstrap component.

http://jsfiddle.net/asessa/4hmcd1ug/5/

**Comment by lode** [comment]
Yeah. Of course.

Maybe good to pick a z-index which sits at a correct hierarchy? Above elements which are always there like a navbar but below interactive elements like a tooltip? In that way a tooltip inside the datepicker would still work.

**Comment by richinator38** [comment]
@asessa , your fix works for me except for when I minify the javascript.  If I deploy with non-minified js, it works.  Not sure why that is.  It was the same way with the version you didn't modify.

**Comment by asessa** [comment]
@richinator38 there were a few console.log used for debugging, try with this version please:
http://jsfiddle.net/asessa/4hmcd1ug/6/

**Comment by richinator38** [comment]
Didn't work.
![calendar-issue](https://cloud.githubusercontent.com/assets/9600779/8704391/4a988d40-2ae8-11e5-95b0-7271d814af71.png)

**Comment by asessa** [comment]
The blue bar is a fixed navbar ? what is the current z-index ?

**Comment by richinator38** [comment]
Yes it is, 1030.

**Comment by asessa** [comment]
Can you send me a fiddle or link (even privately) to check ?

**Comment by richinator38** [comment]
Sure, I'll work on it.

**Comment by richinator38** [comment]
http://plnkr.co/edit/ZSaS5200aePHueiOcW6c?p=preview

**Comment by asessa** [comment]
I've changed the minified version using my latest jsfidlde version and it's working

http://plnkr.co/edit/JDNK3uMJAoh4TFCpa0yR?p=preview

**Comment by richinator38** [comment]
Ah, maybe the ASP.NET MVC minification is breaking it?  That's what mine was using.

**Comment by richinator38** [comment]
Thanks for your help!  Works for me now.  I'm not letting MVC minify it, just using yours.  I'll leave it in the plunker.

**Comment by asessa** [comment]
Probably MVC is too aggressive

**Comment by hebbet** [comment]
fixed.
