### ISSUE TITLE
Add an option to automatically update the date field when a year or month is selected

### ISSUE THREAD

**Issue by nicolasmccurdy** [eternicode/bootstrap-datepicker#1323]
I am working on an application which uses bootstrap-datepicker for a form field asking for a user's birthday. In some cases, a user could try to edit a date they have already entered by updating the year or month in the datepicker. However, this does not save the new date to the input field until the user chooses the date again, which means that it is possible for the user to not realize that their change did not occur and cause them to submit the wrong date.

I have created [an example](http://codepen.io/nicolasmccurdy/pen/RNEboj) which uses the datepicker's events to force input field updates when the year or month change. I think it would be useful if there was an option to enable this behavior built into the datepicker.

**Comment by nicolasmccurdy** [comment]
I updated my example, the JavaScript is a bit simpler now.

**Comment by hebbet** [comment]
can you provide a pull request against current master?

**Comment by nicolasmccurdy** [comment]
I added this option in #1327.

**Comment by acrobat** [comment]
Thanks @nicolasmccurdy! I will review the PR soon!
