### ISSUE TITLE
Pop box position error

### ISSUE THREAD

**Issue by ddyllen-z** [eternicode/bootstrap-datepicker#1325]
![2015-03-20_155728](https://cloud.githubusercontent.com/assets/5013530/6747905/8c9b25a6-cf1a-11e4-968d-7dfd68c3eb71.png)

html:

    <div class="input-daterange input-group" id="datepicker">
		 <input class="form-control datepicker" readonly="readonly" type="text" class="form-control" placeholder="起始时间"  name="dateStart">
		 <span class="input-group-addon add-on">&nbsp;-&nbsp;</span>
		 <input class="form-control datepicker" readonly="readonly" type="text" class="form-control" placeholder="结束时间" name="dateEnd">
    </div>

js:

    $('.input-daterange').datepicker({
		language : "zh-CN",
		format : "yyyy-dd-mm"
      });

Thanks!

**Comment by hebbet** [comment]
thanks for the report, can you provide a jsfiddle?

**Comment by ddyllen-z** [comment]
It's ok when i refresh the page at a moment ago. i'm not edit any code.
i don't konw what happend.
Thanks!

**Comment by hebbet** [comment]
ok, will close that issue
