### ISSUE TITLE
Firefox and IE, January of 100

### ISSUE THREAD

**Issue by MrTarantula** [eternicode/bootstrap-datepicker#1331]
Datepicker goes crazy in Firefox and IE when attempting to access January of year 100. The window freezes for a long time, then the Datepicker fills the height of the window and shows multiple months.

This issue does not occur in Chrome.

**Comment by hebbet** [comment]
Possible #1556 fixes your problem

**Comment by hebbet** [comment]
closing this as it is a duplicate of #1103
