### ISSUE TITLE
 in-line datepicker disappears on blur.

### ISSUE THREAD

**Issue by acrobat** [eternicode/bootstrap-datepicker#1342]
This issue was reported by email

---

The latest changes to the datepicker cause the in-line calendar to disappear on blur.

At line 381
  this.hide();
has been replaced by:
  $(this.picker).hide();

The internal hide() returns if the datepicker is inline.

Regards
Ivano Vingiani

---

This bug was introduced with PR #1322

- [ ] find solution to fix this issue but keep #1145 also fixed
- [ ] add test to prevent future regression

**Comment by 3rdPancake** [comment]
how about this on line 381 ?
```javascript
this.isInline ? true : $(this.picker).hide();
```
not sure about returning true, but this can prevent from hiding inline datepicker on blur.

**Comment by acrobat** [comment]
Yeah that looks like a possible fix, I will test it later and if it works add a test for it to prevent future regression

**Comment by trinzia** [comment]
This is probably same as my issue #1339.

**Comment by acrobat** [comment]
Looks like this issue is fixed in #1399
