### ISSUE TITLE
[Bug]Selecting date out of range

### ISSUE THREAD

**Issue by sahilbabbar** [eternicode/bootstrap-datepicker#1346]
The user is able to select a date that comes before than the date selected on the first click. This happens when one input is assigned "dpd1" id and the other is assigned "dpd2".

**Comment by acrobat** [comment]
Hi @sahilbabbar, can you provide a jsfiddle example showing the problem? You can use [this jsfiddle](http://jsfiddle.net/vh1oknf7/) as a base!

**Comment by hebbet** [comment]
closed due inactivity, feel free to reopen
