### ISSUE TITLE
problem not show the menu

### ISSUE THREAD

**Issue by Q8HMA** [eternicode/bootstrap-datepicker#1351]
Hello

i have problem my code not work fine in my site but it work good on jsfiddle

same code same url 

here it work fine http://jsfiddle.net/vh1oknf7/8/

but on my site not work

any help ??

is there any issue if i used https + http ??

**Comment by hebbet** [comment]
> is there any issue if i used https + http ??

when your site is running on https, and you are loading the scripts via http, most browser will block it, as unsafe script.

**Comment by Q8HMA** [comment]
my site used http not https but the some java used https

**Comment by Q8HMA** [comment]
i used css:
Bootstrap v3.1.1
Jasny Bootstrap v3.1.3
Video.js Default Styles 4.2.2

js :
jQuery v1.11.0
Video.js v4.2.2
Jasny Bootstrap v3.1.3
Bootstrap v3.1.1

its ok or i need to upgrade ???

thnx

**Comment by Q8HMA** [comment]
any help ??

**Comment by hebbet** [comment]
can you provide a link to your site?

**Comment by engrmostafijur** [comment]
www.pixelsolutin4it.com

**Comment by Q8HMA** [comment]
Hello this test page

http://demo.q8hm.net/demo.html

**Comment by acrobat** [comment]
This is the error you recieve:

`Uncaught ReferenceError: $ is not defined`

The code block using the datepicker is defined before jquery is included

```

	$("#date-daterange .input-daterange").datepicker({
		format: "yyyy-mm-dd",
		startDate: "2014-09-20",
		endDate: "+0d",
		forceParse: false,
		autoclose: true,
		todayHighlight: true
	});
```

Either you include jquery above this code block or include jquery in your head section

**Comment by Q8HMA** [comment]
Thnx bro u help me alot i was thinks to remove it :)

**Comment by Q8HMA** [comment]
Hi i have little problem it not work fine if bootstrap is rtl

**Comment by Q8HMA** [comment]
LTR = http://demo.q8hm.net/demo-ltr.html

RTL = http://demo.q8hm.net/demo-rtl.html

**Comment by Q8HMA** [comment]
when u click on white space it going biger

**Comment by Q8HMA** [comment]
and when u click the input box is be biger

**Comment by Q8HMA** [comment]
this links for original css with rtl and rtl

http://demo.q8hm.net/demo2-ltr.html
http://demo.q8hm.net/demo2-rtl.html

**Comment by acrobat** [comment]
This is indeed a bug, can you please submit a separate issue for it? And please include the demo page + a jsfiddle example! (You can use [this jsfiddle](http://jsfiddle.net/q7rLt8vs/) as a base, it includes the latest stable version + a rtl language)
