### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Azaret** [eternicode/bootstrap-datepicker#1352]
Ok, so I would like to blame 786e26b4fe7dd9eb9a4dc795cab755c73a76f8aa and 34cae23af9d2426318e0a772b71277713f888a8f.

First about 34cae23af9d2426318e0a772b71277713f888a8f, Per design dates are capitalized in bootstrap-datepicker, so it makes no sense to have it lowered in French. Yes in French we should not put capitalize a month or a day inside a date or a sentence, but in this case it's neither of both cases. So it should keep the bs-dp design.

Then 786e26b4fe7dd9eb9a4dc795cab755c73a76f8aa, Once again, per design bs-dp used to not put dots, in all languages even it should be put in almost all, even English. So again it's a nonsense to have French with dots and not the others. Also the commit point an article which state "Recommendations" about abbreviating months. There is no official rules, so it is completely fine to stay at 3 letters. That said, if you want to stay on those recommendations its should be "Avr" not "Avril".

I'm not sure those changes are worth breaking the bs-dp design since there is no mandatory rules.

**Comment by acrobat** [comment]
@Azaret there was a discussion about it in #1252, if you have a different opinion about it please create a PR with the desired fixes and then we can have a discussion with the other people who commented in #1252

**Comment by Azaret** [comment]
Ok I didn't saw this PR, maybe I will rather comment there so we could maybe reopen this PR ?

**Comment by acrobat** [comment]
Yeah discussion can continue in the PR and can be reopend or recreated if necessary
