### ISSUE TITLE
Allow user to choose time?

### ISSUE THREAD

**Issue by nhouse** [eternicode/bootstrap-datepicker#1354]
Is there a way to allow users to choose time as well as day? I don't see a way to do this from the docs, but just want to check before looking for an alternative plugin since this works so well.

**Comment by acrobat** [comment]
There is PR submitted to add time picking here #909, but I think there is still a bit work todo to finish the feature

But this is certainly something we want to add in a future version!

**Comment by acrobat** [comment]
Closing this issue, time picking will possibly be added in 2.X or 3.X. Roadmap is still something to be determined!
