### ISSUE TITLE
autoclose should be true by default.

### ISSUE THREAD

**Issue by ravshansbox** [eternicode/bootstrap-datepicker#1361]

**Comment by acrobat** [comment]
We could change the behavior but that would mean a "soft" BC break, if you want to you can open a PR to change it and then we can discus it there. But generally I would introduce these kind of changes in 2.0

**Comment by iltera** [comment]
I second that request. After changing the date and still seeing the picker on the screen is not the default behaviour on other datepickers around.

I tried to change that behaviour with options, but couldn't find it. Can you please send a link to the documentation of this setting?

**Comment by ravshansbox** [comment]
yes, I might say same, mostly it's used with autoclose setting to true.
