### ISSUE TITLE
Bootstrap Datepicker defaults global setting

### ISSUE THREAD

**Issue by pottabathini** [eternicode/bootstrap-datepicker#1363]
I want to set global options for datepicker currently I written code like

//global configuration for datepicker                   
 $.datepicker.defaults = { todayHighlight: true, autoclose: true, format: "mm-dd-yyyy" };
 $("#ReviewDate").datepicker();

but it is not supporting, when I write like below it got work.
$("#ReviewDate").datepicker({ todayHighlight: true, autoclose: true, format: "mm-dd-yyyy" });

I followed this https://github.com/eternicode/bootstrap-datepicker/issues/288 but not working for me.

**Comment by hebbet** [comment]
what version of the datepicker are you using? 

can you provide a jsfiddle example showing the problem?  You can use this [jsfiddle](http://jsfiddle.net/vh1oknf7/) as a base!

**Comment by pottabathini** [comment]
Sorry for delay, I am not able to jsfiddle as it is giving $ undefined error, I pasted same code for your reference @ http://pastebin.com/BZRYFhEY please copy code and paste in .html file and run.

run that file you can see date highlight. but when you uncomment out two lines then you won't get highlight of date.

**Comment by pottabathini** [comment]
https://github.com/eternicode/bootstrap-datepicker/labels/awaiting-feedback

**Comment by hebbet** [comment]
it looks you are using a very old version of datepicker. try updating.

**Comment by hebbet** [comment]
closed, as no further reply.

**Comment by kjdion84** [comment]
`$.fn.datetimepicker.defaults.format = 'YYYY-MM-DD HH:mm:ss';`
