### ISSUE TITLE
autoclose option not working in IE7

### ISSUE THREAD

**Issue by omgaz** [eternicode/bootstrap-datepicker#137]
After choosing a date form the datepicker the popup does not autoclose.

As in the following example:

```javascript
$('#datepicker').datepicker({
  'hide':true,
  'autoclose': true
});
```

**Comment by acrobat** [comment]
I justed checked with IE7 on the sandbox page and autoclose works with the input field, a possible error could be like @richardthombs said that the element is not bound to a input field!
