### ISSUE TITLE
Clearing the date should reset to defaultViewDate

### ISSUE THREAD

**Issue by lode** [eternicode/bootstrap-datepicker#1370]
When clearing the date (via the `clearDates` or `update` methods) the input field is emptied, the date is deselected in the datepicker, *but*, the datepicker still shows the month of the old date. I would expect that would jump back to today (or the `defaultViewDate`).

See for a demo: http://jsfiddle.net/u67d8c50/

I can imagine that either `clearDates` or `update` is changed to make this happen. Or that there is an extra argument for those methods which resets the default view. Or maybe even a property like `resetToDefaultView`?

I'm unclear if this has something to do with https://github.com/eternicode/bootstrap-datepicker/issues/575. Although as seen in the fiddle, both methods have the same problem.

**Comment by dbackowski** [comment]
I have exactly same problem.

**Comment by hebbet** [comment]
PR #1380 was merged. closing.
