### ISSUE TITLE
Calendar not read by NVDA when navigating via keyboard

### ISSUE THREAD

**Issue by andrewleith** [eternicode/bootstrap-datepicker#1378]
When trying to access the calendar via keyboard with NVDA all it says is "blank" every time i press an arrow key.  With Jaws, it started actually changing focus to adjacent form fields.

Is there any intention to make this work? 

I tried navigating through the calendar with my keyboard with the following screen reader / browser configurations (sorry these are so old - its what I happen to have here at work):

* NVDA 2014.4 + IE9
* NVDA 2015.1 + IE9
* NVDA 2014.4 + FF 35
* NVDA 2015.1 + FF 35
* JAWS 14 + IE9
* JAWS 14 + FF35

**Comment by Azaret** [comment]
Correct me if I'm wrong, but it has to do with the lack of ARIA support right ?
If yes this is a duplicate of #811.

**Comment by andrewleith** [comment]
Yes, I believe an implementation using ARIA tags would solve this.  Closing as a duplicate.

**Comment by kgsosa** [comment]
I'm struggling to resolve this issue as well in my project; was there any solution to this issue?
