### ISSUE TITLE
Datepicker and placeholder

### ISSUE THREAD

**Issue by jask05** [eternicode/bootstrap-datepicker#1386]
Hi,
First, thanks for your work :)

I have a problem with an input placeholder and the datepicker. 

I've put an input placeholder but when I select a date and later I refresh the website the placeholder doesn't appears. 
It shows up the date that I've selected before refresh the website and I can't force to show the placeholder content.
Are there any option by which I can use input placeholder as default instead of the value date when I refresh the website?
Thanks

**Comment by hebbet** [comment]
can you provide a jsfiddle, that shows the bug?

**Comment by jask05** [comment]
I've tried with jsfiddle but datapiker didn't work :S 

You can see here: http://3capas.com/tpo/index.php?res=estandar

Last input, called: "FECHA APROX. DE LA OBRA". 

If you select a date and then you refresh the website, the placeholder doesn't appear.

Thanks

**Comment by hebbet** [comment]
i can't select a date. looks like a z-index error. 

Also you are using an old version of datepicker.

i use the datepicker in many of my projects with placeholders and it it working fine.

**Comment by jask05** [comment]
How embarrassing!

I'm going to change the datepicker version. I can reproduce the issue in localhost but, as you told me, I'm going to update it.

Thanks for your time!
