### ISSUE TITLE
IE update breaks layout

### ISSUE THREAD

**Issue by jboelter** [eternicode/bootstrap-datepicker#1389]
It looks like the latest build of IE pushed to my machine has an issue rendering the rows of days (image below). The height does not appear to calculate correctly. CSS below fixes it.

This appears to fix the layout in IE (very limited testing):
```css
.datepicker table tr {
  height: auto;
}
```

![image](https://cloud.githubusercontent.com/assets/3619564/7420041/14c5acde-ef2e-11e4-8a4c-7da511013159.png)

![image](https://cloud.githubusercontent.com/assets/3619564/7420021/f37b00ba-ef2d-11e4-95e4-41333ddee386.png)

**Comment by Azaret** [comment]
Looks like an IE issue which has been fixed. Cannot reproduce in `11.0.9600.17843`.

**Comment by jboelter** [comment]
Agreed; also cannot reproduce in newer builds.
