### ISSUE TITLE
Datepicker + Mask = NaN/NaN/NaN

### ISSUE THREAD

**Issue by victorvasconcelosdeaquino** [eternicode/bootstrap-datepicker#1394]
Hi,

I'm using Datepicker with mask (jQuery Mask Plugin http://igorescobar.github.io/jQuery-Mask-Plugin/), to enter the date, automatically the content of the datepicker is changed to "NaN/NaN/NaN". This only happens in Firefox browser.

**Comment by hebbet** [comment]
can you provide a working example of that bug?

https://github.com/eternicode/bootstrap-datepicker/blob/master/CONTRIBUTING.md#issues

**Comment by hebbet** [comment]
closing old tickets, with no newer reply.
