### ISSUE TITLE
Datepicker orientation mix up - top = bottom and bottom = top

### ISSUE THREAD

**Issue by monkeylumps** [eternicode/bootstrap-datepicker#1406]
I tried to set the orientation of my datepick so that it always goes above the field like so - 

$('.dateInput').datepicker({
            language: "en-GB",
            orientation: "top auto"
        });

This did not work, the datepicker would always show up on the bottom until I changed the code to this -

$('.dateInput').datepicker({
            language: "en-GB",
            orientation: "bottom auto"
        });

**Comment by Lautac** [comment]
I have the same behaviour, I put "bottom auto" in the orientation option but it goes always to top.
$('#datepicker').datepicker({ 
            format: 'dd/mm/yyyy',
            autoclose: true,
            language: 'fr',
            orientation: 'bottom auto',
            todayBtn: 'linked',
            todayHighlight: true
        });

**Comment by dhalai** [comment]
+ 1

**Comment by robertlagrant** [comment]
OH! Wow, okay. Problem "solved" :)

**Comment by elartix** [comment]
I have the same problem.

![image](https://cloud.githubusercontent.com/assets/1899626/8113884/b399f420-1079-11e5-90ef-a7e081a2bf3f.png)

bootstrap 3.x inline form

```javascript
$('.input-daterange').datepicker({
    format: 'dd.mm.yyyy',
    language: 'ru',
    autoclose: true,
    startDate: new Date(),
    setDate: new Date(),
    todayHighlight: true,
    orientation: "bottom auto"
});
```
with orientation: "top auto" same issue

**Comment by Azaret** [comment]
Actually `top` does open the picker at the bottom and `bottom` at the top.
Not sure it was intended, but we can agree this is confusing.
