### ISSUE TITLE
immediateUpdates option does not seem to work

### ISSUE THREAD

**Issue by bensinclair** [eternicode/bootstrap-datepicker#1407]
The `immediateUpdates` option does not seem to work. Have I misunderstood something?

Here's a demo: https://jsfiddle.net/wbLunk0j/

**Comment by Azaret** [comment]
Looks fixed in 1.5

**Comment by Azaret** [comment]
Actually this is a 1.5 feature, the JS you linked is 1.4.

**Comment by bensinclair** [comment]
Thanks mate! I thought I was going crazy!

+1 to showing stable and not dev docs :) Or at least put a comment in about what version is required for a specific feature.
