### ISSUE TITLE
'changeDate' event seems a bit inconsistent

### ISSUE THREAD

**Issue by bensinclair** [eternicode/bootstrap-datepicker#1408]
When you click the 'Clear' button it triggers the 'changeDate' event. 

On the very first 'keyup' within the date input the 'changeDate' event is triggered. But not on the second 'keyup' and beyond. 

And if you manually select the text in the date input and press your delete key to clear the text, the event is not triggered at all. 

Would it be more consistent if 'changeDate' triggered on each 'keyup' and when the input is cleared manually?

An example: https://jsfiddle.net/dh4ea05q/2/

**Comment by Azaret** [comment]
After a bit of test the `changeDate` event looks consistent to me.
`changeDate` is called whenever the date is changed, when you start typing a date the date is not necessarily changed.
When you clear all the text, the event `clearDate` is called in place of `changeDate` which make sense.
Give it a try : https://jsfiddle.net/dh4ea05q/10/

If you want a trigger on each `keyup`, you should use `keyup`.

**Comment by bensinclair** [comment]
Wow not sure how I missed that! Thank you so much :)
