### ISSUE TITLE
Add title to Datepicker

### ISSUE THREAD

**Issue by kingharrison** [eternicode/bootstrap-datepicker#1410]
Is there a way to add a textline title to the top of the picker?

**Comment by Azaret** [comment]
Something like ?
![image](https://cloud.githubusercontent.com/assets/1201743/8232681/e0cfcfca-15d1-11e5-8618-8b843c43a776.png)

**Comment by kingharrison** [comment]
Yes! 

King Harrison IV 
Executive Vice President
king4@k3s.com
Linkedin Profile
877.725.1305 ext: 504
www.k3s.com

On June 18, 2015 at 9:51:48 AM, Gregoire D. (notifications@github.com) wrote:

Something like ?

**Comment by Azaret** [comment]
There you go.
I might be shipped with 1.5 if @acrobat or @hebbet wander here.

**Comment by hebbet** [comment]
@Azaret feel free to make a PR ;-)

**Comment by Azaret** [comment]
Hehe got you :D

**Comment by acrobat** [comment]
Fixed in #1438
