### ISSUE TITLE
List of bootstrap components used?

### ISSUE THREAD

**Issue by nviror** [eternicode/bootstrap-datepicker#1423]
I customized my bootstrap file (http://getbootstrap.com/customize/) to make sure I'm not loading unnecessary components on my web page. Please let me know the list of components  "bootstrap-datepicker" is using from bootstrap.

**Comment by acrobat** [comment]
The datepicker is named "bootstrap" but it doesn't require bootstrap, as we compile the datepicker style with all the build variables pre-defined in [the build file](https://github.com/eternicode/bootstrap-datepicker/blob/master/build/build3.less). You can compile the less files yourself but then you just should provide bootstrap-variables.less or define them yourself!

I hope it's clear how we compile our style
