### ISSUE TITLE
`showMode` should use jQuery's `show` method

### ISSUE THREAD

**Issue by milotoor** [eternicode/bootstrap-datepicker#1424]
Lines 1425-1429, within the `showMode` method, look like this:

```javascript
this.picker
  .children('div')
  .hide()
  .filter('.datepicker-' + DPGlobal.modes[this.viewMode].clsName)
    .css('display', 'block');
```

This is making the implicit assumption that jQuery's `hide` method is just changing the `display` property of the selected elements. If you're going to use `hide` to hide the divs, why not use `show` to show them? 

This isn't merely pedantic. I'm raising this issue because it legitimately caused me trouble recently. I had overwritten the `$.fn.hide` and `$.fn.show` methods to add and remove (respectively) a Bootstrap class, `.hidden`. Overwriting library methods might be a questionable practice, but it was a working hack until I incorporated the datepicker. My suggestion is to change the code to

```javascript
this.picker
  .children('div')
  .hide()
  .filter('.datepicker-' + DPGlobal.modes[this.viewMode].clsName)
    .show();
```

That will work regardless of the implementation of `$.hide` and `$.show`, provided that they undo each other.

**Comment by hebbet** [comment]
feel free to mage a pull request.

**Comment by milotoor** [comment]
Shall do. Thanks for the rapid response!

**Comment by milotoor** [comment]
For the record I would tag this as a bug, not a feature request. Don't you think?

**Comment by hebbet** [comment]
@milotoor seleted the wrong label ;)

**Comment by milotoor** [comment]
Pull request: #1427. Please let me know if there are any changes you would like! I'm not very familiar with qUnit, but tried my best to follow conventions.

**Comment by milotoor** [comment]
Incidentally, two tests were failing on my local machine that don't appear to be failing in the CI build. I'll look into that.
