### ISSUE TITLE
border-radius in less

### ISSUE THREAD

**Issue by BARTlab** [eternicode/bootstrap-datepicker#1429]
pls, replace 
```border-radius: 4px;```
to
```border-radius: @border-radius-base;```

**Comment by hebbet** [comment]
feel free to make a PR.

**Comment by Azaret** [comment]
I felt free, that said, I think that some day the LESS files would need some cleaning, naming convention are different from one file to another.

**Comment by acrobat** [comment]
Fixed in #1435
