### ISSUE TITLE
maxViewMode doesn't work

### ISSUE THREAD

**Issue by lucassp** [eternicode/bootstrap-datepicker#1432]
Hi,

I'm trying lock the datepicker to dates only using maxViewMode but it doesn't work. I'm still able to click the top label and the datepicker switches to months and years.

**Comment by Azaret** [comment]
I believe it has been fixed in the next release #1294.

**Comment by lucassp** [comment]
Thanks @Azaret

**Comment by Sandeeprao69** [comment]
Hey not working for me as well, i am on 1.6.4 which is latest version.

I was trying to disable year using maxViewMode=0;

**Comment by Azaret** [comment]
It's working fine on 1.6.4 as far as I can tell.  
You can test it on [the demo page](https://uxsolutions.github.io/bootstrap-datepicker).
