### ISSUE TITLE
Invalid XHTML? SyntaxError: An invalid or illegal string was specified

### ISSUE THREAD

**Issue by calimeroteknik** [eternicode/bootstrap-datepicker#1434]
I think that this issue finds its root in the usage of innerHTML (instead of DOM manipulation with addChild and so) without adding the / at the end of auto-closing tags or ensuring every attribute has a value.

I serve my sites with the header: `Content-Type: application/xhtml+xml` in order to make the web browser point out syntax errors in the HTML.

Then, the line `$('#mycalendar').datepicker();` raises this in the browser console:
`Undefined entity` (in unknown)
`SyntaxError: An invalid or illegal string was specified` (in jquery-2.1.1.js)

So it looks probable that the generated code is not valid XML (needs a / at the end of auto-closing tags and such).
Maybe `Undefined entity` refers to `&something;`.

**Comment by Azaret** [comment]
There is actually no issue here since in HTML5 there is no `/`at the end of tags, as wrote in [the HTML5 documentation](http://dev.w3.org/html5/spec-author-view/syntax.html#syntax-start-tag).

I guess we can add some support for XHTML 1.x.

Now the fact are  
that XHTML 1.x is getting old, and all browser support HTML5 syntaxe.
that XHMTL 2.0 development have been indefinitely suspended.
and that XHTML5 is based on HTML5 so it fall under HTML5 rules (so no `/`).

So to be honest, I don't see the value of adding this support, nor in fact making website in XHTML 1.x nowadays.

**Comment by calimeroteknik** [comment]
Thank you for the detailed reply.
I'm actually writing HTML5, but to enforce correct syntax on the web developers (including myself), the only way I found is to serve the page with `application/xhtml+xml` in the HTTP headers.

This makes the browser puke an error if the document is not a proper XML tree, so we could say I'm writing XHTML5 code.
It's way stricter than the HTML5 standard, for which this is a perfectly valid document (ew):
`<!DOCTYPE html>`
`<head> <title>title</title>`
`<p>text`
`</html>`

But nobody wants to have to work with that kind of crufty code; I think we can agree that just passing the HTML5 standard is asking for trouble.
Enforcing that the document be an XML tree is not a bad way to ensure that things stay tidy.

JQuery's generated HTML strings are also valid XML; I had no trouble with any component of bootstrap so far, except datepicker. It would be a cool addition, I think. :)

**Comment by Azaret** [comment]
Ok, after checking the code there is self-closing tag anyway.
Now I wanna debug this issue, could you explain me how do you proceed to get your error ?

**Comment by calimeroteknik** [comment]
I put the header `Content-Type: application/xhtml+xml`, which can be simply done in php for instance by inserting this at the top of the page:
`<?php header('Content-Type: application/xhtml+xml'); ?>`

I think it might be an HTML entity, due to the error message in the console:
`Undefined entity (in unknown)`

There was no obvious way to get the code generated by the JS, though, since it's inserted via innerHTML.

**Comment by Azaret** [comment]
if no JS is executed there is no reason the issue is raised by the datepicker.

When I change the mime Chrome will just display the Xml without any error, nor executing any JS.
That's why I was asking.

**Comment by calimeroteknik** [comment]
The error disappears when I remove `$('#mycalendar').datepicker();` from the script in the page.
It seems that the function datepicker() tries to insert something that doesn't pass XML syntax as innerHTML.

**Comment by Azaret** [comment]
There is only `&#171;` and `&#187;` in the code, which by the way should be gone in 1.5.
It's hard to lookup for this since I can't perform what you're doing.

**Comment by calimeroteknik** [comment]
I updated, and the problem is fixed. I'm pretty sure I made a mistake when fetching datepicker initially and didn't have the last version.
Thanks very much!
