### ISSUE TITLE
Daterange. Disable automatic setting of other empty date field?

### ISSUE THREAD

**Issue by johanbaaij** [eternicode/bootstrap-datepicker#1454]
I'm using two datepickers that can be used to set a range, this works great. The user can also submit just a start or end date by leaving one field empty. 

Currently a daterange picker always sets another empty field to the same value the user just entered. Is there a way to disable this? Would there be interest in an option to disable this? I could try to make a pull request.

cheers

**Comment by coreymaher** [comment]
+1

I'd love this functionality as well.

**Comment by Wirone** [comment]
+1

We want to make filters for view and ranges would be optional, so automatically setting other field in range forces user to clear this field.

**Comment by MartijnDwars** [comment]
+1

Had this issues a couple of weeks ago and bumped into it again today.

**Comment by steffendietz** [comment]
Hi,

could some of you who had this issue review my PR and confirm that it works and meets the/our requirements?

Thanks a lot!

**Comment by nwself** [comment]
@steffendietz This works for me except that if I set the "to" date to be before the "from" date, both the "to" and "from" dates are changed. Not sure what everyone else expected but I'd prefer the "from" date to be cleared. (This is possibly out of scope for this issue.)

**Comment by steffendietz** [comment]
@nwself I think you are right. That would be a bit out of scope.
This issue here is only concerned about "not correcting" initially empty fields.
"Clearing" instead of "correcting" the fields is another (preferably configurable) change in behavior and should be handled in its own issue.

Thanks for testing my PR.

**Comment by sylbal** [comment]
+1, any plan for merging this PR ?
