### ISSUE TITLE
Date Range: Set second date picker one day later

### ISSUE THREAD

**Issue by juliomac** [eternicode/bootstrap-datepicker#1455]
Date Range could be quite useful for Booking applications. However , start date it is wired to select end date the same day. For booking a Hotel, for instance, itv would be nice to have more control over the minimum range (https://github.com/eternicode/bootstrap-datepicker/issues/970).

Current version seems not allow much control over both of date picker inputs (https://github.com/eternicode/bootstrap-datepicker/issues/1319), specially on setting the second date after the first picker input.

This has been discussed here: https://github.com/eternicode/bootstrap-datepicker/issues/708.

I guess the solution could be implement if it is added some variable like ```+ MinRange```, controlled by options, on the lines:
```                 new_date = dp.getUTCDate() + MinRange ```

Does that make any sense?

**Comment by lologhi** [comment]
I've something like that, my first datepicker is `.from`, the second is `.to`, and this is working : 

```
$('.input-daterange input.from').each(function (){
    $(this).on('changeDate', function(e) {
        var toDatepicker = $(this).parents('.input-daterange').find('.datepicker.to');
        toDatepicker.datepicker('update', moment($(this).datepicker('getDate')).add(1, 'week').toDate());
    });
});
```

**Comment by juliomac** [comment]
Dear lologhi, Thanks for your solution! I used it as the basis to write my own solution to work with Meteor. It may not be as elegant, but that was how I was able to get it working.

I added ```onchange="CheckOutAddOne" on the HTML input.```. Then included the function:

     CheckOutAddOne = function(){
        CheckIn = $('#CheckIn').datepicker('getDate');
        CheckOut = moment(CheckIn).add(1, 'day').toDate();
        $('#CheckOut').datepicker('update', CheckOut);
    }

It worked like

**Comment by lologhi** [comment]
Cool :v: 
You can close the issue if you're good :hammer:

**Comment by fsluijs** [comment]
Hi guys, I found this to be the best solution for me

`jQuery("#datepicker-start").datepicker().on("changeDate", function(e){
	var toDate = new Date(jQuery('#datepicker-end').datepicker('getDate'));
	toDate.setDate(toDate.getDate() + 7); // add one week
	jQuery('#datepicker-end').datepicker('setDate', toDate);
});`
