### ISSUE TITLE
Documentation: datepicker3.css vs datepicker.css vs datepicker.standalone.css

### ISSUE THREAD

**Issue by alvarotrigo** [eternicode/bootstrap-datepicker#1459]
It is not clear in the docs the difference between the different css files:

- datepicker3.css 
- datepicker.css 
- datepicker.standalone.css

**Comment by hebbet** [comment]
> datepicker3.css

for Bootstrap 3


> datepicker.css

for bootstrap 2 (legacy)

> datepicker.standalone.css

without bootstrap

**Comment by alvarotrigo** [comment]
That's what I guessed, but it should be pointed out in the documentation. Make things easier.

**Comment by AndorLundgren** [comment]
Also, it would be good to tell people that datepicker.css contains outdated css for gradient
(background-image: linear-gradient(top, #fdd49a, #fdf59a);)
It could cause problems with other libraries like Autoprefixer not able to create .map files.

**Comment by fmonts** [comment]
And what is the difference between 
bootstrap-datepicker.standalone.css
and
bootstrap-datepicker3.standalone.css
?
