### ISSUE TITLE
Undefined NaN (01-Jul-2012)

### ISSUE THREAD

**Issue by tysonnero** [eternicode/bootstrap-datepicker#148]
If I plug in a date such as 01-Jul-2012 into the date picker, the calendar reads "undefined NAN" and has no values. The value of the textbox reads "NaN/NaN/NaN". The page eventually become unresponsive and must refresh.

I tested this use case with the datepicker on http://www.eyecon.ro/bootstrap-datepicker/, and the same behavior does not happen but rather sets the default date.

**Comment by acrobat** [comment]
Closing this issues as I can't reproduce it anymore with the latest release and master
