### ISSUE TITLE
Incorrect 'auto' orientation

### ISSUE THREAD

**Issue by meetraz** [eternicode/bootstrap-datepicker#1480]
I have an application where the date field is located near the top of the page.  When I click on the field, the date picker is appearing on the top, so half of it is off the page and not visible.  I tried to add data-date-orientation="bottom" to the input attributes, but it's had no effect.   Is there a way to fix this?

**Comment by tomvo** [comment]
I have the same problem and not really have a solution. When I use `orientation: 'bottom right'` (or all the other combinations) it seems only to adjust the horizontal position, not the vertical one.

**Comment by tomvo** [comment]
oh jeez, I just figured it out, see this one: https://github.com/eternicode/bootstrap-datepicker/issues/1406
It's just mixed-up.

**Comment by hebbet** [comment]
fixed on master with f08ad04
