### ISSUE TITLE
DOCUMENTATION: Add clearDates() to list of methods on website

### ISSUE THREAD

**Issue by notmessenger** [eternicode/bootstrap-datepicker#1486]
I have found and am using the clearDates() method at https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L575 but it is not listed at http://bootstrap-datepicker.readthedocs.org/en/release/methods.html

Is this by chance a private method that is not intended for use and I should not be?

**Comment by acrobat** [comment]
Closing this issue as the docs were added! Thanks for reporting!

http://bootstrap-datepicker.readthedocs.org/en/v1.5.1/methods.html#cleardates
