### ISSUE TITLE
Release 1.5.0 - When?

### ISSUE THREAD

**Issue by HNygard** [eternicode/bootstrap-datepicker#1497]
When will 1.5.0 come out? Ref. #1294 . Seems to be a lot of changes in master.

**Comment by acrobat** [comment]
I wil try to make some time to check which issues we need to be resolve to have a stable release without any BC breaks.

One thing that still needs to be fixed is the placement bug (top = bottom and bottom = top). I will keep you updated here on the progress! 

/cc @hebbet if you also have some time to check the current state of the 1.5 release?

**Comment by hebbet** [comment]
@acrobat I will tried to get it done in maybe 1-2 weeks, but no promise :-)

**Comment by acrobat** [comment]
Yeah I currently have some troubles with my internet connection at home, hopefully get it sorted out soon. Then I'm going to spend some time in the weekends to get this release back on track!

**Comment by tfr** [comment]
Any ideas if my issue (https://github.com/eternicode/bootstrap-datepicker/issues/1496) might be fixed with 1.5.0 ?

**Comment by acrobat** [comment]
@tfr We will try to get it in 1.5, if you have the time to debug the issue further and maybe propose a fix, that would make it easier to get it in 1.5!

**Comment by tfr** [comment]
Hi,

I can try, but I'm more of a backend PHP guy and JS isn't among my strongest suits. However, I'll try to set up a site that does not require login and reproduces this situation.

**Comment by tfr** [comment]
Done: http://datepickerbug.codelab.solutions

**Comment by acrobat** [comment]
[1.5.0](https://github.com/eternicode/bootstrap-datepicker/releases/tag/v1.5.0) is released so closing this issue!
