### ISSUE TITLE
changeDate is triggered on initialization

### ISSUE THREAD

**Issue by himdel** [eternicode/bootstrap-datepicker#1512]
When you initialize datepicker and the input already contains a date value, `changeDate` event is triggered. IMHO this is wrong because the date has not actually changed in that case. 

http://jsfiddle.net/hous9y5L/6/

**Comment by vsn4ik** [comment]
Also triggered `change` event. I am also looking forward to fix it.

**Comment by somazx** [comment]
Also running into this as a problem when trying to bind, for example, an ajax event to changeDate.

This looks to be the result of changes introduced in [v1.30](https://github.com/eternicode/bootstrap-datepicker/blob/master/CHANGELOG.md#130)

> changeDate event is triggered when setDate is called.

**Comment by blag001** [comment]
It's ok for `changeDate`, but the vanilla-js `change` is still triggered on initialization...
( like said on https://github.com/eternicode/bootstrap-datepicker/issues/1561 )

Someone find a workaround for it ?
Seem this [bootstrap-datepicker.js#L793](https://github.com/eternicode/bootstrap-datepicker/blob/master/dist/js/bootstrap-datepicker.js#L793) is used for not firing the `changeDate` if there is no change, why not using it for `change` ?
