### ISSUE TITLE
Issue with calendar appearing off top screen

### ISSUE THREAD

**Issue by mikeerickson** [eternicode/bootstrap-datepicker#1517]
I have created a very simple demo app trying to get the bootstrap-datepicker to work.   

When I click in the area that has the datepicker, the calendar appears off top part of screen.  

The only way it looks right is if I have a lot of stuff above it to force the control down on page (and then it barely makes it).   From what I am observing, it always opens on top of input field (never below which I would think it should do).

Other than the visual issue, everything else works as expected.

Here the files I am including (same issue occurs when i am not using the parallel time popup)

<pre>

    <script src="lib/jquery.timepicker.min.js"></script>
    <link href="lib/jquery.timepicker.css" rel="stylesheet">

    <script src="lib/bootstrap-datepicker.js"></script>
    <link href="lib/bootstrap-datepicker3.css" rel="stylesheet">

</pre>

**Comment by hebbet** [comment]
that is a known bug and might be fixed on master.

//cc @acrobat

**Comment by mikeerickson** [comment]
@hebbet awesome, thx I will have a look and see what happens

**Comment by philxtian** [comment]
@hebbet @acrobat 

Hi! I'm having the same issue. I downloaded the latest version but the calendar still showing off the screen.

But when I open my app in tablet and mobile view, the calendar shows up in the right position.

Is there a latest fix on this? Thanks. :-)

![date-picker](https://cloud.githubusercontent.com/assets/4645586/9308456/ec39a740-450c-11e5-99f4-c2e44dfa5c15.jpg)

**Comment by RickStrahl** [comment]
Running into the same thing. It looks like the datepicker is not respecting the margins - the top offset is off exactly by the top margin I believe.
