### ISSUE TITLE
Switching language on demand

### ISSUE THREAD

**Issue by JirkaKrivanek** [eternicode/bootstrap-datepicker#1522]
I added this method to allow the switching of the language on demand (instead only at the creation time).

Feel free to add it to you code (and possibly fix, if I am missing some issues with it)...

        setLanguage: function(lang) {
            if (!dates[lang]) {
                lang = lang.split('-')[0];
                if (!dates[lang])
                    lang = defaults.language;
            }
            this.o.language = lang;
            this.fill();
        },

**Comment by hebbet** [comment]
duplicate of #362. closing
