### ISSUE TITLE
Datepicker orientation failer

### ISSUE THREAD

**Issue by rammi987** [eternicode/bootstrap-datepicker#1529]
Hello, nice picker
small issue with it, when i click on the input field to show up the calender, the orientation fail.

The calender show on the top of the input witch is fair enuge but the poniting arrow points up away from the input field, do i try to force it to be "bottom lef", issues will be the pointing arrow will point down agian away from the field?

<code>
export function init(scope) {
	$(scope).datepicker({
		format: 'dd/mm-yyyy',
		todayHighlight: true,
		todayBtn: "linked",
		 orientation: "top left",
	});
}
</code>

<code>
input.datepicker(type="text")
</code>

**Comment by jcdavison** [comment]
Hey @rammi987 did you find a solution to this? I'm having the same issue.

https://www.dropbox.com/s/418fyc1imcy67qi/Screenshot%202015-08-25%2012.09.40.png?dl=0

**Comment by MartijnR** [comment]
same issue

**Comment by jcdavison** [comment]
I actually noticed that using the rails gem associated with adding this js to the asset pipeline was having issues, I pulled the js manually into the app I was working and the situation resolved itself.  The likely culprit, in my case, was https://github.com/Nerian/bootstrap-datepicker-rails not the source js itself. probably working off and old version of the js.

**Comment by MartijnR** [comment]
Thanks @jcdavison! Turns out I was also using an old js version.

**Comment by rammi987** [comment]
i self just downgrate bootestrap version and it works agian

**Comment by acrobat** [comment]
So whith which version of the datepicker do you guys have this bug? master(1.5) or a specific lower version?

**Comment by MartijnR** [comment]
I use 1.4.0 (the latest version published on npm), but in my case it turned out to not be a bug.

**Comment by hebbet** [comment]
fixed on master with f08ad04.
