### ISSUE TITLE
Tell the related data API to the options

### ISSUE THREAD

**Issue by victorleal** [eternicode/bootstrap-datepicker#1534]
I'm trying to use the data API to set some options to my datepicker and the docs does not provide the attribute related to an option.

I could collab on this thing, if needed.

**Comment by HuBandiT** [comment]
Please elaborate a bit on what you mean exactly.

The very first section of the documentation at http://bootstrap-datepicker.readthedocs.org/en/stable/options.html specifies the rules for the HTML5 `data-` attribute names to use to specify options in element markup.

Is this the information you are looking for?

**Comment by victorleal** [comment]
I found a way to do it with Angular JS.

But your link provides the stuff I was looking for.
