### ISSUE TITLE
What are the 4 different versions of the CSS file for?

### ISSUE THREAD

**Issue by stringsonfire** [eternicode/bootstrap-datepicker#1548]
I couldn't find an explanation in the documentation, so it's unclear what needs to be included. Maybe this could be added?

    bootstrap-datepicker.css
    bootstrap-datepicker.standalone.css
    bootstrap-datepicker3.css
    bootstrap-datepicker3.standalone.css

Thanks

**Comment by acrobat** [comment]
the 2 `bootstrap-datepicker*.css` files are used in combination with twitter bootstrap styles. The 2 ` *..standalone.css` files are used as standalone css files they are in a twitter bootstrap style, but without any dependencies on twitter bootstrap (we compiled the full files)

**Comment by stringsonfire** [comment]
Is `bootstrap-datepicker.css` for Bootstrap 2.X then?

**Comment by acrobat** [comment]
Yes indeed, the css files without a version number are twbs 2.X the others are twbs 3.X

**Comment by stringsonfire** [comment]
Got it, thanks

**Comment by hebbet** [comment]
> Is bootstrap-datepicker.css for Bootstrap 2.X then?

Currently yes. We might change it with 2.0

**Comment by nelson6e65** [comment]
Thanks for the explanation.

**Comment by acrobat** [comment]
Currently this is the setup but that will change in 2.0 (we can't change it now as it would break backwards compatibility) 

We have [a section in the docs](https://bootstrap-datepicker.readthedocs.org/en/latest/#stylesheets) about the different stylesheets!
