### ISSUE TITLE
update() method doesn't apply to all datepickers

### ISSUE THREAD

**Issue by Dimas-sc** [eternicode/bootstrap-datepicker#1559]
I've updated the Datepicker to the last version and now when I do:

$('#modal-planificacio .input-group.date').datepicker('update');

It only updates the datepicker of the first element (i've two datepickers). Before it updates all of them. Now this works, but isn't a good solution:

$('#modal-planificacio .input-group.date').first().datepicker('update');
$('#modal-planificacio .input-group.date').last().datepicker('update');

**Comment by acrobat** [comment]
Possibly related to #1572

**Comment by acrobat** [comment]
PR #1586 fixed this issue, please test against the latest master!
