### ISSUE TITLE
Change event triggered on initialization

### ISSUE THREAD

**Issue by sladkoff** [eternicode/bootstrap-datepicker#1561]
Hello,

EDIT: So I just found [#1512](https://github.com/eternicode/bootstrap-datepicker/issues/1512) for which this is almost a duplicate. That thread is about the ``changeDate`` event though, so I decided to post anyway. I'll let the contributors decide what to do with this issue.

I have a *suggestion* regarding the datepicker after upgrading from version 1.4 to 1.5.

I have noticed that the datepicker triggers a change event on the input at initialization.

This is a problem for us because we have change event listeners on all inputs of our form. Of course, we only want to handle user-made events. ~~We were able to work around it since all our datepickers have a special class, so that we now only listen for the plugin's ``changeDate`` event on those elements.~~ This does not really fix it, since the ``changeDate`` event is also triggered on init, but only when the original input already has a value assigned (see linked issue in EDIT on top).

I traced the event and found out that it's most likely related to [line 803](https://github.com/eternicode/bootstrap-datepicker/blob/master/dist/js/bootstrap-datepicker.js#L801) which was not there in v1.4. 

I'm not familiar with your codebase but as far as I understood, the plugins' internal ``update`` function is called when the datepicker is first initialized. 
This does not look like a bug but I think that the behavior could be optimized - it would be more intuitive and standardized to be able to listen for the common ``change`` event and I don't think it's good to trigger the ``change`` on init, since there was in fact no change.

Can anyone relate?

PS. I'll post a fiddle when I have the time, if necessary.

**Comment by GNaruhn** [comment]
Same Problem here...

I use the change() event to mark changed fields as 'dirty' and also to enable a disabled submit button.

**Comment by adambiggs** [comment]
I just ran into this problem as well... We listen to `change` events because we only initialize the datepicker plugin on desktop. On mobile we fall back to using native HTML5 datepickers.

The `change` event should have the same behaviour as native HTML5 datepicker fields. I.e. it should only be triggered when the user changes the field's value.

**Comment by denniscastro** [comment]
HI

I had the same problem until today

I solved it changing 

    if (String(oldDates) !== String(this.dates))
to 
    if (String(oldDates) != '' && (String(oldDates) !== String(this.dates)))

in bootstrap-datepicker/js/bootstrap-datepicker.js line 836
the first time oldDates is empty.
