### ISSUE TITLE
startDate doesn't work in other languages

### ISSUE THREAD

**Issue by gustavomanolo** [eternicode/bootstrap-datepicker#1562]
Hi, i've the following example, the start date doesn't work when i set the language to "es", i tried with "en" and this works fine, but not in other languages.

$('#sandbox-container input').datepicker({
    startDate: "09/07/2015",
    language: "es"
});

**Comment by acrobat** [comment]
Thanks for the report! This is an example to reproduce the problem, http://jsfiddle.net/vh1oknf7/76/. We will try to look at it soon!

**Comment by Azaret** [comment]
It does work actually, you're just looking at the wrong month...
The date format is localized, for spanish `09/07/2015` will be June the 9th.
You should set '07/09/2015' if you intend to select September the 7th.

**Comment by acrobat** [comment]
Oh yes, I forgot about the language specific dateformat. Thanks @Azaret for pointing that out!
