### ISSUE TITLE
update npm repository

### ISSUE THREAD

**Issue by lzyzsd** [eternicode/bootstrap-datepicker#1564]
please update the latest version to npm,  many thanks

**Comment by acrobat** [comment]
@lzyzsd The latest released version is available on npm!

>  acrobat published 6 months ago
> 1.4.0 is the latest release

**Comment by lzyzsd** [comment]
@acrobat sorry, do not check the release versions。 since 1.4.0 do not have main property in package.json, it can not be used with webpack, when will you release 1.5.0?

**Comment by acrobat** [comment]
I don't know when 1.5 will be released exactly, because we have a few critical bugs left and I have very limited time resources myself. But we will try to get it out as soon as possible. If the missing main property should be a blocking issue, I could port the fix and release 1.4.1 with the main property!

**Comment by lzyzsd** [comment]
@acrobat many thanks for your effort to this awesome lib, currently, I can do some config in webpack to bypass the problem.

**Comment by Ben52** [comment]
@acrobat Please do! Thanks.

**Comment by acrobat** [comment]
I've pushed 1.4.1 to npm with the main property in the package.json. So you guys can update the your datepicker!

**Comment by acrobat** [comment]
I've pushed 1.4.1 to npm with the main property in the package.json. So you guys can update the your datepicker!

/cc @lzyzsd , @Ben52

**Comment by lzyzsd** [comment]
@acrobat  many thanks

**Comment by stevepiercy** [comment]
I installed via `npm i eternicode/bootstrap-datepicker#d014a14f0 -D` where the hash is the latest.

But I cannot figure out how to get it to load. @lzyzsd @Ben52 what did you folks do to get webpack to load `bootstrap-datepicker`? Can you share your `webpack.config.js` and any other bits?

**Comment by Ben52** [comment]
@stevepiercy I use browserify.

**Comment by stevepiercy** [comment]
For others, in your app's entry point, say in main.js:

```javascript
require('bootstrap-datepicker');
// example configuration
$('#date_measured').datepicker({
    format: "yyyy-mm-dd",
    startDate: "-1y",
    endDate: "0d",
    todayBtn: "linked",
    autoclose: true,
    todayHighlight: true
});
```
