### ISSUE TITLE
daysOfWeekHighlighted not highlighting

### ISSUE THREAD

**Issue by mrcoulson** [eternicode/bootstrap-datepicker#1565]
Hello!  When I specify daysOfWeekHighlighted, I'm not seeing any highlighting of specified days.

    $("input#txtInspectionDate").datepicker({
            startDate: dateArray[0],
            endDate: dateArray[maxDateIndex],
            daysOfWeekDisabled: daysWeekend,
            datesDisabled: datesDisabled,
            daysOfWeekHighlighted: [3, 4]
        });

Anyone else having this trouble or am I alone?  Thanks!

**Comment by hebbet** [comment]
can you provide a jsfiddle?

**Comment by hebbet** [comment]
closing as no further reply. feel free to reopen.

**Comment by paico** [comment]
Hi guys,
I had this problem and the solution was to add this line before calling the datepicker:

`$(document).ready(function () {`

My code looks like this:

`<script>
    $(document).ready(function () {
        $('.datepicker1').datepicker({
            format: 'mm/d/yyyy',
            assumeNearbyYear: true,
            autoclose: 'true',
            startView: '',
            todayHighlight: true,
            calendarWeeks: true,
            daysOfWeekHighlighted: "1,2,3,4,5",
            startDate: '@schedlimitstart',
            endDate: '@schedlimitend'
        });

    });
</script>`

I found the solution in this link: http://forums.asp.net/post/6062481.aspx
