### ISSUE TITLE
Upon loading the bootstrap-datepicker library, I can no longer use the .modal functions in BS 2.3.2

### ISSUE THREAD

**Issue by WtheFourth** [eternicode/bootstrap-datepicker#1566]
```$(...).modal is not a function``` is shown in my console whenever I attempt anything to do with modals after loading ```bootstrap-datepicker.js``` version 1.4.0.

I am using Bootstrap 2.3.2.

---

Specifically, my workflow is this:

* Use ```$('#myModal').modal('show');``` to show modal
* Modal is shown -> ```bootstrap-datepicker.js``` is loaded
* Click button that fires ```$('#myModal').modal('hide');```
* Get error ```$(...).modal is not a function```

**Comment by hebbet** [comment]
why are you using bootstrap 2.3?

**Comment by WtheFourth** [comment]
The application is already in production and we don't have enough time in our current release cycle to upgrade to 3.3.5, although the version shouldn't necessarily matter as long as it is >2.0 per the documentation.
