### ISSUE TITLE
For some methods chain breaks on the first jQuery element

### ISSUE THREAD

**Issue by vsn4ik** [eternicode/bootstrap-datepicker#1572]
`$('input').datepicker('show')` if `$('input').length > 1` methods chain breaks on the first jQuery element.
For reproduce run `grunt screeshots` (see `docs/_screenshot/script/screenshot.js`) and see generated images.

It was created by 847ac88bee7709dcfd12927cd851cc339f1442dd
```js
...
if (internal_return !== undefined)
  return false;
...
```

Maybe delete `return this;` in `show`, `remove`, `hide`, and `update` methods or change to `return;`.

**Comment by acrobat** [comment]
I was looking into this issue but could not find the commit which caused this issue. So this will make it easier to fix, so thanks for the issue @vsn4ik!

**Comment by acrobat** [comment]
@vsn4ik Would this be a valid solution?

```
if (internal_return !== undefined)
	return internal_return;
```

Looks like to case you gave as an example is fixed that way, but i'm not sure if this change has anymore impact on other features. What do you think about this?

/cc @hebbet

**Comment by vsn4ik** [comment]
@acrobat not, this is part code of issue.

This issue was created
847ac88bee7709dcfd12927cd851cc339f1442dd and a75480979a353e344f774a0e4dab762bf748960e.

I think need revert a75480979a353e344f774a0e4dab762bf748960e or ...
1. Delete https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L1615-L1616
2. Change https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L1619
```js
var datepickerPlugin = function(option){
  ...
  if (this.length == 1 && internal_return !== undefined)
    return internal_return;
  ...
};
```

**Comment by acrobat** [comment]
@vsn4ik  Yes I understand that! But I would like to leave the feature of chainable methods, because it's quite handy.

But why should delete the lines on 1616 (point 1 in your description) aand not just replace them with a return of the internal_return itself?

**Comment by acrobat** [comment]
ping @vsn4ik

**Comment by vsn4ik** [comment]
Because the `this.each` function terminates.

My soluton:
1. Revert a75480979a353e344f774a0e4dab762bf748960e
2. Delete https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L1615-L1616
3. Change https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L1619-L1622 to
```js
if (internal_return !== undefined && this.length > 1)
  throw new Error('Using only allowed for the collection of a single element (' + option + ' function)');
else if (internal_return !== undefined)
  return internal_return;
else
  return this;
```

**Comment by vsn4ik** [comment]
Another solution (without revert) #1586.
