### ISSUE TITLE
PT, CS, PL, PT-BR, and SK missing format for locales

### ISSUE THREAD

**Issue by daamazing1** [eternicode/bootstrap-datepicker#1573]
Noticed that PT, CS, PL, PT-BR, and SK are missing locale format properties.

PT should be "dd/mm/yyyy"
PT-BR should be "dd/mm/yyyy"
CS should be "dd.mm.yyyy"
PL should be "dd.mm.yyyy"
SK should be "dd.mm.yyyy"

Thanks,

**Comment by acrobat** [comment]
Can you send a PR to fix the missing properties? Otherwise I will try to add them soon!

**Comment by acrobat** [comment]
Alright thanks @hebbet!

**Comment by hebbet** [comment]
PL already included dd.mm.yyyy
