### ISSUE TITLE
Language  and orientation option not working

### ISSUE THREAD

**Issue by mariaczi** [eternicode/bootstrap-datepicker#1578]
This is code:
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.0/js/bootstrap-datepicker.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#published_at').datepicker({
                language: "pl",
                orientation: "bottom auto",
                autoclose: true,
                todayHighlight: true
            })
        });
    </script>

Autoclose and todayHiglight are working,
but language and orientation not make any effect.

What can be the issue?

**Comment by acrobat** [comment]
That issue is possibly fixed in #1571. Can you test against the current master if you issue is solved?

**Comment by mariaczi** [comment]
I changed to:

```<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker.min.css" />```
 ```   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.min.css" />```

```<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#published_at').datepicker({
                language: "pl",
                orientation: "bottom",
                autoclose: true,
                todayHighlight: true
            })
        });
    </script>```

Still the same... wrong orientation (on top) and still english.

**Comment by hebbet** [comment]
can js provide a jsfiddle?

**Comment by mariaczi** [comment]
language is fixed.
I missed to attach locale file.

What you mean ?

**Comment by hebbet** [comment]
http://jsfiddle.net/

**Comment by mariaczi** [comment]
trying but it's not working there at all

http://jsfiddle.net/scgo6jy2/#&togetherjs=5rgJDgSAMT

**Comment by vsn4ik** [comment]
Reproduced on 1.4.1: http://jsbin.com/miqabesove/edit?html,output
Not reproduced on master: http://jsbin.com/miqabesove/edit?html,output

@mariaczi Thanks! I think you can close this issue.
