### ISSUE TITLE
Setting startDate after initialization

### ISSUE THREAD

**Issue by rept** [eternicode/bootstrap-datepicker#1585]
I have 2 inputs: a from and a to.

If the from is set to the 26th of august I want that date the be the startdate of the to input so the user can't select an invalid period.

For this I used this code:

    $('#absence_from').datepicker().on('changeDate', function(e) {
      return $('#absence_to').datepicker({
        startDate: e.date
      });
    });

However it's not working, what am I doing wrong?  Isn't it possible to change the startDate afterwards?

**Comment by jesperronn** [comment]
You write `e.date`. The event `e` has a `e.target`, which you can investigate.

Can you try to change it to something like:

    var $startField = $(e.target);
    var startdate = $startField.datepicker('getDate');

this should be a date. This date can be inserted with:

   $('#absence_to').datepicker('setStartDate', startdate);


I hope this can guide you in the correct direction. 

Please note that the issue tracker here is probably not the best place for implementation questions. You are probably better off at [Stackoverflow](http://stackoverflow.com/questions/tagged/twitter-bootstrap+datepicker) or similar.

**Comment by rept** [comment]
Ok thanks!
