### ISSUE TITLE
Gradient has outdated direction syntax. New syntax is like "to left" instead of "right"

### ISSUE THREAD

**Issue by KrunchMuffin** [eternicode/bootstrap-datepicker#1594]
I am using gulp-autoprefixer and it is giving me this warning. May want to update.

Relevant lines 131, 196, 248, 299, 371

**Comment by KrunchMuffin** [comment]
I was just looking at the actul lines and you guys are using TOP not RIGHT. So may be something wrong the module, but I think TOP is now TO TOP
http://www.w3.org/TR/css3-images/#linear-gradients

**Comment by hebbet** [comment]
> Relevant lines 131, 196, 248, 299, 371

of which file?

what version of Datepicker did you check? 

see also #1569

**Comment by KrunchMuffin** [comment]
Sorry, using 1.4.0, but just checked 1.4.1 and it is still `top`, needs to be `to bottom`
https://github.com/postcss/autoprefixer/issues/530

**Comment by hebbet** [comment]
cloasing as it is fixed in master.
