### ISSUE TITLE
datepicker do not respect tabindex

### ISSUE THREAD

**Issue by abstractindia** [eternicode/bootstrap-datepicker#1600]
I have several fields in my form. Every field is assigned tabindex. The datapicker is applied on 5th field and after that another field with tabindex 6. While filling the form I move to next field by pressing the tab. But after selecting the date, I press tab to move to the 6th field, it moves back to tabindex 1. 

Is there any option for respecting tabindex. If yes, what is it?

**Comment by acrobat** [comment]
It seems to work in [this example](http://jsfiddle.net/jeroenthora/vh1oknf7/91/), can you provide a jsfiddle which fails?

**Comment by abstractindia** [comment]
Thank you for your co-operation. 
Here is my pastebit http://pastebin.com/DdrYBKvj . Please check.

**Comment by abstractindia** [comment]
Any update?

**Comment by hebbet** [comment]
could you transfer your pastebin to a jsfiddle?

**Comment by abstractindia** [comment]
Sir, Its resolved. I just changed autoclose to false and its now working.
