### ISSUE TITLE
Bootstrap dropdown gets closed on date select

### ISSUE THREAD

**Issue by alvarotrigo** [eternicode/bootstrap-datepicker#1615]
[Reproduction online](http://jsfiddle.net/imac/jp9gr96z/1/)

Any way to prevent it?

**Comment by hebbet** [comment]
when dropdown is no longer in focus, it is closed. that is the normal behavior of bootstrap's dropdown. 

that might help you:
http://www.bootply.com/116350

**Comment by alvarotrigo** [comment]
I know that...
I was already preventing it like this:

```javascript
 $('#pepe').click(function (e) {
    e.preventDefault();
    e.stopPropagation();
});
```

But as the datepicker is relative to the `body` and not the dropdown, it still hiding everything.

That's why I'm asking. Maybe the datepicker returns some `event` I can stop propagating?

**Comment by castamir** [comment]
Solution:
```js
 $('.datepicker').on('hide.bs.dropdown', function (e) {
    return false;
});
```
