### ISSUE TITLE
Allow for correct positioning inside scrollable containers

### ISSUE THREAD

**Issue by thetimbanks** [eternicode/bootstrap-datepicker#1616]
I am experiencing a positioning issue when displaying the datepicker inside a container that is scrollable. The problem occurs because the `offset().top` changes when the container scroll position changes. In order to offset this change in `offeset().top` the `scrollTop` of the container needs to be added to the `top` position`.

Here is a fiddle where the problem is shown. The datepicker on the left uses the `body` as a container and everything works as expected. The datepicker on the right is in a scrollable container and doesn't display in the correct position.
http://jsfiddle.net/thetimbanks/L24bnfpv/

Here is a fiddle using my proposed change. The change checks the container and adds `scrollTop` if the `container !== 'body'`. I don't know for sure if I like that comparison, but it does seem to work. The proposed change is on line 696 of the javascript portion.
http://jsfiddle.net/thetimbanks/L24bnfpv/1/

I have also submitted a PR for this change and am happy to update it in any way.

**Comment by acrobat** [comment]
Fixed in #1617
