### ISSUE TITLE
Update calculation when nudging the datepicker due to going off screen when inside a container

### ISSUE THREAD

**Issue by thetimbanks** [eternicode/bootstrap-datepicker#1619]
When displaying the datepicker inside an element other than `body`, the nudging doesn't properly place the datepicker when it detects it went off the screen to the right. 

Here is a scenario where the datepicker is inside another container and on the right side of the container. As you can see the datepicker ends up way off to the right.

Broken: http://jsfiddle.net/thetimbanks/xefb8vf6/1/

After adjusting the math slightly to determine the correct position, you can see that it is now placed correctly.

Fixed: http://jsfiddle.net/thetimbanks/xefb8vf6/2/

The line that changed is where the `left` position gets updated after determining that the datepicker is off the screen. The line looks like:

`left = offset.left + width - calendarWidth;`

The problem exists because the container's offset (`appendOffset`) isn't being taken into account. Fortunately, the `left` variable has already done that calculation for us so you can just substitute `left` in for `offset.left` resulting in:

`left = left + width - calendarWidth;`

This makes sense since you already know where the left side of the input is (`left`), you are then adding the difference of the widths.

I have submitted a PR to update this line.

**Comment by acrobat** [comment]
Fixed in #1620
