### ISSUE TITLE
SetDate in the 'show' event of Bootstrap DateTimePicker

### ISSUE THREAD

**Issue by lokopinagar** [eternicode/bootstrap-datepicker#1621]
I want to set date in datetimepicker on show event. the dateVariable is set when someone select value from the bootstrap datepicker. Now if some again open the datepicker i want to auto select it on show event.

Or is their any other way to do this.

Please Note that Datepicker is on a div, which opens in a popup when someone click a button, not on a textbox or any other input type html.

$('.date-picker').datepicker({
                        setDate: new Date(),
                    }).on('show', function (e) {
                  //   setDate: dateVariable
                    });

**Comment by Azaret** [comment]
`$('.date-picker').datepicker('setDate', dateVariable);` should do the trick.
Here an exemple: https://jsfiddle.net/kde1vwgt/26/

**Comment by lokopinagar** [comment]
As i said the datepicker is on div not on button or any type of input type elements and it open in popup on button click so 'show' events does not even fire.

**Comment by Azaret** [comment]
You can use `$('.date-picker').datepicker('setDate', dateVariable);` anywhere.
The library you're using to open the popup most probably have some show event, you should call setDate inside it.

**Comment by lokopinagar** [comment]
Thank you
