### ISSUE TITLE
Datepicker title not centered when displaying calendar weeks

### ISSUE THREAD

**Issue by mologie** [eternicode/bootstrap-datepicker#1625]
Hello,

I found that in the current release candidate (1.5 RC1), with the following configuration, the title is not properly centered:

```js
$(document.forms.addScSollForm.sollDate).datepicker({
	calendarWeeks: true,
	todayHighlight: true,
	daysOfWeekDisabled: [0,2,3,4,5,6],
	title: "Select calendar week"
});
```

The reason appears to be that the generated title `th` element has a hardcoded colspan of 7 columns. However, when displaying calendar weeks, there are 8 columns.

A screenshot of the issue is attached.

![capture](https://cloud.githubusercontent.com/assets/597682/10559661/c3c84626-74f6-11e5-8511-73d9afbc17de.PNG)

**Comment by vsn4ik** [comment]
Fixed, but not closed...

/cc @acrobat, @hebbet.

**Comment by hebbet** [comment]
thanks ;-)
