### ISSUE TITLE
Enable one or more dates???

### ISSUE THREAD

**Issue by dzung1nguyen** [eternicode/bootstrap-datepicker#1632]
Hi Guys, 

I can set a enable date?

Eg:
 I disable all days: 0->6
But i want to enable date: 26/10/2015 => Monday (day of date: 1).

How to  setup that?
....

daysOfWeekDisabled: [0,1,2,3,4,5,6],

...

Please help me.
Thanks so much.

**Comment by Azaret** [comment]
I advise you to use [`beforeShowDay`](http://bootstrap-datepicker.readthedocs.org/en/stable/options.html#beforeshowday).
With something like this:
```js
$('#sandbox-container input').datepicker({
  beforeShowDay: function (date){
    if (date.getTime() === (new Date(2015, 9, 26)).getTime()) {
      return false;
    }
  }
});
```

**Comment by dzung1nguyen** [comment]
@Azaret  Thank man.
