### ISSUE TITLE
Reset the date in Embedded datepicker

### ISSUE THREAD

**Issue by laxman4434** [eternicode/bootstrap-datepicker#1634]
I want to reset the date in embedded date picker without using the clear button.

Instead, I want to clear the date on button click event.

Any help would be appreciated

**Comment by Azaret** [comment]
You should be able to do it with [`update`](http://bootstrap-datepicker.readthedocs.org/en/stable/methods.html#update):
```js
$('.datepicker').datepicker('update', '');
```

**Comment by laxman4434** [comment]
Thank you very much. That worked
