### ISSUE TITLE
datepicker closing bootstrap modal when the popup closes 

### ISSUE THREAD

**Issue by JasonColeyNZ** [eternicode/bootstrap-datepicker#1642]
To fix this issue I had to add 

    if (event == 'hide') then return;

See below...

     _trigger: function (event, altdate) {
             var date = altdate || this.dates.get(-1),
                 local_date = this._utc_to_local(date);

             if (event == 'hide') return;
             this.element.trigger({
                 type: event,
                 date: local_date,
                 dates: $.map(this.dates, this._utc_to_local),
                 format: $.proxy(function (ix, format) {
                     if (arguments.length === 0) {
                         ix = this.dates.length - 1;
                         format = this.o.format;
                     }
                     else if (typeof ix === 'string') {
                         format = ix;
                         ix = this.dates.length - 1;
                     }
                     format = format || this.o.format;
                     var date = this.dates.get(ix);
                     return DPGlobal.formatDate(date, format, this.o.language);
                 }, this)
             });
         },

**Comment by hebbet** [comment]
can you provide a jsfiddle?
