### ISSUE TITLE
 Not validating disabled date

### ISSUE THREAD

**Issue by eduavila** [eternicode/bootstrap-datepicker#1648]
How do I not allow user can put the inactive date. Today he does not let you select, but to put it manually does not do any validation that the date is disabled.

ex:
$('#sandbox-container input').datepicker({
    datesDisabled: ['10/06/2015', '10/21/2015']
});

![captura de tela 2015-10-29 as 13 30 30](https://cloud.githubusercontent.com/assets/1779843/10825143/7093928a-7e42-11e5-8939-b0663b7ff903.png)

**Comment by frederikprijck** [comment]
Which version of the datepicker are you using ?

Take a look at this jsfiddle, it works perfectly: http://jsfiddle.net/frederikprijck/L76a8vaL/

![Image](http://i.imgur.com/ntFSeZd.png)

**Comment by frederikprijck** [comment]
I'm interested in this aswell.

I think they are working on it, considering this commit: https://github.com/eternicode/bootstrap-datepicker/commit/4375a0d346449f57fff029fbd36c1d2c54135207

Any timeframe for when this will be released ?

**Comment by acrobat** [comment]
1.5.1 should be released soon! I don't have a specific time but should be out before christmas!

**Comment by emrass** [comment]
I'm afraid this issue does still exist - just checked it with both 1.5.1 and 1.6.0.
Potential duplicate: #1803
