### ISSUE TITLE
Datepicker comes open in wrong container when using on input-group

### ISSUE THREAD

**Issue by JarJak** [eternicode/bootstrap-datepicker#1652]
Works in sandbox:
https://eternicode.github.io/bootstrap-datepicker/?markup=component&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox

But here it doesn't:
http://jsfiddle.net/sc8uh1ej/

**Comment by Azaret** [comment]
Because the picker expect you to instance it on the input, `#datepicker` in your example, not `.datepicker`.

**Comment by acrobat** [comment]
Yes indeed what @Azaret said, see fixed example: http://jsfiddle.net/sc8uh1ej/1/

**Comment by JarJak** [comment]
But in sandbox it works! 
I want the datepicker to be opened also when user click on the icon. See:
http://jsfiddle.net/sc8uh1ej/2/

**Comment by Azaret** [comment]
the sandbox explicitly instantiate on the input:
```js
$('#sandbox-container input').datepicker({
...
});
```

If you want to bind your icon to open the picker, you should do it apart: http://jsfiddle.net/sc8uh1ej/3/
```js
$(document).ready(function(){
    $('.datepicker input').datepicker({
        //..
    });
    $('.datepicker .input-group-addon').on('click', function () {
        $(this).closest('.datepicker').find('input').datepicker('show');
    });
});
```

**Comment by JarJak** [comment]
So the sandbox is wrong? It generates code:
```js
$('#sandbox-container .input-group.date').datepicker({
});
```

Anyway thanks for solution!

**Comment by Azaret** [comment]
Hmmm might be a typo on the sandbox.
