### ISSUE TITLE
Disable the possibility to jump to month and year views by clicking on the top part

### ISSUE THREAD

**Issue by gkatsanos** [eternicode/bootstrap-datepicker#1659]
Even though my start date is today and all other past dates are disabled, I can still switch to the month or year view. Would it possible to disable that functionality? (is there an option or do I have to add a custom event handler that cancels the click event assigned by the script?)

**Comment by Azaret** [comment]
You can use [`maxviewmode`](http://bootstrap-datepicker.readthedocs.org/en/stable/options.html#maxviewmode) to do so.

**Comment by gkatsanos** [comment]
I did, and still when I click on the top I go to years/months.

```javascript
        $(function() {
                        var datesDisabled = [
                "07/11/2015",
                "10/11/2015"
            ];
            $('#fake-date-input').datepicker({
                autoclose: true,
                weekStart: 1,
                maxViewMode: 0,
                format: 'MM dd, yyyy',
                startDate: '0d',
                endDate: '+15d',
                language: $('html').attr('lang'),
                datesDisabled: datesDisabled,
                container: '#fake-date-input'
            });
        });

        var isPaymentEnabled = true;
    ```

**Comment by Azaret** [comment]
I cannot reproduce with 1.5.
While I can click on the header nothing happen as expected.

**Comment by gkatsanos** [comment]
It was caching, now it's all fine, thanks!
