### ISSUE TITLE
I need the parameters from locale file

### ISSUE THREAD

**Issue by rogloz** [eternicode/bootstrap-datepicker#1664]
Hi. I'm new in this, but i need help!!!

Is there any way to get the parameters by example weekstart, daysShort, daysMin, months, etc, from a datepicker to use it in html code?

**Comment by acrobat** [comment]
If you have included your locale file, you can get the info from this property `$.fn.datepicker.dates['pt']`

**Comment by rogloz** [comment]
thanks
