### ISSUE TITLE
Custom formatting does not retrieve the correct date

### ISSUE THREAD

**Issue by tommysanterre** [eternicode/bootstrap-datepicker#1667]
When using custom formatting the day is one day behind the value displayed in the date picker.

If you select November 1st the date passed to the toDisplay function is actually October 31st.

http://plnkr.co/edit/i3YEu1fRHFcuSpgQTmVh?p=preview

**Comment by tommysanterre** [comment]
@abibell, I see you created the feature. Any ideas?

**Comment by abibell** [comment]
Oh yes. Here are few things you need to understand:
1. Custom formatting functions are available so the developer can customise the formatting backing and forth. Your functions are your result.
2. The primary purpose was to store dates in ISO/UTC format in Database, but let the user see their local browser timezone datetime. Here is a working example of this https://gist.github.com/abibell/21be920e95d6cc9d247f
3. Your code does convert UI date to ISO date object as I can see. Not other way around properly. You can use the gist above and can customise to your needs.

**Comment by tommysanterre** [comment]
I copied code from the documentation and didn't remove the comment. What i'm trying to show is that when selecting a date in the calendar the date passed to the toDisplay function is one day behind. I'm not trying to do any conversion.

**Comment by tommysanterre** [comment]
I see that calling toISOString() on the passed date return the correct day. The issue was really the timezone as you mentioned. Thanks.

**Comment by abibell** [comment]
@tommysanterre you are welcome mate.
All good👍
