### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined(anonymous function) @ bootstrap-datepicker.ru.js:15

### ISSUE THREAD

**Issue by fazliddin** [eternicode/bootstrap-datepicker#1675]
My jquery version is 1.11.3

**Comment by acrobat** [comment]
Can you provide a jsfiddle example to display the problem? Looks like jquery is not yet loaded

**Comment by fazliddin** [comment]
jQuery is loaded, I can see it. I am using this component from yiibooster and bootstrap-datetimepicker.js date is 2013-09-12. but i am using 1.11.3 may be this problem

**Comment by fazliddin** [comment]
actually problem appears on chrome, but not in firefox. I am using debian 8.

**Comment by acrobat** [comment]
If you say bootstrap-datetimepicker that is another library (https://github.com/Eonasdan/bootstrap-datetimepicker) 

Otherwise can you provide a jsfiddle to show us the exact problem?

**Comment by acrobat** [comment]
Closing this for now, leave a comment if the problem is with this datepicker
