### ISSUE TITLE
Feature Request: Holiday Repeater

### ISSUE THREAD

**Issue by sl1331** [eternicode/bootstrap-datepicker#1676]
Nice little widget. Wondering if could come up with a repetitive indicator for dates we want disabled all the time rather than having to put them in for every year. For example, New Year's day, where we could set the datesDisabled to something like 01/01/XXXX or 01/01/####. Would indicate that we want January 1st disabled for every year.

Also wondering if there is a way to provide dynamic indicators such as 3rd Monday of month, but this not-so-much a request as a thought.

**Comment by acrobat** [comment]
That is something you can solve with the [`beforeShowDay` callback](https://bootstrap-datepicker.readthedocs.org/en/latest/options.html#beforeshowday). There you can implement the logic to disable dates without the year
