### ISSUE TITLE
Orientation "auto" not working in firefox when container is body

### ISSUE THREAD

**Issue by dfcamara** [eternicode/bootstrap-datepicker#1678]
In Firefox (42.0 and ESR 38.4.0) body.scrollTop is always zero so orientation "auto" doesn't work when container defaults to body. Workaround is set option "container: $(document.documentElement)" in this case.

See: https://www.google.com/search?q=body.scrollTop+deprecated

**Comment by dfcamara** [comment]
It's the same issue and 1.5.1 fixes it. Maybe I'm mistaken but I think I have tried with 1.6.0-dev and so I thought it was not fixed. Thanks.

**Comment by acrobat** [comment]
@dfcamara can you confirm if it's still an issue on 1.6.0-dev (current master)? As we may have a possible regression

**Comment by acrobat** [comment]
Ok great! Thanks for the feedback @dfcamara!
