### ISSUE TITLE
Options using Attributes with uppercase fail

### ISSUE THREAD

**Issue by petterberglund** [eternicode/bootstrap-datepicker#1682]
Hi,

Noticed that when you apply options using the "data-date-"-attribute it fails to apply due to a lower-case in the opts_from_el function.

For example, the format will apply but the weekStart will not. 

data-date-format="yyyy-mm-dd"
data-date-weekStart="1"

I've made a temporary quickfix on this, replacing the 
out[inkey] = data[key];
with
out[opt] = data[key];

where I filter out "opt" based on the names in the defaults array.

**Comment by frederikprijck** [comment]
The documentation states the following: 

```
Most options can be provided via data-attributes. An option can be converted to a data-attribute by taking its name, **replacing each uppercase letter with its lowercase equivalent preceded by a dash**, and prepending “data-date-” to the result. For example, startDate would be data-date-start-date, format would be data-date-format, and daysOfWeekDisabled would be data-date-days-of-week-disabled
```

So weekStart should be applied as data-date-week-start, not as data-date-weekStart
```
<input type="text" class="form-control" id="myDatePicker" data-date-format="dd/mm/yyyy" data-date-week-start="2">
```

Here is a js fiddle demonstrating this: https://jsfiddle.net/hewhy2mm/3/

**Comment by acrobat** [comment]
Thanks @frederikprijck for the solution! Closing the issue
