### ISSUE TITLE
How to convert datepicker date to mysql date

### ISSUE THREAD

**Issue by abstractindia** [eternicode/bootstrap-datepicker#1683]
Sir, I am having problem inserting date in mysql table. I have formated datepicker to display dd-mm-yyyy and mysql needs the date in format yyyy-mm-dd. Can you suggest me how to configure this. I want the date to be displayed in dd-mm-yyyy and converted to mysql format when insert / update.
Please guide.

**Comment by frederikprijck** [comment]
The datepicker is designed to work that way, so I guess you are doing something wrong.

You can set the format of the datepicker using the following code:

```
$('#myDatePicker').datepicker({
    format: 'dd/mm/yyyy'
});
```

This only modifies the format for displaying purposes. The actual value is still a javascript Date object and can be easily parsed to the ISO format or any other format you like:

```
var date = $("#myDatePicker").datepicker("getDate");
console.log(date.toISOString()); // Logs in the format YYYY-MM-DDTHH:mm:ss.sssZ
```

However I would advice you to send the javascript date object to your backend and let the serializer do the work. I dislike keeping track of dates as a string.
