### ISSUE TITLE
I am trying to get the orientation right for the tooth for date picker.kindly help.

### ISSUE THREAD

**Issue by vizart87** [eternicode/bootstrap-datepicker#1686]
![image](https://cloud.githubusercontent.com/assets/15833615/11341233/d625b0b0-9201-11e5-86a9-f4ab285e3b32.png)

**Comment by acrobat** [comment]
Which version of the datepicker do you use? Can you provide a jsfiddle to display the problem?

**Comment by vizart87** [comment]
I fixed the issue with over riding the datepicker.css. 
+.datepicker-dropdown.datepicker-orient-top:after {
+    bottom: -6px;
+    border-bottom: 0;
+    border-top: 6px solid #ffffff;
+    top: initial;
+}
