### ISSUE TITLE
How to Initialize datepicker with a date and show it in <input>  Element?

### ISSUE THREAD

**Issue by huguangju** [eternicode/bootstrap-datepicker#1688]
this my code:  

```js
$('.input-group.date').datepicker({
      minViewMode: 1,
      autoclose: true
 }).datepicker('update', new Date());
```

There may be a better solution？take for example:
```js
$('.input-group.date').datepicker({
      minViewMode: 1,
      autoclose: true,
      initDate: new Date()
});
```

**Comment by blag001** [comment]
This is a bug tracker, not a help-desk... 
For this kind of question, please use website like [StackOverflow](http://stackoverflow.com/questions/tagged/bootstrap-datepicker)

BTW : 
https://bootstrap-datepicker.readthedocs.org/en/latest/options.html#id3
or use the jquery `$('.date').val(new Date())` before calling the datepicker

[to close]
