### ISSUE TITLE
Bootstrap-datepicker and J-query datepicker conflict

### ISSUE THREAD

**Issue by malenkymuk** [eternicode/bootstrap-datepicker#1694]
I'm using autocomplete from Jquery-ui.
Also jquery-ui has own datepicker.
Bootstrap-datepicker and J-query's datepicker conflict.
When using both jquery datepicker replaces Bootstrap-datepicker.

**Comment by vsn4ik** [comment]
See: http://bootstrap-datepicker.readthedocs.org/en/master/#no-conflict-mode.

**Comment by acrobat** [comment]
Closing this as the link from @vsn4ik should fix the issue
