### ISSUE TITLE
datepicker gets broken

### ISSUE THREAD

**Issue by adithyan** [eternicode/bootstrap-datepicker#1695]
I use requirejs to optimize my project. After optimization, the datepicker gets broken

![screen shot 2015-12-01 at 9 14 53 pm](https://cloud.githubusercontent.com/assets/1707567/11505548/f4be449a-9870-11e5-8818-ecf282b8893c.png)

>$('#datepicker').datepicker({
        format: "dd/mm/yyyy",	// no i18n
        endDate: new Date(),
        autoclose: true,
        orientation: "top left",	// no i18n
        todayBtn: "linked",	// no i18n
    });

Help needed, Thanks in advance

**Comment by acrobat** [comment]
Can you provide a jsfiddle to display the problem? I can't reproduce it, see [example here](http://jsfiddle.net/zcvq0yhh/10/)

**Comment by adithyan** [comment]
After moving to latest 1.5.* the above issue is fixed
