### ISSUE TITLE
Default dates are not getting displayed.

### ISSUE THREAD

**Issue by prashanthsun9** [eternicode/bootstrap-datepicker#1715]
Default dates are not displayed, I am trying to select today's date and one month previous date, which is not displayed inside the input box, i have tried all kinds of solutions and every possible resolution provided by users in github and as well as stackoverflow, nothing worked, please help, below is my code.

    $('#from').datepicker({
        format: 'mm/dd/yyyy',
        autoclose: true,
        startDate: '-1y',
        endDate: '+2y',
        todayHighlight: true
    });
    var currentDate = new Date();
    $('#from').datepicker('update', currentDate);
    $('#to').datepicker({
        format: 'mm/dd/yyyy',
        autoclose: true,
        startDate: '-1y',
        endDate: '+2y',
        todayHighlight: true
    });
    currentDate.setDate(currentDate.getDate() - 31);
    $('#to').datepicker('update', currentDate);

**Comment by hebbet** [comment]
can you provide a jsfiddle?

**Comment by prashanthsun9** [comment]
OK, i figured out the problem it is with jQuery plugin, everything works fine, with just datepicker files added as external resources, if I add jQuery plugin then nothing works, here is a fiddle link,
http://jsfiddle.net/DwT8M/675/

**Comment by prashanthsun9** [comment]
Not a bug, it was angular which was causing a problem, fixed it by my self, thank you, anyway :)
