### ISSUE TITLE
Arrows not showing up

### ISSUE THREAD

**Issue by baardbaard** [eternicode/bootstrap-datepicker#1717]
Hi,

I implemented the standalone version of the datepicker and everything seems to be working fine, except that the next and previous arrows don't show up. I can click where they are supposed to be and it works, but I would really like some arrows.

I found #610 and there's supposedly a fix in the works for 1.6, but what can I use in the meantime? 

Thanks.

**Comment by acrobat** [comment]
What you could try is to overwrite the arrow classes like this:

```
th.previous:before  {
  content: "<" !important;
}

th.next:before  {
  content: ">" !important;
}
```

But that's a hacky workaround. I'm going to try to wrap things up and have 1.6 out by the end of the year (no specific timing for the moment!)

**Comment by baardbaard** [comment]
Thank you for the quick response. This will do for now. Looking forward to the 1.6 release!

**Comment by M-Shahbaz** [comment]
.next span:before {
								position: relative;
								top: 1px;
								display: inline-block;
								font-family: 'Glyphicons Halflings';
								font-style: normal;
								font-weight: 400;
								line-height: 1;
								-webkit-font-smoothing: antialiased;
								-moz-osx-font-smoothing: grayscale;
								content: "\e080";
								border: 0px;
								color: #333;
							}
							.prev span:before {
								position: relative;
								top: 1px;
								display: inline-block;
								font-family: 'Glyphicons Halflings';
								font-style: normal;
								font-weight: 400;
								line-height: 1;
								-webkit-font-smoothing: antialiased;
								-moz-osx-font-smoothing: grayscale;
								content: "\e079";
								border: 0px;
								color: #333;
							}
