### ISSUE TITLE
Back and Forward Arrow Navigation Broken

### ISSUE THREAD

**Issue by dougkozar** [eternicode/bootstrap-datepicker#1718]
The Back and Forward navigation arrows in the calendar pop-up widget work properly in the 1.5.0 CDN version at CloudFare (https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.min.js) but do not work properly in the 1.5.0 version here on GitHub.

**Comment by acrobat** [comment]
Hi @dougkozar thanks for the bug report, can you provide a jsfiddle to display the problem?

**Comment by cyberbobjr** [comment]
Hi,
i'm confirm the bug...

**Comment by vsn4ik** [comment]
Fixed by #1722?

**Comment by acrobat** [comment]
Closing this issue for now as it should be fixed in #1722. If this is still an issue on the current master please comment/reopen!
