### ISSUE TITLE
1.6.0Dev The year navigation error

### ISSUE THREAD

**Issue by gaojianzhuang** [eternicode/bootstrap-datepicker#1719]
If we click the back button in the top year area, the time show wrong.

**Comment by acrobat** [comment]
@Azaret seems to be a bug wxhen u switch to decade or century view then the laft arrow also goes up: http://jsfiddle.net/zcvq0yhh/15/

If you have time to look at it that would be great! Otherwise I will have some time in the weekend!

**Comment by acrobat** [comment]
Fixed in #1722
