### ISSUE TITLE
[1.6.0-Dev] Clicked on prev or next

### ISSUE THREAD

**Issue by vHades0199** [eternicode/bootstrap-datepicker#1720]
Hi. I found a bug when click on glyphicon in prev button.
Can fix like this:
             // Clicked on prev or next
            var navArrow=target.closest('.prev, .next')
             if (navArrow.length > 0) {
                 dir = DPGlobal.modes[this.viewMode].navStep * (navArrow.hasClass('prev') ? -1 : 1);

**Comment by acrobat** [comment]
Hi @vHades0199 , thanks for the bug report! Can you provide a jsfiddle to display the problem? As I can't reproduce it

**Comment by ArsenePadthai** [comment]
Hi, I also found this bug. 
When clicking the prev arrow,  it sometime goes to the next month. @vHades0199 your solution can fix this, thank you.

**Comment by acrobat** [comment]
@ArsenePadthai can you provide a jsfiddle to display the problem? Makes it easier to fix and test

**Comment by SanderVanDam** [comment]
Its the same issue as https://github.com/eternicode/bootstrap-datepicker/issues/1719 and the solution provided by @vHades0199 solves it.

**Comment by ArsenePadthai** [comment]
http://jsfiddle.net/hjv4xL74/
@acrobat Hi, someone has already provide the jsfiddle related to this bug as #1719. However, I provide this jsfiddle as an alternative. Hope it can help.

**Comment by acrobat** [comment]
Thanks @ArsenePadthai! It looks like it's related to #1719 but here the bug already occurs on the day selection.

I will come up with a fix!

**Comment by acrobat** [comment]
Fixed in #1722
