### ISSUE TITLE
Rename "remove" function to "destroy"

### ISSUE THREAD

**Issue by tgirardi** [eternicode/bootstrap-datepicker#1721]
Bootstrap plugins use the name "destroy" for the method that removes the plugin form the web page. I suggest using the same name for standardization purposes. 

For backward compatibility, the name "remove" could be an alias of "destroy".

I can make a PR of this if you find it to be a good idea.

**Comment by acrobat** [comment]
That sounds like a good idea! Please create a PR if you have the time, thanks!

**Comment by tgirardi** [comment]
Nice. Work for the weekend then hahaha

**Comment by acrobat** [comment]
Closing this issue. Fixed in #1732 and will be released in 1.6.0
