### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by canfiax** [eternicode/bootstrap-datepicker#1733]
What about Bootstrap 4 support?

**Comment by acrobat** [comment]
Bootstrap 4 progress is tracked in #1670. But we won't start on a BS4 theme until they reach the beta stage

**Comment by sohrabzia** [comment]
any progress yet?

**Comment by sahilchopra** [comment]
+1

**Comment by samuelg0rd0n** [comment]
Is there any progress? Does the plugin support Bootstrap 4 or not?
