### ISSUE TITLE
bower package is not up-to-date

### ISSUE THREAD

**Issue by ManuelHaas** [eternicode/bootstrap-datepicker#1737]
Hi!

When I try to add the package in Visual Studio 2015 with bower the latest version available is 1.4.1.

I'm not sure where the problem is located - is it on your side or is it a Microsoft problem?

Best regards, Manuel

![bootstrap-datepicker](https://cloud.githubusercontent.com/assets/10881695/12018116/785e925c-ad5f-11e5-8384-a24dee1411ae.PNG)

**Comment by acrobat** [comment]
This looks like an issue with Visual Studio as bower just uses the tags available on github. You can check the [libraries.io page](https://libraries.io/bower/bootstrap-datepicker) for all available versions!
