### ISSUE TITLE
Inline or Embedded Calendar not Responsive?

### ISSUE THREAD

**Issue by MarcPinnell** [eternicode/bootstrap-datepicker#1739]
New to your Date Picker. Super simple to implement, thank you!

After getting it up and running, I realized the embedded calendar wasn't responsive. I don't see any options to set it to be, nor do I see any particular CSS that needs to be changed to make the calendar responsive.

Suggestions?

**Comment by hebbet** [comment]
can you provide a jsfiddle?

**Comment by MarcPinnell** [comment]
Haven't done that before, but here goes! https://jsfiddle.net/SoccerGuy3/zn4zf6rs/

**Comment by MarcPinnell** [comment]
https://jsfiddle.net/SoccerGuy3/zn4zf6rs/


On Dec 29, 2015, at 12:26 AM, hebbet <notifications@github.com> wrote:

> can you provide a jsfiddle?
> 
> �
> Reply to this email directly or view it on GitHub.
> 

Marc Pinnell
1027 Design
PO Box 990872
Redding, CA 96099-0872
530.941.4706
fax: 866.232.5300
www.1027Design.com
Certified Lasso Developer

**Comment by MarcPinnell** [comment]
ping....

**Comment by russ-ab** [comment]
Check this out: https://jsfiddle.net/4zbrh768/1/

**Comment by MarcPinnell** [comment]
Beautiful! Thanks!

**Comment by acrobat** [comment]
So I guess your issue is fixed @MarcPinnell?

**Comment by MarcPinnell** [comment]
Yep! Worked perfectly.
