### ISSUE TITLE
JQuery datepicker unable to navigate with keyboard when Startview changed to month or year

### ISSUE THREAD

**Issue by sanals** [eternicode/bootstrap-datepicker#1740]
JQuery datepicker is unable to navigate with keyboard when Startview changed to 1-month or 2-year. I have given the link below for reference.
I am using the pluign from this link: http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=2&maxViewMode=2&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox

**Comment by sanals** [comment]
Sorry I didn't know that, I was able to change year by pressing down Ctrl and could change month with shift. Had to go through the code o ind that. Thanks...

**Comment by acrobat** [comment]
@sanals you can check [the docs here](https://bootstrap-datepicker.readthedocs.org/en/latest/keyboard.html#up-down-left-right-arrow-keys) to get more info on the keyboard support
