### ISSUE TITLE
Typescript defination

### ISSUE THREAD

**Issue by activebiz** [eternicode/bootstrap-datepicker#1741]
It would great if the control support typescript. There is a definition file at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/bootstrap.v3.datetimepicker/bootstrap.v3.datetimepicker.d.ts but it looks outdated.

As everything is going towards ECMA Script 2015 (and typescript) it would be great if there is a typescript definition under the same repo as the code.

Great control btw. Good work.

Thanks

**Comment by hebbet** [comment]
the linked file is about datetime**picker**, closing that ticket.
