### ISSUE TITLE
remove .idea on npm

### ISSUE THREAD

**Issue by luqin** [eternicode/bootstrap-datepicker#1742]
remove unnecessary file on npm such as docs, grunt, .idea

**Comment by acrobat** [comment]
And where do you have the .idea directory? There is nog grunt dir in the docs directory

**Comment by luqin** [comment]
docs, grunt, .idea

**Comment by hebbet** [comment]
i can't find any .idea-file.

**Comment by webhacking** [comment]
where is .*idea-files?? i can't find

**Comment by luqin** [comment]
![image](https://cloud.githubusercontent.com/assets/2267688/12059903/820f7fae-af9f-11e5-835c-4bde2c46e3d0.png)

**Comment by hebbet** [comment]
could verify it with a fresh install of npm. 

added .npmignore with 2c7d569384cdd3d

**Comment by luqin** [comment]
:+1:
