### ISSUE TITLE
Release date for 1.6.0?

### ISSUE THREAD

**Issue by jeremyschultz** [eternicode/bootstrap-datepicker#1746]
Just wondering when 1.6.0 and its assumeNearbyYear option will be officially released. Thanks!

**Comment by tclindner** [comment]
+1

**Comment by acrobat** [comment]
My plan is to have 1.6.0 released by the end of the month, but we will work with some beta/rc releases first. So I hope you guys can give those RC's a test before the final release!

I will ping this issues when the beta/rc is out! (and the stable release)

**Comment by acrobat** [comment]
@jeremyschultz @tclindner I've just release v1.6.0-alpha please test this release and report any issues! Then we should have a stable release (if no major issues) by the end of the month!

**Comment by acrobat** [comment]
@jeremyschultz @tclindner 1.6.0 was just released! Check [the release](https://github.com/eternicode/bootstrap-datepicker/releases/tag/v1.6.0) page for the changelog!

**Comment by tclindner** [comment]
Awesome, nice work! Thank you, @acrobat
