### ISSUE TITLE
Highlight holidays

### ISSUE THREAD

**Issue by slookabill** [eternicode/bootstrap-datepicker#1757]
Is there a way to add highlights selected holidays throughout the selection?

**Comment by acrobat** [comment]
Please read the docs before opening issues!

But there are a few way to highlight days. You have the [daysofweekhighlighted option](https://bootstrap-datepicker.readthedocs.org/en/latest/options.html#daysofweekhighlighted) to highlight fixed days. Or [beforeshowday option/callback](https://bootstrap-datepicker.readthedocs.org/en/latest/options.html#beforeshowday) to add custom logic to highlight/disable specific dates
