### ISSUE TITLE
How can I set backgroud for day?

### ISSUE THREAD

**Issue by LuciferZhang** [eternicode/bootstrap-datepicker#1759]
Now I want to send a date-array to datepicker, eg:[new Date(2016,1,18,'colorClass'), new Date(2016,1,19,'colorClass')]  , and how to set these days backgroud style? look like this.
![image](https://cloud.githubusercontent.com/assets/10653933/12412952/200f7030-bec6-11e5-8b2d-03ff688851e4.png)

tips: colorClass is classname of what I have defined.

**Comment by acrobat** [comment]
You can use the [beforeshowday option](https://bootstrap-datepicker.readthedocs.org/en/latest/options.html#beforeshowday) to get the extra class applied!

**Comment by LuciferZhang** [comment]
beforeShowDay: function (date) {
                    scope.schedules.forEach(function (day) {
                        if(date.getFullYear() == day.getFullYear() && date.getMonth() == day.getMonth() && date.getDate() == day.getDate()){
                            return 'green';
                        }
                    });
                }

it  doesn't work!
