### ISSUE TITLE
How do I pull in this library + time picker?

### ISSUE THREAD

**Issue by canfiax** [eternicode/bootstrap-datepicker#1763]
I am currently pulling in this library in my bower.json, that supports time picking as well:

    "bootstrap-datepicker": "git@github.com:rchavik/bootstrap-datepicker.git#5d82d35f54c25b8cebda0c0f7493a39a80f1c4e8",

How can I pull in the latest 1.6 alpha AND have the timepicker?

**Comment by acrobat** [comment]
That's a fork of this repository so the owner of the fork should update his fork with the original codebase! You should contact @rchavik about it!

**Comment by canfiax** [comment]
@rchavik would that be doable? :)

**Comment by rchavik** [comment]
@canfiax sorry, i'm unable to do this due to time constraints.

maybe you can help rebasing #909 on top of latest master?

**Comment by acrobat** [comment]
Yes timepicking is something we have planned for 2.0/2.x but before we integrate that feature we want to rewrite some inner works so we can handle dates and datetimes better!

**Comment by canfiax** [comment]
@acrobat any updates on this? There are currently no libraries out there that efficiently support this.

**Comment by acrobat** [comment]
@canfiax you could use [Eonasdan/bootstrap-datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker). Which is sort of the same code base but with time picking and some other different features.

Again timepicking is something that should come to this lib in the future. But currently I don't have the time to added new features, etc to thislib. I hope that I can make some time in a few months!

So for now you could use the eonasdan datetimepicker!

**Comment by canfiax** [comment]
Thanks @acrobat :)
