### ISSUE TITLE
Prev month not working

### ISSUE THREAD

**Issue by phillip-kruger** [eternicode/bootstrap-datepicker#1769]
Hi.
First of all, thanks for the great datepicker.

I have once issue where the prev month goes to the next month.

Here my conf

$('#datepicker_lg').datepicker({
        format: 'yyyymmdd',
        startDate: "today",
        endDate: "+7d",
        weekStart:1
    });

So I only allow selection for the next 7 days. At the end of the month the next month become available and the arrow next to the month shows up. Clicking next month actually goes to the next month and then prev month arrow shows up. However clicking that goes to the next month rather the prev.

![image](https://cloud.githubusercontent.com/assets/6836179/12543400/d6135552-c337-11e5-8afc-1edd1614e281.png)

![image](https://cloud.githubusercontent.com/assets/6836179/12543411/e81de0dc-c337-11e5-934b-59da6e0df301.png)

![image](https://cloud.githubusercontent.com/assets/6836179/12543416/f86c555e-c337-11e5-839b-61be4f9e5e7c.png)

Thanks
Phillip

**Comment by phillip-kruger** [comment]
B.t.w I have tested this in 1.5.1 and the latest 1.6.0 alpha

**Comment by acrobat** [comment]
@phillip-kruger can you provide a jsfiddle that has the problem? As I can't seem to reproduce this issue here http://jsfiddle.net/zcvq0yhh/22/

Thanks!

**Comment by phillip-kruger** [comment]
OK I see now it's working with the latest alpha. I must have tested the
wrong one. I get it in a prev version. But I'll just upgrade ! Thanks !!

**Comment by acrobat** [comment]
Ah great! Should have worked in the alpha as we had a specific fix for that issue! Stable should be out by the end of the month (or around the end)

**Comment by phillip-kruger** [comment]
Thanks !!
