### ISSUE TITLE
Full text search problems

### ISSUE THREAD

**Issue by daniyel** [eternicode/bootstrap-datepicker#1782]
Hi.

We are experiencing some full text search problems, or maybe we are using it the wrong way.

We have index as 

```
...
"user.address.city" : {type : "text", analyzer : "german"},
...
```

And we are using filter and query option to search for all records that match the name or partially match the name, meaning they contain substring of the searched string.

We have used `wildcard, contains, prefix,` you name it but the search is weird. We have for example `Indianer-Dorf` and if we type `i` we get nothing then `in` again nothing then all up to `india` then we see this record and if we continue typing `ner` we are not getting any records back. Also if we just type `re`, we have examples that are starting with `re` or have `re` somewhere in the string and so on but we are not getting all the matches.

We are using Cassandra version 2.2.4 and plugin version 2.2.4.1.

**Comment by acrobat** [comment]
@daniyel are you sure this issue is related to this library/plugin? As there is no 2.2.4.1 version and don't seems to get the link between a full text search and a datepicker

Can you provide some more info?

**Comment by daniyel** [comment]
@acrobat i found what was the issue, i think there is somewhere else one ticket with same problem, we set the type "text" instead of "string" now it is working as expected with the search, just did not realize how the text and analyzer work in the first place.

Thank you for your help. I will put the link to the issue, where I found solution.
