### ISSUE TITLE
remove sourceMappingURL form .css and .min.css builds perhaps?

### ISSUE THREAD

**Issue by MartijnR** [eternicode/bootstrap-datepicker#1795]
I think including source maps is useful for developers of bootstrap-datepicker.

However, when using your great library in large projects where your .css file is imported (because the projects don't use less e.g.), it becomes a slight nuisance to ignore/avoid all those failed requests for bootstrap-datepicker.min.css.map.

**Comment by acrobat** [comment]
@vsn4ik any idea how to solve this or do you have experienced this problem yourself?

**Comment by vsn4ik** [comment]
Uncheck this in chrome dev tools settings.
![q6mtd](https://cloud.githubusercontent.com/assets/3757319/13399202/20bfd002-df13-11e5-8b44-d1d3c2fc49e8.png)

I think if the project is large, you can easily add task for compilation bootstrap-datepicker without source maps.

**Comment by MartijnR** [comment]
Ok, so we disagree about the need to add those references to the compiled css. I think they don't belong there.

(I don't want to add a less build system just for this reason of course).
