### ISSUE TITLE
How to disable past date on datepicker of boostrap 3?

### ISSUE THREAD

**Issue by allin81** [eternicode/bootstrap-datepicker#1808]
Hi all,
this is my first ask there.

I'm using boostrap 3 and i have to disable the past date of the datepicker

This is my actual code

`<script type="text/javascript">
$(function () {
$('#form_datetime').datetimepicker({
                format: 'DD/MM/YYYY',
            });
});
</script>`

i tryed with minDate +1 but not work
How i can make?

Thank you

**Comment by hebbet** [comment]
you are not using that plugin, you are using datetimepicker. 

closing that issue.

**Comment by allin81** [comment]
sorry, datepicker and datetimepicker are 2 different plugin?

**Comment by hebbet** [comment]
yes.

**Comment by allin81** [comment]
ok, so can you link me a file where i can download the script datepicker and i can customize it with some examples?
