### ISSUE TITLE
Orientation wrong

### ISSUE THREAD

**Issue by robjens** [eternicode/bootstrap-datepicker#1816]
This is with orientation bottom, top does the same but the other way around so it is never pointed towards the element.

![image](https://cloud.githubusercontent.com/assets/11848802/13438894/e826d396-dfe2-11e5-9248-154f25d262b7.png)

Not sure if this ticket will do anything, as there are `+300` other ones in line. Also this seems to be limited to modal usage (of course), scanning a LOT of issues and nothing describes this. Please advice.

(should i find the 'fix', I'll drop a note and close this to keep the pile from collapsing)

**Comment by robjens** [comment]
Well, since changing orientation messes up the position, I used Chrome Dev tools and noticed the CSS was working fine, it just had a issue with switching position around as soon as I toggle up (to down) and down (to up).

First I thought it might have been the positioning of the modal, moved that around, wasn't it. Nothing funky with the input field it is attached to either (position css, removed static, nop).  
So I thought, two can play that game, after finally having tried to instantiate the picker AFTER the modal was being opened, -also no effect- to finally just screw-you-guys-im-going-home mode, which of course did work:

```
$('#dtstart, #dtend').datepicker({
  locale: 'nl',
  orientation: 'auto bottom'
}).on('show', function () {
  $('.datepicker-orient-bottom').removeClass('datepicker-orient-bottom');
  $('.datepicker-dropdown').addClass('datepicker-orient-top');
});
```
Problem 'solved' I guess....

**Comment by hebbet** [comment]
that bug should be fixed in 1.5 or 1.6

**Comment by robjens** [comment]
Alright, thanks for keeping me posted.

**Comment by anpegar** [comment]
Hi !!
The problem wasn't solved in 1.5.1 and upper.

I've found out that in the 1.3.0 works fine !!

Version 1.5.1
![image](https://cloud.githubusercontent.com/assets/8124520/16837920/b4b6b136-49c6-11e6-9f2c-3dc9383918b4.png)



Version 1.3.0
![image](https://cloud.githubusercontent.com/assets/8124520/16837906/943686ca-49c6-11e6-941e-5c6d8105c9c0.png)

**Comment by acrobat** [comment]
@anpegar can you provide a jsfiddle example? thanks!

**Comment by anpegar** [comment]
Here it is
https://jsfiddle.net/7f0f0ao4/

If you change this 
//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.1/js/bootstrap-datepicker.min.js

by this
//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js

It works fine !!

**Comment by julianfox** [comment]
Same for me, I have to use the 1.3.0... Any update about it ?

**Comment by wagner** [comment]
Still not working @ 1.6.5.

**Comment by joelklingler** [comment]
I fixed it using the following JS:

https://github.com/soulim/ember-cli-bootstrap-datepicker/issues/78#issuecomment-296571933

**Comment by hughanderson4** [comment]
I noticed this behavior when I updated my installation of Bootstrap Datepicker. I updated the .js file but forgot to also update the .css file. I had wrong arrow. Once I updated also the css file to latest version, my arrows work correctly now.
