### ISSUE TITLE
Manual setting of date range

### ISSUE THREAD

**Issue by jarodium** [eternicode/bootstrap-datepicker#1821]
Hello

I have a form in which I have 4 inputs in the DOM:

date_start
time_start
date_end
time_end

When I setup the form with class input-daterange the plugin is assuming that time_start is the "end_date" of date_start. I believe is getting all inputs and working with them.

Is there any way I can setup just the inputs I want?
I have tried to add class input-daterange and the following code:
```
$('#carBook .input-daterange').datepicker({
    todayHighlight: true,
    language: $("html").attr("lang"),
    format:'dd/mm/yyyy'
});
```

**Comment by burkovsky** [comment]
Hi @jarodium. You can manually setup list of inputs with [inputs](http://bootstrap-datepicker.readthedocs.org/en/stable/options.html#inputs) option.

**Comment by jarodium** [comment]
Hello @burkovsky 

will do. 

Thank you
