### ISSUE TITLE
autoclose not supported by the data-api

### ISSUE THREAD

**Issue by eadbhard** [eternicode/bootstrap-datepicker#1830]
I want to use bootstrap-datepicker without jquery. For this, data-provide="datepicker" on the input controls works perfectly. However, data-autoclose="true" or data-auto-close="true" seem not to work so I have to depend on a jquery call for this.

Please support autoclose in the data-api.

Thanks!

**Comment by acrobat** [comment]
The option you should use is `data-date-autoclose`. See [the docs](https://bootstrap-datepicker.readthedocs.org/en/latest/options.html#options) for more info. Example [here](http://jsfiddle.net/zcvq0yhh/38/)

**Comment by Danish-Ayub** [comment]
Thank you very very much, it's work

**Comment by arLevi** [comment]
Then you should update the docs, it seems that according to:
https://bootstrap-datepicker.readthedocs.io/en/stable/options.html#autoclose
`daysOfWeekDisabled would be data-date-days-of-week-disabled.`
Meaning `autoClose` should be `data-date-auto-close` ... not `data-date-autoclose` ....
