### ISSUE TITLE
Initialising a Datepicker element calls update() which triggers a change event even if nothing has changed

### ISSUE THREAD

**Issue by k-risc** [eternicode/bootstrap-datepicker#1846]
The web application we implement and maintain contains a lot of forms. We have event handlers that set a global `formModified` to true whenever a form field changes. `window.onbeforeunload()` then checks for `formModified` and displays a warning when it's true.

After updating bootstrap-datepicker.js to v1.6.0 we received reports by users about these warnings appear when leaving a page even when they changed nothing.

I analysed it and saw that when initialising a Datepicker, it calls update(). And at the very end of this function, before the final `return this;` you introduced:
`this.element.change();`

This triggers our event handlers and thus sets  `formModified` to true, which then triggers the alert when a user tries to leave the page.

What is the reason for a "forced" update event in the case that the elements value has not actually changed? In my opinion this is not entirely correct.

**Comment by adambiggs** [comment]
I'm dealing with this issue as well. See #1561
