### ISSUE TITLE
Support for HH:mm

### ISSUE THREAD

**Issue by canfiax** [eternicode/bootstrap-datepicker#1848]
What about support for hours and minutes? There aren't any good libraries out there that has support for this.

**Comment by antigoogle** [comment]
I am using this1: [http://curioussolutions.github.io/DateTimePicker/](url)

**Comment by acrobat** [comment]
We currently don't support timepicking but that could be a feature we add in the future (no eta or roadmap yet). But you could use the [Eonasdan/bootstrap-datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker) it was build from a fork from this lib but with now different and extra features, including time picking. So for now I would suggest you use the datetimepicker library!
