### ISSUE TITLE
Really terrible documentatition ...

### ISSUE THREAD

**Issue by antigoogle** [eternicode/bootstrap-datepicker#1850]
Try make better docs, no examples there, nothing.
 There are alot of better pickers with normal documentation.

**Comment by raveren** [comment]
You are a toxic little man spewing thankless, typo-laden bug reports all over github. 

The docs are linked in the readme: http://bootstrap-datepicker.readthedocs.org/en/latest/

**Comment by antigoogle** [comment]
I know this link ! I said the docs are terrible. Now, please:
1. push the button on your head ;
2. wait to load;
3. read the comment, again.

**Comment by acrobat** [comment]
@antigoogle feel free to fork the repo and improve the docs on section you feel that need improvement! Thanks!

**Comment by antigoogle** [comment]
I do not have problems to help if needed.

**Comment by acrobat** [comment]
@ghost Just fork the repo, extends the doc parts you feel need extra examples, explanation, ... and open a PR we will be happy te merge it if it make the part more clear!
