### ISSUE TITLE
v1.6 Uncaught TypeError: Cannot read property 'toDisplay' of undefined

### ISSUE THREAD

**Issue by camelyanvb** [eternicode/bootstrap-datepicker#1864]
Sorry,sorry!
I've figured this out.
Incorrect locale file - from v1.4

After upgrading from v 1.4 to v1.6 I am getting this error on page load
format is undefined in that moment
There is call stack

DPGlobal.formatDate (bootstrap-datepicker.js:2010)
Datepicker.fill (bootstrap-datepicker.js:993)
Datepicker.update (bootstrap-datepicker.js:825)
Datepicker (bootstrap-datepicker.js:147)
(anonymous function) (bootstrap-datepicker.js:1731)
jQuery.extend.each (jquery-2.1.1.js:375)
jQuery.fn.jQuery.each (jquery-2.1.1.js:139)
datepickerPlugin (bootstrap-datepicker.js:1713)
(anonymous function) (Testdp2.htm:58)

Fill  v1.4
this.picker.find('.datepicker-days thead .datepicker-switch')
            .text(dates[this.o.language].months[month]+' '+ (this.o.maxViewMode < 2 ? '' : year));

Fill Fill  v1.6

titleFormat = dates[this.o.language].titleFormat || dates['en'].titleFormat,
[but titleFormat still remains undefined, maybe because there is no titleFormat in locale??]
...
			this.picker.find('.datepicker-days .datepicker-switch')
						.text(DPGlobal.formatDate(d, titleFormat, this.o.language));

----------------------------------
And there is my testing page

 <div class="col-md-4" id = "sandbox-container">   
<div class="input-group date">
<input type="text" class="form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
</div>
</div>
 </div>
 
<script type='text/javascript' >

$('#sandbox-container .input-group.date').datepicker({
    format: "mm/dd/yyyy",
    todayBtn: true,
    autoclose: true
});

</script>
This is a bug, or I something doing wrong??

Thanks in advance

**Comment by acrobat** [comment]
@camelyanvb is this issue resolved?

**Comment by camelyanvb** [comment]
@acrobat 
Yes! Thank you. I have created an unnecessary locale file. This led to an error
