### ISSUE TITLE
disable previous dates

### ISSUE THREAD

**Issue by zaibazhar** [eternicode/bootstrap-datepicker#1865]
How to disable all previous dates except current date and onward?

**Comment by acrobat** [comment]
You can use `startDate: 'today'`for this. See example: http://jsfiddle.net/zcvq0yhh/42/

But please use this issue tracker for reporting bugs or feature requests and use sites like [stackoverflow](http://stackoverflow.com/questions/tagged/bootstrap-datepicker) or the [google groups page](https://groups.google.com/forum/#!forum/bootstrap-datepicker)  to get support setting up applications. Thanks!
