### ISSUE TITLE
Popup calendar position is set releated to body, which cause issue in modal

### ISSUE THREAD

**Issue by abdfahim** [eternicode/bootstrap-datepicker#1866]
The calendar that pops up when click on the datepicker button is attached to the body. Also the position of the calendar box is set as absolute.

So, when you place the datepicker in a long model (where modal can be scrolled), the calendar box does not scroll (because the position is set to body, and when we scroll modal, the body remains fixed).

In my opinion, calendar should be fixed with its parent.

You can check the issue in this fiddle. Click to open modal, then click to open calendar, then scroll down the modal (without closing calendar).

https://jsfiddle.net/abdfahim/Lkzvkmok/

**Comment by acrobat** [comment]
Does the option [`container`](https://bootstrap-datepicker.readthedocs.org/en/latest/options.html#container) fix your problem? See example: https://jsfiddle.net/Lkzvkmok/1/

**Comment by abdfahim** [comment]
Perfect. thanks.
