### ISSUE TITLE
re-enable disabled day on click

### ISSUE THREAD

**Issue by alexquinterorivera** [eternicode/bootstrap-datepicker#1872]
Problem:

I have disabled weekdays 0,6 (weekends)
I need to be able to enable specific days within weekends on click.

Right now when i try to manipulate classes it will not let me do this, it changes the class to remove disabled , then makes it active and brings back the disabled. So the active class will be added but the disabled class will not be removed.

$('#datepicker').datepicker().on('show', function(){
 $(".disabled").click(function(){
  $(this).removeClass('disabled');
 })
})

**Comment by Azaret** [comment]
`daysOfWeekDisabled` is not designed to have exception, you should use [`beforeShowDay`](http://bootstrap-datepicker.readthedocs.io/en/stable/options.html#beforeshowday) instead.

**Comment by alexquinterorivera** [comment]
Thanks! I misunderstood the assignment I was given, I had to make it a toggle so I used setdate

Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: "Gregoire D." <notifications@github.com> Datum: 08-05-16  10:56  (GMT+01:00) Aan: eternicode/bootstrap-datepicker <bootstrap-datepicker@noreply.github.com> Cc: alexquinterorivera <alexquinterorivera@gmail.com>, Author <author@noreply.github.com> Onderwerp: Re: [eternicode/bootstrap-datepicker] re-enable disabled day on click (#1872) 
daysOfWeekDisabled is not designed to have exception, you should use beforeShowDay instead.
