### ISSUE TITLE
Announcing picker.js project (ES2015 port) for BS3, BS4, BMD4 - and a thank you!

### ISSUE THREAD

**Issue by rosskevin** [eternicode/bootstrap-datepicker#1873]
I've just released an evolution of `bootstrap-datepicker` called [picker.js](https://github.com/alienfast/picker.js).  It is functionally complete for Bootstrap 3 and _mostly_ a drop in replacement, though some of the config has changed in structure.  

Since I switched from bootstrap 3 to bootstrap-material-design, I needed to make some major visual modifications, but I didn't want to lose the effort of creating the picker itself.  So I created a project that is the same logic wise, with pluggable framework templates.  It also delegates a lot of work to both moment.js and popper.js to ease maintenance.  I hope this will be useful for most who are using bootstrap.

I _very much welcome_ contributors from this project there, but most of all, I want to say a **big thank you** for all the work.  Now that I've done the port and refactoring, I can see how much time and effort went into making this work well.   **Thank you, Thank you**.

---------
Here's a quick summary

## Goal 

1. An ES2015 base classes for use in multiple renderings for different frameworks 
2. Variations of `datepicker`:
    - Bootstrap 3 - completed
    - Bootstrap 4 - works but could use some styling help
    - [bootstrap-material-design](https://github.com/FezVrasta/bootstrap-material-design/tree/v4-dev) 4 picker that meets the [Material Design specification](https://www.google.com/design/spec/components/pickers.html#) - works - needs help on the animated reveal/hide
3. (future) add time pickers - starting with material design    

## Why?
The `bootstrap-datepicker` project had 415 open issue and 64 open pull requests (at the time of writing).  Aside from popularity, one reason for this is it bit off a big chunk, including all date functionality and rendering/placement functionality.

Maintaining that much code may be too much for anyone, and we want to _expand_ it!  

## How?
- Use ES2015 classes (available as es, iife or umd)
- Use SCSS for full variable based customization/inclusion
- Use [moment.js](http://momentjs.com/) for anything date related
- Use [popper.js](http://popper.js.org/) for anything UI placement related
- Created `presets` for rendering on different frameworks (BS3, BS4, BMD4)   

---------------
Thanks again.  More information can be found here: https://github.com/alienfast/picker.js

**Comment by rosskevin** [comment]
Well this has been a short run!   We have just completed a refactoring of this bootstrap-datepicker into picker.js (it's in great shape) and we have decided to switch to a full ReactJs stack.  I've made a [call for new maintainers/owners](https://github.com/alienfast/picker.js/issues/15).  I'm willing to accept new maintainers or consider transferring ownership to someone that will continue to keep it in great shape for the community.  Please contact me if interested.

**Comment by acrobat** [comment]
Thanks for the heads up! Closing this issue for now as we keep putting effort in developing this library. We don't have the knowledge of the reworked lib as we know this library and it's already abandoned and looking for new maintainers (right after the "launch").

So thanks again for the information but we will currently stick to this library!
