### ISSUE TITLE
Bug for start date in sandbox alpha

### ISSUE THREAD

**Issue by abumalick** [eternicode/bootstrap-datepicker#1881]
I like your sandbox, very userfull.

Here is the bug : 
[screenshot](http://tinyurl.com/z9dec6l)
When you choose start date 01/01/1990
He starts in 3990

Keep up the good work !

**Comment by vsn4ik** [comment]
@acrobat Please, update the library itself on sandbox. Now only the actual text on buttons (49113f62669571d95433bd1ae48efe311539554b).

@abumalick I could not play with the latest stable version (1.6.1). Once @acrobat updates the version on sandbox, will have to try to play back again.

**Comment by Azaret** [comment]
Just tested on 1.6.1 and it works fine. I guess it's related to the sandbox page itself.

**Comment by acrobat** [comment]
The sandbox page was updated today and the bug seems to be resolved!
