### ISSUE TITLE
Update NuGet package to 1.6.1

### ISSUE THREAD

**Issue by leotsarev** [eternicode/bootstrap-datepicker#1884]
Dear @scott-xu,
could you please upgrade NuGet package to 1.6.1 version?

**Comment by leotsarev** [comment]
WOW, that was fast!

**Comment by leotsarev** [comment]
But sadly, that was wrong.
1.6.1 package is broken — probably something related to Scripts should be inside content

**Comment by acrobat** [comment]
I think it's best to use the [Contact owners](https://www.nuget.org/packages/Bootstrap.Datepicker/ContactOwners) link on the nuget page. Closing this for now as we don't maintain the NuGet package
