### ISSUE TITLE
event not trigger

### ISSUE THREAD

**Issue by spiritelf** [eternicode/bootstrap-datepicker#1888]
$([$birthday]).datepicker({
					    format: "yyyy-mm-dd",
					    language:__language,
					    startView: 0,
					    defaultViewDate: { year: 1977, month: 04, day: 25 },
					    //autoclose: true
					}).on("changeDate",function(){window.alert("aa")});   this not happen "aa"

**Comment by spiritelf** [comment]
why ???

**Comment by stanpalatnik** [comment]
$([$birthday]).on("changeDate",function(){window.alert("aa")});

**Comment by acrobat** [comment]
@spiritelf in the GitHub repository we only discuss bugs and new features. For this kind of questions please use any of the support alternatives like [gitter](https://gitter.im/eternicode/bootstrap-datepicker) or [stackoverflow](http://stackoverflow.com/questions/tagged/bootstrap-datepicker) Thanks!

-------------------------
The example of @stanpalatnik work, see [example](http://jsfiddle.net/zcvq0yhh/54/)
