### ISSUE TITLE
There is not '.date-reset' class for reset input

### ISSUE THREAD

**Issue by Federico-Comesana** [eternicode/bootstrap-datepicker#1902]
### Expected behaviour
I've been working with [datetimepicker.js](http://www.malot.fr/bootstrap-datetimepicker/) and It's fine.
Now I'm testing datepicker.js and I'm missing the functionality for reset the input.

![capture1](https://cloud.githubusercontent.com/assets/4299372/15595812/7c61a128-2398-11e6-9e2a-27878880d040.PNG)
![capture2](https://cloud.githubusercontent.com/assets/4299372/15595814/7f6707be-2398-11e6-8763-b8f15f34cb7a.PNG)
![capture3](https://cloud.githubusercontent.com/assets/4299372/15595837/bb89f67a-2398-11e6-89d4-256193f10f39.PNG)
![capture4](https://cloud.githubusercontent.com/assets/4299372/15595859/ea5096e4-2398-11e6-92eb-09e824a8eb3c.PNG)

### Actual behaviour
Doesn't have javascript code to handle date-reset class.

Tell us what happens instead.

### Datepicker version used
1.4.0

**Comment by acrobat** [comment]
The library you mention is a different than this library. You should open an issue at [smalot/bootstrap-datetimepicker](https://github.com/smalot/bootstrap-datetimepicker)

**Comment by Federico-Comesana** [comment]
Actually no. I've mentioned a different library only for getting an example.
What I'm suggesting is to copy the behavior of the other library (DateTimePicker.js). 
Both are very similar. 
This feature is desirable if you want to reset the datepicker without adding custom javascript code.

**Comment by acrobat** [comment]
Ah yes I've misread the issue. But we have [`clearBtn`](https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#clearbtn) option, if this is set to `true` it will display a button in the picker to clear it's value.

Example: http://jsfiddle.net/zcvq0yhh/68/

**Comment by Federico-Comesana** [comment]
Okay, thanks @acrobat , I didn't notice the 'clearBtn' function.

Thanks!
