### ISSUE TITLE
only upcoming dates

### ISSUE THREAD

**Issue by musman92** [eternicode/bootstrap-datepicker#1903]
i want to select date which is not passed, i.e today and future dates,

**Comment by MostlyChrisJ** [comment]
```javascript
$("#selector").datepicker({
 startDate: "0"
});
```

https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#startdate

**Comment by acrobat** [comment]
@musman92  in the GitHub repository we only discuss bugs and new features. For this kind of questions please use any of the support alternatives like [gitter](https://gitter.im/eternicode/bootstrap-datepicker) or [stackoverflow](http://stackoverflow.com/questions/tagged/bootstrap-datepicker) Thanks!

The solution @MostlyChrisJ sugests should fix your problem!
