### ISSUE TITLE
Button input-group-addon icon it's not working with ID

### ISSUE THREAD

**Issue by lenamtl** [eternicode/bootstrap-datepicker#1930]
### Expected behaviour
When clicking on button input-group-addon icon it's open the calendar

### Actual behaviour
When clicking on button input-group-addon icon  it's not opening the calendar

### Datepicker version used

v1.7.0-dev

### Example code

It's working ok if I use` data-provide="datepicker"` but it's not taking my custom settings.
```
$('#expiration').datepicker({
		autoclose: true,
		startDate: "today",

});

```
I have tried the sandbox code demo it's working online but not with my code
```
$('#expiration .input-group.date').datepicker({
});
```
Sandbox + select Component radio button
https://eternicode.github.io/bootstrap-datepicker/?#sandbox

**Comment by tiesont** [comment]
I think you mixed up the "expected" versus "actual" behavior, unless you **don't** want the calendar icon to open the datepicker.

**Comment by lenamtl** [comment]
Ho yes sorry I have corrected that ;)

**Comment by lenamtl** [comment]
I'm still doing test with no luck

```
<div class="form-group">
	<label for="contact_expiration">Expiration</label>
		<div class="input-group date">
			<span class="input-group-addon">
				<i class="fa fa-calendar"></i>
			</span>
			<input type="text" class="form-control input-sm" id="expiration" value="">
														
		</div>
</div>		
```

This is opening the calendar from the input only
$('#expiration').datepicker({
});


This work ok only if I use the class .input-group.date not the id #expiration for both input and button
How can I get the same result with the id?
```
$('.input-group.date').datepicker({
});

```

This act like 2 different calendar
```
$('#expiration, .input-group.date').datepicker({
});

```

This don't work at all
```
$('#expiration .input-group.date').datepicker({
});

```

**Comment by tiesont** [comment]
That last one will never work. Are you aware of [how CSS selectors work](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_started/Selectors#Information_Selectors_based_on_relationships)? `#expiration` is a descendant of `.input-group`, not the other way around (which is what your selector is trying to match). If you really only want the one element selected, use `.parents()` or `.closest()`:

```
$('#expiration').parents('.input-group').datepicker({
});
```
or
```
$('#expiration').closest('.input-group').datepicker({
});
```

**Comment by lenamtl** [comment]
I didn't pay attention.... shame on me... thanks
