### ISSUE TITLE
keepEmptyValues option: Doesn't exist inside dist/js files

### ISSUE THREAD

**Issue by fsbernardo** [eternicode/bootstrap-datepicker#1937]
### Expected behaviour
Option "keepEmptyValues" should be defined inside "dist/js" files

### Actual behaviour
There is no reference of this option in the actual files 

### Datepicker version used
1.6.1.

**Comment by acrobat** [comment]
keepEmptyValues was added in 1.7.0 (#1558) and this version is not yet released. So the option is not available in 1.6.1

**Comment by fsbernardo** [comment]
Hei,
You are correct. I haven't write down the correct version.
So I rephrase: On master version the option "keepEmptyValues" aren't defined as an default/option in "dist/js" files

**Comment by acrobat** [comment]
Ah yes, we a version is not released (dev-master code) we have to generate the dist files from time to time. This time it was a long time ago, so I've generated the dist files so you should be able to use the option now on master
