### ISSUE TITLE
getDate with range datepicker

### ISSUE THREAD

**Issue by tiberakis** [eternicode/bootstrap-datepicker#1945]
I want get the date of a datepicker using the getDate method. Although all is fine with a single datepicker, when i try the same with a range datepicker I can't get the date. 
Here is the html:
`<div class="input-group input-daterange" id="datepicker">
			<input type="text" class="form-control"  >
			<span class="input-group-addon">to</span>
			<input type="text" class="form-control">
</div>`
Here is the js:
`$(document).ready(function(){
    $('#datepicker').datepicker({
        //..
    });
    $('#datepicker').datepicker()
    .on('changeDate', function() {
		var my_date=$('#datepicker').datepicker('getDate');
		alert(my_date);
    });
});`
Here the fiddle:
http://jsfiddle.net/vh1oknf7/140/

i use version 1.6.1.
Surely I am making a stupid mistake but I don't find a solution. Any help? Thank you.

**Comment by tiberakis** [comment]
I solved the problem using the getDate method on each input of the range datepicker. Here the example:
[http://jsfiddle.net/vh1oknf7/141/]
As i said it was a stupid mistake.

**Comment by Igor1306** [comment]
> I solved the problem using the getDate method on each input of the range datepicker. Here the example:
> [http://jsfiddle.net/vh1oknf7/141/]
> As i said it was a stupid mistake.

Thank you so much, I'd saved a lot of time !:)
