### ISSUE TITLE
Broken against jQuery 3

### ISSUE THREAD

**Issue by pugnascotia** [eternicode/bootstrap-datepicker#1948]
### Expected behaviour
Contents of picker widget e.g. days of the month should be displayed.

### Actual behaviour
Picker opens but contents are not displayed

### Datepicker version used

1.6.1
Broken against jQuery 3.0.0 and 3.1.0

### Example code

http://jsfiddle.net/4x9wfayw/

**Comment by bcrigler** [comment]
ditto

**Comment by glen-84** [comment]
`Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3`

**Comment by pugnascotia** [comment]
If I'm reading this thread correctly, Bootstrap have addressed this:

https://github.com/twbs/bootstrap/issues/16834

However it's targeted at v3.3.7, which isn't available yet.

**Comment by hakuno** [comment]
Okay, Bootstrap `3.3.7` is released. And Datepicker `1.7.0` isn't working. Any help? I can't get it working with jQuery `3.1.0` right now.

**Comment by joantorres** [comment]
Same problem here. Any workaround other than going back to jQuery 2?

**Comment by lucasmm** [comment]
for now i'm using this in bower.json

`"bootstrap-datepicker": "https://github.com/eternicode/bootstrap-datepicker.git#e48ea20"`

e48ea20 is commit where correction has been made.

**Comment by glen-84** [comment]
jQuery migrate shows the following:

```
JQMIGRATE: jQuery.unique is deprecated, use jQuery.uniqueSort
JQMIGRATE: jQuery.fn.bind() is deprecated
```

**Comment by acrobat** [comment]
I should be able to make some time next week to look into this issue

**Comment by rhpot1991** [comment]
Bit by this when upgrading NuGet packages.  Previously Bootstrap didn't support jQuery 3, but now that they do I am free to upgrade.  I get an empty date picker when jQuery 3 is in place.

**Comment by evanleck** [comment]
Bootstrap v4 just added support for jQuery 3 with the [alpha 3 milestone](https://github.com/twbs/bootstrap/milestone/35?closed=1).

Running against that, I see an issue with `display: none` on `.datepicker-months`, `datepicker-years`, `datepicker-decades`, and `datepicker-centuries`. They all remain hidden even once `div.datepicker` is shown.

**Comment by acrobat** [comment]
It seems that #1964 fixes the jquery3 iqque. Can you guys test and confirm the patch?

**Comment by glen-84** [comment]
@acrobat #1958 looked like a better (and cleaner) fix to me, but I don't have time to test it right now.

**Comment by evanleck** [comment]
@glen-84 @acrobat I've updated my code with that fix and it works fine for me.

**Comment by acrobat** [comment]
PR #1958 was merged in master and the fix is backported to 1.6 in https://github.com/eternicode/bootstrap-datepicker/commit/a923be23ef98046f254206ff98366eb8b3fc6e1f. A new version (1.6.2) was pushed and published

**Comment by priley86** [comment]
@acrobat hi, can you explain why `jQuery.unique` was left in, and we have not merged `jQuery.uniqueSort`? [uniqueSort](https://api.jquery.com/jQuery.uniqueSort/) is supported by jQuery `1.1.2+`

**Comment by acrobat** [comment]
I overlooked that extra fix, will make some time and change the method and push a new release!

**Comment by acrobat** [comment]
@priley86 Can you test commit https://github.com/eternicode/bootstrap-datepicker/commit/df4542c95ba126a3847e5d275d71897b8f79b086 if this is enough for your issue?

**Comment by priley86** [comment]
@acrobat +1 this will resolve this issue

**Comment by acrobat** [comment]
I've pushed a new release with the uniqueSort fix! https://github.com/eternicode/bootstrap-datepicker/releases/tag/v1.6.3

**Comment by rhpot1991** [comment]
Anyone know how this gets pushed to NuGet?

**Comment by acrobat** [comment]
@scott-xu maintains the nuget package! Ping @scott-xu

**Comment by scott-xu** [comment]
pushed
