### ISSUE TITLE
problem in ie8 when using with webshims forms-ext polyfill

### ISSUE THREAD

**Issue by drewB** [eternicode/bootstrap-datepicker#196]
If you use webshims (http://afarkas.github.com/webshim/demos/) 'forms-ext' polyfill the datepicker is unusable in ie8.  It loses its background, says "PrevNext" instead of having arrows and all the numbers gets cramped together.  I suspect it is related to 'forms-ext' providing HTML5 date, number, range types but don't know exactly what is going on.

**Comment by acrobat** [comment]
Closing this issue as it should be fixed with webshims 1.10.x version
