### ISSUE TITLE
upgrade guide

### ISSUE THREAD

**Issue by Nuruddinjr** [eternicode/bootstrap-datepicker#1962]
### Expected behaviour
I have installed  Stefan Petre's original code library in my template which I got,however I want to upgrade to this library. When I have old library it works fine, but after i Change datepicker doesn't show.
### Actual behaviour
Tell us what happens instead.

### Datepicker version used
Last version is used. 
ex. 1.6.1.

### Example code
`$('.datepicker').datepicker({
                format: 'mm/dd/yyyy'
            });`

Please let me know what could possibly gone wrong while upgrade?

**Comment by acrobat** [comment]
I really can't say what went wrong but I'm sure a simple upgrade from stefan's code to this code base is not possible as there is years code changes in this repository.

The example code should work. Closing this issue for now, please comment with a jsfiddle example that has the same problem you are experiencing.
