### ISSUE TITLE
Bootstrap date picker in arabic showing extended white backgound

### ISSUE THREAD

**Issue by asmaazoghbi** [eternicode/bootstrap-datepicker#1967]
In arabic language bootstrap has an extended white background.
The position of the datepicker is not getting over the input as in (english datepicker)

Please any help

**Comment by musabsudan** [comment]
Same here

**Comment by timmorey** [comment]
I think I'm running into this issue too.  There is an open pr that fixes the problem I'm seeing: https://github.com/eternicode/bootstrap-datepicker/pull/1973.

**Comment by acrobat** [comment]
Fixed in #1973

**Comment by anurajmadathil** [comment]
On the CSS 'bootstrap-datetimepicker.css', line 23:

.datetimepicker.datetimepicker-rtl {
	direction: rtl;
	right: auto; /*Added extra fixed the issue for me*/
}
