### ISSUE TITLE
Code breaks minification

### ISSUE THREAD

**Issue by Lambik** [eternicode/bootstrap-datepicker#1969]
Hi,

### Expected behaviour
I use gulp to minify (uglify) my code, including yours as a bower component. The uglify process errors out because of:

    SyntaxError: Unexpected token name «$», expected punc «)»]

The line it is referring to is probably this:

    replace:function(b){b&&(a.isArray(b)||(b=[b]),this.clear(),this.push.apply(this,b)$.isFunction()},clear:

See the random $.isFunction().

### Datepicker version used

The latest master, because my bower.json is "bootstrap-datepicker": "*"

https://github.com/eternicode/bootstrap-datepicker/commit/6788e92fc9d277a93c7be5e11236c0ec583af679

**Comment by jk2K** [comment]
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.3/js/bootstrap-datepicker.min.js
I have the same problem,  `Uncaught SyntaxError: Unexpected identifier`

**Comment by Lambik** [comment]
Indeed, just verified it with setting an explicit bower version: 1.6.3 breaks the minification, while 1.6.2 works.

**Comment by acrobat** [comment]
I don't know what went wrong, but deleted the minified js file and regenerated it. This fixed the issue. New dist files were generated on master and v1.6.4 was pushed with the correct minified file!

Thanks for reporting @Lambik

**Comment by Lambik** [comment]
Thanks for the quick fix!
