### ISSUE TITLE
Format for setEndDate and setStartDate? 

### ISSUE THREAD

**Issue by alvarotrigo** [eternicode/bootstrap-datepicker#1977]
Documentation doesn't mention which format is expected for `setEndDate` or `setStartDate`.
It refeers to endDate option, which doesn't either explain the required format.

I do not want to base endDate and newDate on the current date, but on a specific date. For example:

```
Fri Aug 19 2016 00:00:00 GMT+0100 (GMT Daylight Time)
```

**Comment by jelhan** [comment]
Conversion is implemented here: https://github.com/eternicode/bootstrap-datepicker/blob/6788e92fc9d277a93c7be5e11236c0ec583af679/js/bootstrap-datepicker.js#L246-L268 It looks like both `Date` object in local time (see implementation of `_zero_time` method which is used for conversion) or a string parsed with `format` option is possible. Should be documented.
