### ISSUE TITLE
nl locale issue, keeps showing english translation

### ISSUE THREAD

**Issue by JayMaree** [eternicode/bootstrap-datepicker#1986]
### Expected behaviour
The calendar we use should show the dutch dateticker language.

### Actual behaviour
I added the dutch(nl) locale to the bootstrap datepicker file but somehow it won't activate the dutch translation.

File which I use: [bootstrap-datepicker.txt](https://github.com/eternicode/bootstrap-datepicker/files/429835/bootstrap-datepicker.txt)

### Datepicker version used
the latest

### Example code

https://jsfiddle.net/mm1zk79v/

**Comment by acrobat** [comment]
This is indeed an issue with the latest master (1.7-dev), I will try to look into to the issue and provide a fix. In the meanwhile you can use the latest stable release 1.6.4. (With 1.6.4 it does still work http://jsfiddle.net/zcvq0yhh/134/)

**Comment by acrobat** [comment]
I've looked more closely into the issue but can' find a real bug. I think my issue was a mixup between minified and non minified files. But the language file works in the current master. See http://jsfiddle.net/zcvq0yhh/137/

Closing the issue for now
