### ISSUE TITLE
How to show empty when date is nulled

### ISSUE THREAD

**Issue by lenamtl** [eternicode/bootstrap-datepicker#1993]
Does the datepicker handle the NULL value as empty or we have to handle the case with custom code ?

**Comment by lenamtl** [comment]
Note: I end up to handle the case with custom code

**Comment by bhargav3** [comment]
@lenamtl Please share the custom code, it might be useful to me and others.

**Comment by lenamtl** [comment]
Hi here is my code I'm using PHP.
It's handle the 3 cases, the field is empty, NULL or having date
`value="<?php if (($ContactValue["contact_expiration"]) == NULL  || "" ) { echo ""; } else { $date = date_create($ContactValue["contact_expiration"]); echo date_format($date, 'd/m/Y');}?>`
