### ISSUE TITLE
Format the date received from changeDate event

### ISSUE THREAD

**Issue by VeeK727** [eternicode/bootstrap-datepicker#2000]
This might be a very stupid question but I'm using the `changeDate` event to receive the date that was selected using jquery. I do get the date but it looks like this "**Mon Feb 01 2016 00:00:00 GMT+0530 (India Standard Time)**". I cannot use this date for any calculations or processing. 

Is it possible to convert it in yyyy-mm-dd format? I tried javascripts's `Date.parse()` but it didn't work?

**Comment by attacking** [comment]
First add an option 'format: "yyyy-mm-dd"' in your datepicker initialization function. In the changeDate handle, you can use $(canlenedar).datepicker('getFormattedDate') to get fromatted date.

**Comment by VeeK727** [comment]
Ah Thanks. That worked. For anyone looking at it in the future, this is the general code I used

```
$('#month').datepicker({
          format: 'yyyy-mm-dd'
}).on('changeDate', function(e) {
    var date = $('#month').datepicker('getFormattedDate');
    console.log(date); // Returns something like 2016-09-15
});
```
