### ISSUE TITLE
date time picker not get closed after selecting date

### ISSUE THREAD

**Issue by sushantlal** [eternicode/bootstrap-datepicker#2007]
### Expected behaviour
calendar should be closed after selecting date

### Actual behaviour
will close when u click anywhere outside of it 

### Datepicker version used
Version 3.0.0
-------------------------------
bootstrap-datetimepicker.js
https://github.com/Eonasdan/bootstrap-datetimepicker
### Example code

http://eonasdan.github.io/bootstrap-datetimepicker/
can refer this link i have downloaded from here

$(document).ready(function () {
    var currentDate = new Date();
    jQuery('#gtdDate').datetimepicker({
        format: 'DD-MMM-YYYY HH:mm',
        useCurrent: false,
        autoclose: true,
        keepOpen: false,
    })
});

<input type="text" id='gtdDate' ng-model="ExDate" placeholder="Select date" readonly>

**Comment by acrobat** [comment]
This is the eternicode/bootstrap-datepicker repository. You use the Eonasdan/bootstrap-datetimepicker, if you have issue with the library you should [report the issues to them](https://github.com/Eonasdan/bootstrap-datetimepicker/issues)!
