### ISSUE TITLE
Using 'setDate' or 'update' to change the datepicker date not updating the view

### ISSUE THREAD

**Issue by devqualwebs** [eternicode/bootstrap-datepicker#2018]
### Expected behaviour
setDate or update should change the selected date of datepicker including view also.
### Actual behaviour
It is only changing the date of datepicker but not updating the view of datepicker calendar.  I have included the jsfiddle link below in which I console the result on event 'changeDate' it is also working but not updating the view.
### Datepicker version used
Using 1.6.4 

[https://jsfiddle.net/devqualwebs/5gvn5w1y/9/](https://jsfiddle.net/devqualwebs/5gvn5w1y/9/)

**Comment by akashk92** [comment]
hey there I am facing same problem,
I am setting date using setDate method , but datepicker still shows today date .
