### ISSUE TITLE
Selecting the already selected date clears the field.

### ISSUE THREAD

**Issue by altinselimi** [eternicode/bootstrap-datepicker#2033]
### Expected behaviour
It should not clear the field.

### Actual behaviour
It clears the field.

### Datepicker version used

1.6.4.

### Example code

Jsfiddle example to reproduce the problem.

Its the same as in the demo, but it's not happening in the demo. I am using it in an angular web app by the way.

**Comment by acrobat** [comment]
[This is an example with 1.6.4](http://jsfiddle.net/zcvq0yhh/147/) and when selecting the previous selected date this doesn't clear the value

Can you provide an example that shows this problem

**Comment by altinselimi** [comment]
I just set up a new web app boilerplate and your plugin works flawlessly, its probably my project that got some plugin which is conflicting with your datepicker. Is there any quick way of finding out which except of turning them all off one by one ? (I use ui-bootstrap from angular-ui)

**Comment by acrobat** [comment]
I don't have any experience with angular so really don't know what could cause a conflict. So my advice would be indeed turning off and on one by one :smile: 

I'm going to close this issue for now as it is nog bug. But maybe someone with angular experience could provide some insights on this!

**Comment by Azaret** [comment]
@altinselimi Don't know if you solved your issue, but the dev tools is your friend (at least on chrome :D). On Chrome you can right click on your input and ask it to break when dom element is edited. It might help you find what is emptying your input.
