### ISSUE TITLE
datepicker doesn't update if the current date value in the input field was entered with the datepicker

### ISSUE THREAD

**Issue by MartijnR** [eternicode/bootstrap-datepicker#240]
I noticed that the datepicker only updates after date changes made in the input field directly if the first date was entered via keyboard (or javascript). If the first date was selected from the datepicker, any subsequent changes made directly in the input field do not update the datepicker. Manually calling $(selector).datepicker('update') also doesn't work (which I presume is the same issue). 

So to replicate:
- instantiate datepicker as component with date-format="yyyy-mm-dd"
- load form with empty date field
- select "2012-10-03" from datepicker
- change this to "2012-10-01" by keyboard directly in the input field
- datepicker still shows 2012-02-02

Awesome work by the way!

**Comment by acrobat** [comment]
Closing this issue for now, please comment or reopen with an jsfiddle example if this should still be an issue!
