### ISSUE TITLE
AMD Support

### ISSUE THREAD

**Issue by angelyordanov** [eternicode/bootstrap-datepicker#280]
Hi @eternicode,

I'm thinking of implementing AMD support for `bootstrap-datepicker` and would like to know what do you think about it.

What i would propose is wrap the current datepicker code in something like this

    (function (factory){
        if (typeof define === 'function' && define.amd){
            define("datepicker", [ "jquery", "i18n!./locale/dates" ], function ($) {
                return factory($, window, document);
            });
        } else {
            window.jQuery.fn.datepicker = factory(window.jQuery, window, document);
        }
    })(function ($, window, document, undefined) {
        var datepicker = ...
        return datepicker;
    });

And the locales like this

    (function (factory){
        var dates = factory();
        if (typeof define === 'function' && define.amd){
            define(dates);
        } else {
            $.fn.datepicker.dates['en'] = dates;
        }
    })(function () {
        return {
            days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
            daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
            daysMin: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
            months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
            monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
            today: "Today"
        };
    });

The locale files should be moved each in its own directory. The default strings should be in `/locale/root/dates.js` and a specific locale, french for example, should be in '/locale/fr/dates.js`.

The non-amd usage would remain the same, with the exception of the changed file paths for the locales.

Thanks,
Angel

**Comment by nikolas** [comment]
Yeah, same here, @MaxArt2501.

**Comment by acrobat** [comment]
AMD/requireJs support will be added in #1196

**Comment by acrobat** [comment]
Closing this issue as #1196 was merged!
