### ISSUE TITLE
Datepicker arrow out of place when input inside a relatively positioned div in Safari

### ISSUE THREAD

**Issue by jsuter** [eternicode/bootstrap-datepicker#324]
I noticed some strange behaviour in Safari when I had an input field inside a div that has been positioned relatively:

![Screen Shot 2013-01-15 at 11 26 10 AM](https://f.cloud.github.com/assets/641801/68975/86c8c3a6-5f49-11e2-8985-2b6393a476c3.png)

I narrowed it down to the :before { and :after { inside the datepicker.less file. Changing these values to 	&-dropdown:before { and &-dropdown:after { fixes the issue. This is also consistent with the .css file if you build it from the build_standalone.less.

**Comment by acrobat** [comment]
@jsuter can cheyck if the bug still occurs with the 1.3.1 version and with the latest safari? If so can you provide a jsfiddle example showing this error? You can use this [base jsfiddle](http://jsfiddle.net/g02L8z8y/) to start from

**Comment by hebbet** [comment]
closing old tickets, with no newer reply.
