### ISSUE TITLE
Scroll page, when show datepicker with fixed input

### ISSUE THREAD

**Issue by orloffv** [eternicode/bootstrap-datepicker#384]
http://fiddle.jshell.net/EGXu9/9/show/

![Screen Shot 2013-03-01 at 2 24 53 PM](https://f.cloud.github.com/assets/504986/209097/55cdca74-825a-11e2-92e0-21c862b9d1e0.png)
![Screen Shot 2013-03-01 at 2 25 02 PM](https://f.cloud.github.com/assets/504986/209096/55ada7bc-825a-11e2-897d-2c9339575f7f.png)
![Screen Shot 2013-03-01 at 2 25 11 PM](https://f.cloud.github.com/assets/504986/209095/559293aa-825a-11e2-90fd-74b1cfb11197.png)

**Comment by acrobat** [comment]
Fixed in #918!

**Comment by acrobat** [comment]
Issue was fixed in #918 but i discovered still a small issue when page is scrolled before opening the datepicker. I will try to fix this error then this issue should be fixed

**Comment by yoyos** [comment]
I have an issue related to this fix and appendOffset.top in bootstrap3:

https://github.com/eternicode/bootstrap-datepicker/issues/1364
