### ISSUE TITLE
Parsing date with format when value in another format

### ISSUE THREAD

**Issue by solilin** [eternicode/bootstrap-datepicker#445]
Input field has format 'mm-dd-yyyy'. After I'll write something like '05-27-09' I'll get 1909 year instead 2009, it's very uncomfortably. For example jquery ui datepicker works more transparently in this question (http://jqueryui.com/datepicker)

**Comment by FlanTech** [comment]
I second this request.  If I use datepicker for a date of birth, user is more likely to type in value than use picker.  Would be nice if they could type in two-digit year even when format is set for four digit year.

**Comment by dlurton** [comment]
I "third" this request.  My QA person just filed a bug because "0/14/15" results in a date of Jan 14th, 15 and not Jan 14th, 2015!

**Comment by Azaret** [comment]
Please refer to #1629 and #1556

**Comment by ajb** [comment]
I would recommend https://github.com/eternicode/bootstrap-datepicker/pull/1631 instead.

**Comment by Azaret** [comment]
Sure :D well there is many opened PR and tickets about this whole Date thing.
I took the most recent and discussed one ;)
We should soon enough reach a consensus and poke hard @acrobat to merge it so we can move on and close half of the tickets...

**Comment by ajb** [comment]
@Azaret yup, no problem! Just wanted to make sure that the folks in this thread saw #1631 :smile:

**Comment by acrobat** [comment]
This bug is fixed with the `assumeNearbyYear` option from #1631. Here is an example on how to use this option (will be release with 1.6.0)

```
$('#datepicker').datepicker({
        format: 'dd.mm.yy',
        assumeNearbyYear: true
    });
```
