### ISSUE TITLE
"setClean" method request

### ISSUE THREAD

**Issue by buehler** [eternicode/bootstrap-datepicker#465]
It would be nice, if we could have a method to set the elements val to emptystring.

For some reasons it's annoying that the actual date is set into the inputfields value. It would be cool to have some possibilities to control that.

**Comment by Azaret** [comment]
Hi, sorry for the late reply, is this still an issue for you ?
If it is, could you elaborate a bit more on what you're expecting ?

**Comment by buehler** [comment]
Hey @Azaret 
Better late than never :wink: 

I have nooo idea what I was thinking back then or what the issue was. I think I had some project that required an empty value in the input field when the clear button is pressed.

But as long as I don't stumble over the issue or the "feature request" again, I suggest we close this ticket :grin: 

Cheers
Chris
