### ISSUE TITLE
Option to assume current century for parsing with format m/d/yyyy

### ISSUE THREAD

**Issue by kevinwmerritt** [eternicode/bootstrap-datepicker#491]
Datepicker should parse date 6/12/13 as 6/12/2013 when date format is m/d/yyyy

**Comment by acrobat** [comment]
This bug is fixed with the `assumeNearbyYear` option from #1631. Here is an example on how to use this option (will be release with 1.6.0)

```
$('#datepicker').datepicker({
        format: 'dd.mm.yy',
        assumeNearbyYear: true
    });
```
