### ISSUE TITLE
Internal Date Variables exposed

### ISSUE THREAD

**Issue by GevatterGaul** [eternicode/bootstrap-datepicker#537]
The internal Date Variables are exposed through the API. Consider this:

d = new Date('X');
$('datepicker').datepicker('setStartDate', d);
d.setDate(d.getDate()+7);
$('datepicker').datepicker('setDate', d);

Expected Behaviour:

Start Date should be "X", Date "X+7".

Actual Behaviour:

Both Values are "X+7"

Explanation:

The Date Variable is passed by reference, and not copied, when it enters the datepicker. Same applies to the getters, where you can gain access to internal Variables.

Can someone confirm this as a bug?

**Comment by acrobat** [comment]
I've tried this with the latest release and I can't reproduce the problem! Can you confirm it's not an issue with the 1.3.1 release?

Example: http://jsfiddle.net/g02L8z8y/3/
