### ISSUE TITLE
Removing glyphicons dependency made it hard to use icons

### ISSUE THREAD

**Issue by timmywil** [eternicode/bootstrap-datepicker#610]
I'd like to use my own icons, and I'm sure some would like to continue using bootstrap's icons. The use of the html character codes makes it hard to use any icons because you see that html character next to any pseudo elements. The only option I see (if you don't want to edit bootstrap-datepicker manually) is to manipulate the html after it's added to the dom to get rid of the arrow characters.

I suggest adding an option to exclude those characters.

**Comment by Azaret** [comment]
Gonna work on implementing this option https://github.com/eternicode/bootstrap-datepicker/pull/1007#issuecomment-113084646

**Comment by acrobat** [comment]
Fixed in #1700 and will be released with 1.6
