### ISSUE TITLE
Missing Documentation for embedded mode

### ISSUE THREAD

**Issue by econic** [eternicode/bootstrap-datepicker#699]
There's a data-api example and a js example for embedding the datepicker - both don't give hints on how to have it set the value of an existing input[type="hidden"].

There should be comments on how to effectively use the embedded mode.
Or did i just not find them?

**Comment by acrobat** [comment]
@econic do you mean an example showing the embedded mode + listening on the changeDate and then fill a hidden input field?

**Comment by econic** [comment]
Yes @acrobat, that's what i meant.
You load the page with an existing hidden form input field in the dom, which then should be managed with an embedded datepicker (initialized during or after pageload).

**Comment by SeanLF** [comment]
For the time being, this might help. This will get the values from the date picker, format them as indicated in date picker options and 'paste' them in the element with ID my_hidden_input. This also works with <code>multidate: true</code>.
```js
$(".datepicker").on("changeDate", function(event) {
    $("#my_hidden_input").val(
        $(".datepicker").datepicker('getFormattedDate')
     )
});
```

**Comment by acrobat** [comment]
Thanks @SeanLF

**Comment by econic** [comment]
Well, ok that works of course.
I rather meant an option to just have that initialized by the datepicker itselt.
Just like
``$('.datepicker').datepicker()`` initializes it on a normal input,
``$('.hidden-datepicker').datepicker({fooBar: true})`` could initialize it in embedded mode for a hidden input.

Anything like that on the roadmap?
This would be especially useful for people working only with embedded datepickers in generic forms, because, well, it's the easy way.

**Comment by acrobat** [comment]
That's not something that is currently planned as a feature, but please create a new issue with your last description of the feature and we can plan it into a future release!

**Comment by SeanLF** [comment]
Assuming you use <code>,</code> to separate your dates. This script won't work if your date format is dd/mm/yyyy (except on Chrome).

```js
$(document).ready(function(){
    var dates = $('#my_hidden_input').text().split(',');
    var jsDates = [];
    if(dates[0] != ""){
      for(var date in dates){
        jsDates.push(new Date(dates[date]));
      }
      $('.datepicker').datepicker('setDates', jsDates);
    }
  })
```

**Comment by econic** [comment]
have a look at #1265 for the feature request
