### ISSUE TITLE
Inconsistent Copy / Paste Behavior

### ISSUE THREAD

**Issue by austenc** [eternicode/bootstrap-datepicker#778]
When you copy/paste a date (like '09/04/1948') into a datepicker field with `Ctrl+V` and hit `Tab` the datepicker works as expected, updating on paste / keeping the date you pasted once you hit tab. 

However, If you (may have to refresh prior to this) paste that same date, 09/04/1948 into the field using **Right Click -> Paste** and then press `Tab` it will change the date you pasted to the default date.

Win7 x64, Google Chrome

[Feel free to confirm on this Bootply](http://bootply.com/104843)

**Comment by rhoggSugarcrm** [comment]
I'm working on a fix for this - it already works on Firefox and Chrome for my company's use cases. Testing for Safari and IE is in progress.

We need to have this fix into version 1.3.0, but we can fork that specific version ourselves if needed.

Message me if you have any questions. I haven't pushed my changes to my fork yet, but I will soon.

**Comment by rhoggSugarcrm** [comment]
Ok, looks like my fix is working on FF, Chrome, Safari, IE 11, and IE 9. @acrobat are there any other browsers you would want me to test on?

My apologies that I can't post the code just yet - I need to make 100% sure I have legal permission - but expect it shortly (in a few days at the absolute worst).

**Comment by acrobat** [comment]
Fixed in #1297
