### ISSUE TITLE
Bind event bug/issue

### ISSUE THREAD

**Issue by qinbx** [eternicode/bootstrap-datepicker#783]
Hi,

I met an bind event issue.
```
<input type="text" id="inputText1" />

<script>
  $("#inputText1").change(function(){  alert("change") }).datepicker();
</script> 
```

**When i change the date for #inputText1 using datepicker plugin, the alert shows 3 times.**

You can try on this demo page:
http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&todayBtn=false&language=en&orientation=auto&autoclose=on&keyboardNavigation=on&forceParse=on#sandbox

Hope there has a solution, thanks.

**Comment by acrobat** [comment]
Fixed in #1337
