### ISSUE TITLE
documentation confusion

### ISSUE THREAD

**Issue by gfairchild** [eternicode/bootstrap-datepicker#809]
There are several aspects of the documentation and release that are confusing.

1. In the release css directory, there are 2 css files, datepicker.css and datepicker3.css. What's the difference between these? When should one be used over the other? Does the 3 indicate Bootstrap 3 support? CSS 3 support? Something else? bootstrap3.css is never mentioned in the documentation.

2. The instructions regarding usage are a little confusing for the Bootstrap noob (like myself). I know now that I should use *either* the JS method (e.g., `$('.datepicker').datepicker()`) or the data API method. I think the documentation should be split up to make this more obvious, with a few more examples showing it in action. For example, the current [Usage](http://bootstrap-datepicker.readthedocs.org/en/latest/#usage) section is organized like this:

**Usage**
JS instructions here

**Data API**
Data API instructions here

This is confusing because it makes it seem as though you need to include the JS and then optionally include the Data API on top of that. I think it could be clearer if it were formatted this way:

**Usage**
Brief paragraph describing that there are two ways of using bootstrap-datepicker, one using JS, and the preferred way, using Bootstrap's Data API.

**Option 1: JavaScript**
JS instructions

**Option 2: Bootstrap Data API**
Data API instructions

Maybe the data API option should be option 1 since it's really the preferred way to do it. Does this make sense? I think reorganizing the instructions in this manner would make it very clear that you should choose one option or the other. Bootstrap's data API isn't described very well on Bootstrap's site either, so it took some playing around to figure out what was going on.

**Comment by acrobat** [comment]
We always welcome additions and fixes to our docs. If anyone would like to help, just open a new pull request with changes you would like to apply. 

Closing this issue for now
