### ISSUE TITLE
Disabled field still allows date picker to change value.

### ISSUE THREAD

**Issue by EminenceHC** [eternicode/bootstrap-datepicker#814]
Even though a field is disabled, the datepicker will allow the value to be changed. How can I disable this?

**Comment by cplaetzinger** [comment]
Sample taken from #800:
http://jsfiddle.net/VUcjY/1/

**Comment by McNetic** [comment]
Well, we use the datepicker as a polyfill for date input fields, and as such, we try to have the behaviour resemble that a native date input field would have. That means: If the field is disabled (or also readonly), the user can not change it's value. I think datepicker should behave in the same way.

**Comment by mediavrog** [comment]
+1 for read only datepicker

**Comment by acrobat** [comment]
Fixed in #1731
