### ISSUE TITLE
Scrolling on mobile device closes datepicker

### ISSUE THREAD

**Issue by berniegp** [eternicode/bootstrap-datepicker#820]
Hello,

When opening a datepicker in a mobile device, the month's grid sometimes cannot be displayed completely (i.e. it's too tall). Scrolling the page to see the rest of the month's grid unfortunately closes the datepicker. This makes it awkward to use this module on mobiles devices. In my tests, changing the event that closes the datepicker from touchstart to touchend fixed the issue.

Here's the diff (sorry, about inline diff, but it's too small to bother forking) :

```diff
bootstrap-datepicker/js/bootstrap-datepicker.js
@@ -355,7 +355,7 @@
 					resize: $.proxy(this.place, this)
 				}],
 				[$(document), {
-					'mousedown touchstart': $.proxy(function(e){
+					'mousedown touchend': $.proxy(function(e){
 						// Clicked outside the datepicker, hide it
 						if (!(
 							this.element.is(e.target) ||
```

**Comment by acrobat** [comment]
Fixed in #1284
