### ISSUE TITLE
Add option for arrows content

### ISSUE THREAD

**Issue by pavolzbell** [eternicode/bootstrap-datepicker#833]
Hello, is there a possibility to add an option for arrows content. I mean now the arrows are hard coded in templates like `<th class="prev">&laquo;</th>` and it would be nice to change `&laquo;` for `<i class="fa fa-long-arrow-left"></i>` for instance, of course with custom options. Thanks :)

**Comment by acrobat** [comment]
Fixed in #1700 and will be released with 1.6
