### ISSUE TITLE
Offsets mess with placement logic

### ISSUE THREAD

**Issue by bbeuerlein** [eternicode/bootstrap-datepicker#849]
In using this component on a new site I am developing, I noticed that the default placement of the datepicker using auto placement seems to not acount for a possible offset of the page itself. I have implemented the class "col-lg-offset-2" on my entire page, and when the browser is large enough to fall under this size, the placing of the datepicker is off by two columns. When i shrink my browser down to the medium size, where I have no offset enabled, the datepicker is placed correctly. 

Any known quick fix to the script that can correct this?

**Comment by hebbet** [comment]
closing old tickets, with no newer reply.
