### ISSUE TITLE
Disable view modes?

### ISSUE THREAD

**Issue by norbiu** [eternicode/bootstrap-datepicker#852]
Whenever you click on the calendar title in the header, it takes you to the "months of the year" view mode. Is there a way to disable the ability to view other view modes or turning off the link without editing the plugin file?

My project requires people selecting dates between certain months of the current year, so it would be nice to have that link disabled, to avoid accidental clicks.

**Comment by Azaret** [comment]
Hi, sorry for the late reply.
If you didn't find out by now, you should be able to do such setting the option `maxViewMode` to `days`:
```js
$('#sandbox-container input').datepicker({
    maxViewMode: 'days'
});
```
