### ISSUE TITLE
Attach to element and get alternative date format.

### ISSUE THREAD

**Issue by vmasto** [eternicode/bootstrap-datepicker#856]
Hi, if you have a look at this demo (I know the scripts aren't the same) http://www.eyecon.ro/bootstrap-datepicker/ you can see an example where the datepicker is attached to anchor elements (link buttons) and update their data-date attribute on changeDate. Is there a way to do this in the current script or a way to get the date that's set in the specified format (e.g. yyyy/mm/dd) other than the timezone format?

**Comment by Azaret** [comment]
Hi, this might be late, but it is possible:
```
$('#mylink').datepicker({
  changeDate: function (date){
    $('#mylink').attr('data-date', date.getFullYear() + '/' + (date.getMonth() + 1) + '/' date.getDate());
  }
}).on('click', function (e){
  e.preventDefault();
});
