### ISSUE TITLE
Question: change value on hidden input with inline/embedded datepicker

### ISSUE THREAD

**Issue by alessandroraffa** [eternicode/bootstrap-datepicker#886]
How to dynamically change the value of an hidden input, using the same format specified in the options?

This is my code:

```html


  <div id="date-datepicker">
    <div>
      <input type="hidden"
             name="date"
             value="">
    </div>
  </div>

```

```javascript


  $('#date-datepicker div').datepicker({
    format: "dd/mm/yyyy",
    todayBtn: "linked",
    language: "it",
    autoclose: true,
    todayHighlight: true,
    clearBtn: true
  });

```

Thanks

**Comment by m-aciek** [comment]
I suggest you to put the input out of datepicker's div. I tested it and datepicker crashes if have something there.

That's my workaround: (here for multidate: false)
```javascript
$("#date-datepicker div").on("changeDate", function(event) {
    var picker = $(event.target);
    $("input[type='hidden'][name='date']").val(
        picker.datepicker().__proto__.datepicker.DPGlobal.formatDate(
            picker.datepicker("getDate"), "dd/mm/yyyy", "it"
        )
    )
});
```

**Comment by SeanLF** [comment]
I looked through the .js file and found the getFormattedDate function:

$("#date-datepicker div").on("changeDate", function(event) {
    $("input[type='hidden'][name='date']").val(
        $('#date-datepicker div').datepicker('getFormattedDate')
    )
});

**Comment by acrobat** [comment]
The examples of @m-aciek and @SeanLF as cases on how to fix this issue. And issue #699 was fixed with an example added to the docs. So closing this issue as the question is resolved
