### ISSUE TITLE
dd.mm.yy 01.01.2014 resolves to 1. Jan 4014

### ISSUE THREAD

**Issue by stefankleff** [eternicode/bootstrap-datepicker#919]
If the fomat is set to dd.mm.yy and the given input is 01.01.2014 its resolved to 1. Jan 4014. There seems to be a detection that the given year has 4 instead of 2 digits, but the calculated date should be 1. Jan 2014  instead.

**Comment by acrobat** [comment]
Looks like this issue is fixed in version 1.5. See example [here](http://jsfiddle.net/zcvq0yhh/12/). Closing this for now, create a new issue is this problem still occurs!
