### ISSUE TITLE
ISO date formatting

### ISSUE THREAD

**Issue by raveren** [eternicode/bootstrap-datepicker#930]
Hey there, excellent plugin, waiting patiently for some resolution on an integrated timepicker, however currently I am in need to pick ISO dates from the calendar, which I temporary achieve by allowing the user to only select mondays, however the result value is not displayed as I wish and can not be interpreted by the plugin.

PHP's [date](http://php.net/manual/en/function.date.php) supports it via `o-W` format, so does the dreadful jQuery UI: http://api.jqueryui.com/datepicker/#utility-formatDate

Could you please add similar functionality?

**Comment by abibell** [comment]
I like the idea. In our case, we want to pick dates in local formats but store in UTC, for user friendliness. I will add this feature

**Comment by acrobat** [comment]
Fixed in #1582
