### ISSUE TITLE
Using format "M d, yyyy" to preset the input field isnt recognized by datepicker

### ISSUE THREAD

**Issue by stringbeans** [eternicode/bootstrap-datepicker#938]
Suppose I have an input field

<input type='text' id='test' value='May 03, 2014' />

And I initialize it with the following:

$("#test").datepicker({format: 'M dd, yyyy'});

When I click into the field, May 3 2014 is not highlighted in the datepicker popup. Also if I do not choose a date and just click outside of the popup it will append today's date to the existing value of that field.

**Comment by acrobat** [comment]
@stringbeans can you confirm if this is still an issue with 1.3.1? If so please provide a jsfiddle example, you can use [this jsfiddle](http://jsfiddle.net/g02L8z8y/) as a start

**Comment by hebbet** [comment]
closing old tickets, with no newer reply.
