### ISSUE TITLE
Disable/enable certain dates dynamically

### ISSUE THREAD

**Issue by gercheq** [eternicode/bootstrap-datepicker#940]
If you're building a reservation system with a date picker, you need to disable/enable certain dates not only a specific day of the week. Currently there's no way to implement this using this version of the datepicker.

**Comment by vinograd19** [comment]
I think add [beforeshowday](http://bootstrap-datepicker.readthedocs.org/en/release/options.html#beforeshowday) is the best practice for this case

**Comment by acrobat** [comment]
It looks like you have 2 options for this

- beforeShowDay callback
- disabledDates option (will be available in 1.4.0) which was added in #515
