### ISSUE TITLE
checkin and checkout

### ISSUE THREAD

**Issue by CARocha** [eternicode/bootstrap-datepicker#947]
Hi, in original code the eyecode have example for check-in and checkout
http://www.eyecon.ro/bootstrap-datepicker/
Disabling dates in the past and dependent disabling.
this code not working whit this version of bootstrap-datepicker?

var nowTemp = new Date();
var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
 
var checkin = $('#dpd1').datepicker({
  onRender: function(date) {
    return date.valueOf() < now.valueOf() ? 'disabled' : '';
  }
}).on('changeDate', function(ev) {
  if (ev.date.valueOf() > checkout.date.valueOf()) {
    var newDate = new Date(ev.date)
    newDate.setDate(newDate.getDate() + 1);
    checkout.setValue(newDate);
  }
  checkin.hide();
  $('#dpd2')[0].focus();
}).data('datepicker');
var checkout = $('#dpd2').datepicker({
  onRender: function(date) {
    return date.valueOf() <= checkin.date.valueOf() ? 'disabled' : '';
  }
}).on('changeDate', function(ev) {
  checkout.hide();
}).data('datepicker');

but with this version not working why any help?

Cheers

**Comment by IndraDarmawan** [comment]
Hi CARocha, i have same problem too.
But i found a solution to fix it.
Let's try this code for bootstrap datepicker like on http://eternicode.github.io/bootstrap-datepicker

$('#dpd1').datepicker({ 
	todayBtn: "linked",
	todayHighlight: true,
	autoclose: true
}).on('changeDate', function(e){
	$('#dpd2').datepicker({ 
		autoclose: true
	}).datepicker('setStartDate', e.date);
	$('#dpd2').focus();
}); 

Let's check line  " datepicker('setStartDate', e.date); " , it will set startDate of datepicker dpd2.
Hope it help you.

**Comment by udaraaot** [comment]
Hi, this doesn't work for me. Can you guys please help? This is my code. But this doesnt seem to work. 

`$('.input-daterange').bootstrapDP({
		
		startDate: "+0d",
		defaultViewDate : "+0d",
	  	format: "dd-M-yyyy",
		maxViewMode: 3,
 		autoclose: true,
		orientation: "bottom auto",
		disableTouchKeyboard:true,
  		
	}).on("changeDate", function(e) {
				
				$('#FromDate').bootstrapDP('setStartDate', e.date);
    			$("#ToDate").focus(); 	//popup up end date calendar
 				var selectedFromDate = $('#FromDate').bootstrapDP("getDate");
				var selectedToDate = $('#ToDate').bootstrapDP("getDate");
				$("#from").val(dateFormat(selectedFromDate,'yyyy-mm-dd'));
				$("#to").val(dateFormat(selectedToDate,'yyyy-mm-dd'));
				
   	}); `
