### ISSUE TITLE
Two Fields with same date in different format

### ISSUE THREAD

**Issue by charldarwin** [eternicode/bootstrap-datepicker#956]
Hi, this is first time I post here but I can't find a solution for this. I would like to input the date in two fields at same time with different format. Example:

Field one: Monday, 25 May 2014
Field two(hidden type): 25-05-2014

I should say that field two will be a hidden field. So Only should enter date to field one and automatically the field two should add the date in other format.

**Comment by acrobat** [comment]
In 1.5.0 the format option was extended with 2 new sub-options `toValue` and `toDisplay`. See docs [here](http://bootstrap-datepicker.readthedocs.org/en/v1.5.0/options.html#format)

You could use these new options to solve your problem!
