### ISSUE TITLE
Click function override

### ISSUE THREAD

**Issue by CalvinGrain** [eternicode/bootstrap-datepicker#966]
Is there a way to override click function on a date?
Well the idea is when user clicks on a date a popup appears with a list of events in that day and user can check or uncheck the date from popup. I need to override click function to ignore add or remove class="active".

**Comment by mjanda** [comment]
A bit late, but you can use changeDate event

$('#...').datepicker().on('changeDate', function(e){ ... your code ... });

**Comment by acrobat** [comment]
Answer provided, closing issue
