### ISSUE TITLE
Remove year link from the datepicker

### ISSUE THREAD

**Issue by anurag12345** [eternicode/bootstrap-datepicker#969]
I am using month datepicker that is showing the months but the problme it is also showing the years link at the top of datepicker which i do no want.
Please help me out.

**Comment by acrobat** [comment]
This config can be used to achieve that

```
$('#datepicker').datepicker({
        //...
          minViewMode: 1,
    			maxViewMode: 1
    });
```
See example: http://jsfiddle.net/zcvq0yhh/13/

Closing for now, please open a new issue if you (still) experience a bug
