### ISSUE TITLE
escape key opens the datepicker

### ISSUE THREAD

**Issue by jdanyow** [eternicode/bootstrap-datepicker#981]
pressing escape opens the picker:

https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L1115

This seems counter-intuitive and is problematic when escape key is bound to other things such as a shortcut key for closing a bootstrap modal.  Consider the scenario where the focus is in the datepicker input and the user presses escape to close a bootstrap modal.  The modal closes and an orphaned datepicker popup appears above the underlying screen.

As a workaround I've commented lines 1115 and 1116 out in my copy of the picker js but I think this behavior should be removed from the mainline project.

**Comment by acrobat** [comment]
Fixed in #1305
